### ISSUE TITLE
Strange background behavior

### ISSUE THREAD

**Issue by osk2** [google/blockly#1031]
I'm facing a weird bug which cause background of Blockly shows random image

Normal background should be like 

![supki](https://cloud.githubusercontent.com/assets/705280/24891115/4b2217be-1ea6-11e7-86e5-f6c2837ff2a5.png)

But instead, Blockly shows something like below

![8rntu](https://cloud.githubusercontent.com/assets/705280/24891048/fbc07abc-1ea5-11e7-9773-8cbcf68e92f8.png)

Please have a look of the [screen recording](https://youtu.be/9RMzcQJglNU)

This happens mostly when I switch back from another tab or window, and most images appears on background are (inverted or rotated) favicon

I also found that this issue only happens in Google Chrome

Someone on [Stackoverflow](http://stackoverflow.com/questions/43274192/blockly-workspace-background-shows-random-image?noredirect=1#comment73718645_43274192) point me out that this might be cause by `<base>` tag, but it seems like Blockly didn't use `<base>` tag?

Even I change [this line](https://github.com/google/blockly/blob/master/core/workspace_svg.js#L348) as comment on Stackoverflow to use absolute URL, All I got is a blank background

Is this a bug of Blockly or Chrome? or I misconfigured something? :/

---
Some additional info of my environment
- MacOS 10.12.4
- Chrome 56

**Comment by NeilFraser** [comment]
Wow, that is stunning!  I've never seen anything like it before.  That has to be a Chrome bug.  Looks pretty serious too, since it is leaking information from other sites.

Three questions:
* Chrome 56 is already obsolete, does it still happen in Chrome 57?
* If it is in 57, can you recreate this with [Chrome Canary](https://www.google.com/chrome/browser/canary.html) (which will become Chrome 59)?
* Can you recreate this on [the public demo](https://blockly-demo.appspot.com/static/demos/code/index.html)?

I'll leave it up to the team to see if there is anything on Blockly's side, but I would suggest that if this can be recreated in Canary, that you raise [a bug with Chrome](https://bugs.chromium.org/p/chromium/issues/list).

**Comment by osk2** [comment]
@NeilFraser Thanks for the response

Just upgraded to Chrome 57 and installed Chrome Canary, and my answer to all three problems is yes

I'll try to submit this bug to Chrome, and update this issue once I have any news 😏

**Comment by rachel-fenichel** [comment]
Wow.

I can't repro this at all.  K

**Comment by rachel-fenichel** [comment]
I can't repro this, but keep us updated if Chrome has any comments.

(Also, wow.)

**Comment by osk2** [comment]
After doing some digging, I found that the issue not only happens in Blockly

I am almost sure this is bug of Chrome. Already submitted bug to Chromium, will update this issue if I have news

**Comment by picklesrus** [comment]
We've now seen this once too. I dug up the chromium bug so we could track it: https://bugs.chromium.org/p/chromium/issues/detail?id=710725

**Comment by osk2** [comment]
Finally they can reproduce this bug. It seems like this bug only exists on MacOS with Intel HD 6000 GPU.

Disable `Use hardware acceleration when available` can temporarily fix the bug

**Comment by rachel-fenichel** [comment]
I'm closing this since it's definitely in Chrome and not Blockly.  Thanks for giving them such a detailed report and repro cases.
