### ISSUE TITLE
Is new generators is welcome ?

### ISSUE THREAD

**Issue by tst2005** [google/blockly#104]
Hello,

I found a implementation of Lua  generator for blockly ([here](https://github.com/espertus/blockly-lua)).
I see the PHP generator was added.

Is any generator is welcome ?

Best Regards,

**Comment by NeilFraser** [comment]
Neither PHP nor Lua have been accepted yet since they don't pass the unit tests.  In both cases they are really close.  Passing all the unit tests is required since we don't want to ship broken generators.  I'm hopeful that PHP will get included soon.  But I haven't heard fro the Lua developer in a year.

New (popular) languages are welcome, but Blockly does not deal with typed languages well.  C, Java, Arduino, etc all define variables with int, bool, or some other fixed type.  That's not something Blockly can easily handle.
