### ISSUE TITLE
Support for Objects, Classes and JSON.

### ISSUE THREAD

**Issue by Eisenspalter** [google/blockly#115]
Will Blockly support Objects, Classes or JSON in future?

**Comment by LunicLynx** [comment]
I started implementing basic oop support: #243

**Comment by Suhail-ahammed** [comment]
is this feature implemented?

**Comment by 4n70w4** [comment]
I would also like to.

**Comment by d3x0r** [comment]
I'm kinda surprised this isn't a thing; but maybe it's because of the wide targeted languages...

```
Language "JavaScript" does not know how to generate  code for block type "list_create".
```

was playing with some of the demos, and found one I could make a list - but then as seen, you can't actually make a list in JS... which is one of the simpler operations `["abc","abc",123,123]` done.  

Lists I sort of thought were a good start towards getting objects, or multi-field variables... other than being indexed only by number and not name.

I saw along the way that 'typed variables' have been added - but that's not really what this needs...

**Comment by ngomezcn** [comment]
Is this feature request planned to be added?

**Comment by rachel-fenichel** [comment]
We do not intend to add blocks for the creation of objects, classes, and json. These would vary too much by language for us to generalize them across our five basic languages (dart, javascript, python, php, lua).
