### ISSUE TITLE
Scrollbar appears on page when dropdown menu is open

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1242]
To recreate:
https://blockly-demo.appspot.com/static/demos/fixed/index.html

Click on any dropdown menu.  Scrollbar appears on page body.  This didn't used to happen.

This doesn't happen on the playground, but that's just because the playground is set with CSS to suppress all scrollbars.  However, many pages do require scrollbars, so that's not a solution.  Interestingly on the multi-playground the effect is greater on lower Blockly instances.

The currently published version of Blockly Games predates this bug and demonstrates the expected behaviour.

**Comment by rachel-fenichel** [comment]
Do you know what commit blockly was at last time you updated blockly games?

**Comment by NeilFraser** [comment]
Last push to Blockly Games was 29 Jun 2016.

**Comment by rachel-fenichel** [comment]
This looks like the relevant change: https://github.com/google/blockly/commit/927cabe992026a2bc3b6b3ac1b064b56b5d8d711#diff-6336396d4982b6d05b6bfa800b569248L150
```
 -  Blockly.WidgetDiv.DIV.style.height =
 -      (windowSize.height - anchorY + scrollOffset.y) + 'px';
 +  Blockly.WidgetDiv.DIV.style.height = windowSize.height + 'px';
```

**Comment by rachel-fenichel** [comment]
And here's the change that initially added the explicit widget div height.  I'm not sure why we're setting height and not width--it seems like we need neither or both, but that only one is a bug.

**Comment by rachel-fenichel** [comment]
@picklesrus and I did some digging today.  Here are our conclusions so far:
- the first child of the widget div has `position: absolute` on it
- this takes it out of the normal positioning flow and the parent doesn't learn about its height
- removing `position: absolute` from the relevant [line](https://github.com/google/blockly/blob/master/core/css.js#L692) in css.js and not setting the height in `WidgetDiv.position` gets rid of the scrollbars
- The above fix lets the widget div go outside the window in RTL, which it shouldn't do.

It should look like this:
![image](https://user-images.githubusercontent.com/13686399/29048287-a869bf18-7b84-11e7-971c-251c79ffdc63.png)
But instead it looks like this:
![image](https://user-images.githubusercontent.com/13686399/29048322-d279c47e-7b84-11e7-907b-863abff18adb.png)
- In LTR it still does the right thing (the widgetDiv is positioned so that it won't go out of the window).

Setting the height explicitly seems like the wrong way to solve the original problem (disappearing menus) but it's been in the code for a while.  @picklesrus and I suspect there's a simple bit of CSS that would solve our problem, but don't know what it is.

**Comment by picklesrus** [comment]
Yeah, what @rachel-fenichel tried by removing the position:absolute on child of the widget div (which is already absolutely positioned) seems right.  It seems like the rtl problems are from a few left: (e.g. https://github.com/google/blockly/blame/4dffad0dad22e6a5b2c568f5f703e8b6359f5a28/core/css.js#L699) that are on that widget div's child that probably don't work once the position:absolute is resolved. But I think there should be away around it.  I just don't know what it is yet :-/

**Comment by NeilFraser** [comment]
Also visible on backendless.com's "codeless" editor.

**Comment by rachel-fenichel** [comment]
Fixed!
