### ISSUE TITLE
FieldImage opt_click field broken

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#1263]
The Blockly FieldImage's optional click handler is broken in both develop and master.

Looks like this just got left behind. Fix is simple: 
https://github.com/Microsoft/pxt-blockly/commit/2a1b39c130a7faeff4ffb0614310e899acfb1548

**Comment by rachel-fenichel** [comment]
@microsoftsam in that commit you're making the arguments be
`src, width, height, opt_alt, opt_onClick, flip_rtl`

Note that a required argument like `flip_rtl` should not come after an optional argument like `opt_alt` or `opt_onClick`, and that to specify `opt_onClick` you are also required to specify `opt_alt`.  The latter is not something we've noted in the Blockly codebase.

I'll take a look and pull this fix in.

**Comment by rachel-fenichel** [comment]
Fixed by #1320

**Comment by picklesrus** [comment]
Re-opening because I don't think this quite fixed things.  ImageFields, by default, aren't editable and the gesture code code returns false in isFieldClick_ when fields aren't editable and then ignores the click.  Looks like the pxt branch solved this by adding this bit of code when the click callback is passed in: https://github.com/Microsoft/pxt-blockly/blob/2a1b39c130a7faeff4ffb0614310e899acfb1548/core/field_image.js#L59

Also see for more: https://groups.google.com/forum/#!topic/blockly/BZ7XNOtyx8o

**Comment by picklesrus** [comment]
I believe another user is about to hit this bug as well: https://groups.google.com/forum/#!topic/blockly/0WyP0khCIfA

**Comment by thejinx0r** [comment]
@picklesrus 
Thanks for the hint:
After setting a FieldImage to editable (`fieldImageInstance.EDITABLE=true;`),
callbacks are triggered on mouse down.

**Comment by samelhusseini** [comment]
Fields now use showEditor_ to hint whether or not they are clickable. 
Closing as this is no longer an issue.
