### ISSUE TITLE
domToWorkspace generated statement blocks get scrambled on Chrome

### ISSUE THREAD

**Issue by JC-Orozco** [google/blockly#1302]
While developing my BlocksIDE platform I noticed the next problem:
When I generate more than 10 separate statement blocks using Blockly.Xml.domToWorkspace they get scrambled in Chrome but not in Firefox, IE, Edge, Safari.
I set up an example as simple as possible to demonstrate this, It consists of a single html file derived from the "Fixed Blockly" demo, it uses Blockly as a node_module library:
https://github.com/JC-Orozco/blockly_simple
By the way I am also including a possible workaround to fix the problem as a commented out xml.

**Comment by picklesrus** [comment]
What do you mean by scrambled? 
I didn't download your code, but in the fixed blockly demo, I loaded your xml through the console and called workspace.cleanUp() and this is what I got:
![screen shot 2017-09-01 at 4 57 13 pm](https://user-images.githubusercontent.com/15675877/29991100-aaef65b0-8f36-11e7-8b60-61266d458346.png)

If the bug is that they aren't sorted by their numeric values or by the order they were in when you loaded them via xml or something else?  We can't really do much about the numeric part since a comparison function across different types of blocks doesn't make a whole lot of sense.  For the xml bit, your xml that sets the coordinates of the block is probably your best since the cleanup blocks function in the workspace doesn't have access to the original xml that was loaded or know whether the workspace has changed since the load happened.

**Comment by JC-Orozco** [comment]
The numeric value is just to visualize the order of the blocks in the xml. My problem is that the blocks do not get loaded in the same order that they appear in the xml. The curious thing is that Chrome is the only browser that I tested that did not get the statement blocks in order. The numeric blocks are just an example, but the same thing happens with a proper statement block list. In BlocksIDE when I am converting from javascript to blocks, to get a list of statements is in that case a common scenario. I am aware that this may not be a bug since all the blocks will be placed on top of each other before calling workspace.cleanUp(). On the other hand it would be desirable to get the same sequential order as in the xml.

**Comment by JC-Orozco** [comment]
A possible solution that will preserve the xml order of the top level statements and will result also on a consistent behavior among all browsers is to place each new top level xml statement that does not include an x or y attribute appended at the bottom of the existing blocks. Instead of assuming an origin position (0, 0). Unless this results in a unacceptably high performance penalty.

**Comment by RoboErikG** [comment]
The code generation is completely independent from the xml loading. When code generation runs on disconnected stacks it tries to order them from the highest stacks down, with a slight preference given to stacks that are further left.

Since you're importing multiple blocks without x/y positions, they all get placed at the same spot. When all the blocks are at the exact same location there's no implied order and it's going to depend on the browser's implementation for how it picks between equal values in ordering.

As Pickles suggested, you should add x/y positions to your blocks so that they have a deterministic order.

**Comment by JC-Orozco** [comment]
I agree. In any case I did want to submit this issue since it took me a while to figure out. Specially since it worked OK on most browsers. It can save someone time if they stumble upon a similar problem. Just for the record, the solution of adding x/y positions was suggested by me as a workaround on my original post.
