### ISSUE TITLE
Blockly into a "resizable" container

### ISSUE THREAD

**Issue by ldetomi** [google/blockly#1311]
Hi,
I put Blockly plugin into a DIV with `resize:horizontal` property but.... how to force resize at resize of this container?

Here a [DEMO](https://jsfiddle.net/ldetomi/5u4offh2/) that explain problem. Please, try to resize red-bordered container using bottom-right handle

**Comment by RoboErikG** [comment]
Take a look at the [resizeable Blockly guide](https://developers.google.com/blockly/guides/configure/web/resizable).

Also, please ask questions on the [mailing list](https://groups.google.com/forum/#!forum/blockly) instead of filing issues. You'll get a faster response and help us keep our issue tracker focused on issues.

**Comment by ldetomi** [comment]
Problem is that Blockly and Guide (that I read) manage resizability of browser window and not resizeability of DIV container. Infact if you resize container in my DEMO, you can see that Blockly canvas is not resized until you force a browser window ones...

In my opinion current implementation is very basic and often far from real usage
