### ISSUE TITLE
Race condition when loading messages

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1369]
These lines all trigger errors in Blockly Games when compiled:

https://github.com/google/blockly/blob/master/blocks/math.js#L507
https://github.com/google/blockly/blob/master/blocks/loops.js#L282
https://github.com/google/blockly/blob/master/blocks/loops.js#L286

The issue is that the properties on Blockly.Msg may not be loaded yet, and these dynamic tooltips are set to undefined.  The compiled test in Blockly does not suffer from this issue, presumably due to minor differences in the order files are loaded.

**Comment by RoboErikG** [comment]
I believe we started requiring messages be loaded before blocks for this reason and because the JSON references don't load correctly without them.

We updated all of the demos to include msg.js before the blocks files, but we've been unable to come up with a good solution to remove that requirement. Any ideas?

**Comment by NeilFraser** [comment]
If one has to load `msg/xx.js` before the blocks, then what is the purpose of the calls to `Blockly.utils.runAfterPageLoad`?  They have comments such as:
`// Wait for load, in case Blockly.Msg is not yet populated.`

Looking at this, it's actually a pretty poor solution since (as mentioned in those same comments) it only works in browsers and will fail in Node.

When dealing with compiled code, it's not as easy as including `msg/xx.js` before the blocks.  Order is dependant which files `require` which other files.  The blocks files do indirectly require `Blockly.Msg`, but the messages are actually defined on `Blockly.Msg.xx` and there's no way for the blocks files to require the right one.  At the moment it is random (though deterministic) whether messages or blocks are loaded first.

**Comment by NeilFraser** [comment]
Bending this issue to actionable items:

The three lines listed above should be changed from:
...Blockly.Msg.MATH_CHANGE_TOOLTIP, 'VAR'));
to:
...'%{BKY_MATH_CHANGE_TOOLTIP}', 'VAR'));

Furthermore, Blockly.utils.replaceMessageReferences needs to not truncate a string that has a %1.

**Comment by RoboErikG** [comment]
And to followup, to fix replaceMessageReferences we need to split out its behavior from the tokenization of messages. Right now, interpolate is doing both and when it hits a message reference with a %1 it tries to tokenize it and loses everything after the first token.

**Comment by AnmAtAnm** [comment]
The real issue was an incorrect call in recursion, calling the public `tokenizeInterpolation(..)` instead of the private `tokenizeInterpolation_(..)` that could receive the `parseInterpolationTokens` flag.

The FSM is the right solution for the message reference replacement, because regex do not handle `%` escaping well: `%{MSG_REF}`, `%%{NOT_A_REF}`, `%%%{MSG_REF}`, ...
