### ISSUE TITLE
Delete areas broken in RTL Mutators on FF

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1425]
Demo:
https://www.youtube.com/watch?v=DIdfREakzpg

Try here:
https://blockly-demo.appspot.com/static/demos/rtl/index.html

**Comment by picklesrus** [comment]
I'm currently suspicious that using getBoundingClientRect we use to calculate the delete area is doing the wrong thing in firefox, rtl, in the mutator.  Firefox devtools thinks that flyout is not where it is rendered... See screenshot of the blue, highlighted area that firefox tells us the flyout is vs where it is actually rendered :(  Not sure what to do about this yet. Still digging.

![screen shot 2017-11-07 at 2 21 32 pm](https://user-images.githubusercontent.com/15675877/32521291-cd4c0dfa-c3c7-11e7-8c12-d5f2de7c22ed.png)

**Comment by picklesrus** [comment]
I'm a bit stuck on how to work around this.

I've seen a bunch of references to firefox bugs about how getBoundingClientRect doesn't take into account css transforms on svgs, but we're just using the regular transform attribute.  

getBoundingClientRect of the workspace of the mutator appears to be correct - I suppose because it doesn't have a transform attribute on it?  I can use that as the base instead and then do some math to calculate the offset of the flyout.  But, none of that pays attention to scale so it breaks on zoom.  The mutator workspace doesn't have a scale (it zooms based on the main workspace's zoom level/scale) so I'd have to reach out to grab that and do some more math.

**Comment by rachel-fenichel** [comment]
I did a bisect to find when this broke.  It was [this change](https://github.com/rachel-fenichel/blockly/commit/a0e6d4bbb58412ec9a32d38bfad5fbcf3b40ec12).

But that's just the change that made us not connect to blocks under the flyout.  The actual problem with the flyout seeming to be in the wrong place probably crept in separately, and was exposed by that change.

Also, that means it's been broken for a year :/

**Comment by NeilFraser** [comment]
It's definitely this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1066435

**Comment by NeilFraser** [comment]
@picklesrus Why is the root element of a mutator's flyout a 'g', whereas the root element of a main workspace's flyout is an 'svg'?  Let's look at this on Monday.

**Comment by picklesrus** [comment]
At some point we figured out this was likely introduced by @rachel-fenichel's change involving deleting blocks that are under the toolbox.  Next step would be to go find that change and verify.

**Comment by rachel-fenichel** [comment]
The change that exposed the problem is https://github.com/rachel-fenichel/blockly/commit/a0e6d4bbb58412ec9a32d38bfad5fbcf3b40ec12

From above: 
> But that's just the change that made us not connect to blocks under the flyout. The actual problem with the flyout seeming to be in the wrong place probably crept in separately, and was exposed by that change.

Last time we discussed this I suggested just making it so that we prefer connectingover deleting in a mutator.  But Neil pointed out that this would not allow a user to reorder their inputs/clauses, since all disconnected blocks would be deleted immediately.

**Comment by rachel-fenichel** [comment]
#1774 works around this but does not fix the underlying problems.  It uses a different way to calculate the delete area, for use when we know that the browser might get it wrong (firefox, rtl, mutator).  

A real fix would involve making the mutator workspace's flyout be an `<svg>` instead of a `<g>`, which would consolidate code paths.
