### ISSUE TITLE
During horizontal window resize in RTL, scrollbar floats out of flyout bounds 

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1445]
### Problem statement

Flyout scrollbar should be attached to flyout edge during window resize, but it isn't. RTL only, toolbox at end. See animated gif attached.
- [x] Bug report
- [ ] Feature request

### Steps to Reproduce
1. Open simple flyout in rtl. (e.g. https://blockly-demo.appspot.com/static/tests/playground.html?dir=rtl&toolbox=simple&side=start)
2. shrink the window vertically so that the flyout has a scrollbar
3. shrink the window horizontally.
4. Notice the scrollbar doesn't stay pinned to the edge of the flyout.

![2b17dc51-e51a-4f0d-9c49-592a5f99f921](https://user-images.githubusercontent.com/15675877/32806995-573c5666-c943-11e7-8a10-832b88460ed4.gif)

### Operating System and Browser

_Remove this hint: these checkboxes can be checked like this: [x]_

- [x] Desktop:
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):

**Comment by BeksOmega** [comment]
I think this is related to right-anchored flyouts rather than RTL flyouts. (Observe RTL vertical start & LTR vertical end)
![scrollbarwindowresize](https://user-images.githubusercontent.com/25440652/52448868-200dcd00-2aea-11e9-8bb9-91dcd75f7a37.gif)

**Comment by BeksOmega** [comment]
This behavior also occures with bottom horizontal toolboxes.

Bottom LTR:
![scrollbarmovement_horizontal_playgrond_bottom_ltr](https://user-images.githubusercontent.com/25440652/52523545-84926e80-2c47-11e9-9601-da6f2fa63125.gif)

Bottom RTL:
![scrollbarmovement_horizontal_playgrond_bottom_rtl](https://user-images.githubusercontent.com/25440652/52523547-8c521300-2c47-11e9-8a15-968975f36698.gif)

It does not occure with top toolboxes:
![scrollbarmovement_horizontal_playgrond_top_ltr](https://user-images.githubusercontent.com/25440652/52523595-983dd500-2c47-11e9-8472-8529e09dee56.gif)

It is also not replicatable on the multiplayground (I assume because the workspaces don't actually resized vertically).
![scrollbarmovement_horizontal_multiplayground](https://user-images.githubusercontent.com/25440652/52523606-b277b300-2c47-11e9-9d64-52e4642803f1.gif)

**Comment by samelhusseini** [comment]
Fixed by #2281
