### ISSUE TITLE
Trash can slowly moves out of the screen

### ISSUE THREAD

**Issue by msprotz** [google/blockly#146]
Hi Neil,

Here's a couple issues we've noticed with our usage of Blockly. The first one is as follows. I put up a minimal testcase at http://jonathan.protzenko.free.fr/t/editor.html

Happens on Firefox and Chrome, does not happen on IE.

STR:
- load the page
- click repeatedly on the workspace background
- observe the trash can being dragged out of the screen

Sorry about the terse bug report -- let me know if you need extra information.

Thanks,

Jonathan

**Comment by NeilFraser** [comment]
It is not the trash can, it is the Blockly SVG that is slowly growing vertically by a pixel or two every time it renders.  With work, this could be solved, but then you'd run into an unsolvable problem: if the window were resized smaller, then the editor div would not be able to shrink since it has a large editor inside it.

The instructions here show how to robustly fill (actually cover) an area without affecting its size:
https://developers.google.com/blockly/installation/injecting-resizable

**Comment by msprotz** [comment]
Indeed, following the instructions on the page solved it. Agreed about the shrinking issue.

**Comment by jano42** [comment]
I worked on this issue, and finally identify it as a bad css behavior.


It seems that a simple css fix solve it.

```````css
.blocklySvg {
    display: block;
}
```````
