### ISSUE TITLE
Undeletable blocks have delete icon when dragged over category toolbox

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1487]
Go to playground and import this XML:
```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block deletable="false" type="controls_if"></block>
</xml>
```
Drag the block over the toolbox.  Icon shows delete cross.  Expect to see the normal dragging hand instead.

This is a regression within the past year (Blockly Games does not do this).

**Comment by rachel-fenichel** [comment]
Whoops.  BlockDragger.dragBlock checks if the event is in a delete area, but doesn't check if the block is deletable.

The fix is probably right [here](https://github.com/google/blockly/blob/develop/core/block_dragger.js#L191).  After the call to `this.workspace_.isDeleteArea(e)` add 

```
if (!this.draggingBlock_.isDeletable()) {
  this.deleteArea_ = Blockly.DELETE_AREA_NONE;
}
```

Though we probably need to check all of the descendants as well.

**Comment by rachel-fenichel** [comment]
Never mind, that was the wrong fix anyway.  Dragged connection manager already checks whether the block is deletable.  So this is just a problem with the cursor.  I'll sort it out and send a PR.

```
  var wouldDelete = !!deleteArea && !this.topBlock_.getParent() &&
      this.topBlock_.isDeletable();
  this.wouldDeleteBlock_ = wouldDelete && !wouldConnect;

  // Get rid of highlighting so we don't sent mixed messages.
  if (wouldDelete && this.closestConnection_) {
    this.closestConnection_.unhighlight();
    this.closestConnection_ = null;
  }
```

**Comment by picklesrus** [comment]
Discussed with @rachel-fenichel. Will try and fix by adding a class analogous to  blocklyToolboxDelete, except with the grabby hand instead.
