### ISSUE TITLE
Add default type option to variable fields

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1499]
Variable fields have a default name option in JSON but no default type.  As a result, an unset variable field creates a variable with the default name but the `''` type.  This can be a problem if the field doesn't accept the `''` type.

**Comment by NAllred91** [comment]
Do you think that the default name option should only be used if there is no variable that exists with a type that is in the `variableTypes` array?  If a variable does exist with a type that is in the `variableTypes` array then use that variable as the default.

Otherwise, every time you drag one of these blocks into the workspace a new variable is created with the default variable name.
