### ISSUE TITLE
How does a developer say what variable types are allowed in a workspace?

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1513]
Variable map's `getVariableTypes` returns all of the types that have been used in the workspace so far.
https://github.com/google/blockly/blob/master/core/variable_map.js#L225

Variable fields now use `getVariableTypes` to decide which variables to show in the dropdown (if the field doesn't explicitly specify).  But that only shows types that have already been used--and it doesn't remove a type if the last use of it has been deleted.  So that feels wrong in two ways.

Does a developer need to explicitly register every variable type they might care about?  Or does it happen when defining the blocks, or the buttons?

**Comment by RoboErikG** [comment]
My 2¢, I think we do want to move to listing the allowed variable types as the standard use case. I don't think that's incompatible with the current behavior, either.

This is also related to #1455 and https://github.com/google/blockly/issues/446

**Comment by picklesrus** [comment]
I think we need to think through the implications of what happens when the list doesn't match what a developer gives us through other channels:
 e.g. if I load xml to the workspace with a variable type that isn't in the allowed types, what do we do? Warn? Ignore? Nothing?  If we do have to write code to check for inconsistencies, we should consider whether that is that actually easier than just building up the list ourselves.

**Comment by maribethb** [comment]
Now out of scope due to the implementation of typed variables.
