### ISSUE TITLE
Is it possible to have multiple outputs for Blockly?

### ISSUE THREAD

**Issue by Ericxgao** [google/blockly#1524]
As the title says - I am trying to integrate Blockly with an existing set of functions from a library, some of these functions provide multiple outputs and I was wondering if there was a way for me to have Blockly provide multiple outputs as well.

**Comment by NeilFraser** [comment]
In terms of the block structure, every block has zero or one parent.  It's a tree.  So in that sense, no.

In terms of the language, you could return a list, array, tuple, or other data structure containing multiple output values.  Blocks could also set multiple variables.  So in that sense, yes.

It would be better to ask this sort of question on the newsgroup, rather than filing a bug.  More people would see it and give creative solutions.
