### ISSUE TITLE
Proposal - Block.setDisabled() to Block.setEnabled()

### ISSUE THREAD

**Issue by sooonism** [google/blockly#1593]
I would like to suggest that change the `Block.setDisabled()` to `Block.setEnabled()`, make it much more readable.

It is always better to make it straight forward that having a double negative scenario, which, `Block.setDisabled(false)` is one of them. I literally have to stop my coding and study carefully how this line affect my logic.

By changing to `Block.setEnabled(true)`, I can straight away know what will happen and move on with my coding.

**Comment by RoboErikG** [comment]
This is a good suggestion. Because it's an existing API that's been around for a while we'd actually need to add setEnabled as a new method, deprecate setDisabled, and have setDisabled invert and call through to setEnabled though, which might make things kind of messy.

I think we'd have to discuss a little bit on our side if we want to make that change.

**Comment by AnmAtAnm** [comment]
If implemented, this should be mirrored on iOS and Android.

**Comment by rachel-fenichel** [comment]
@sooonism we're open to a pull request for this.  As @RoboErikG mentioned, we would want to deprecate but not delete `Block.setDisabled()`

**Comment by NeilFraser** [comment]
Followup: setDisabled was later deleted here: https://github.com/google/blockly/pull/4330
