### ISSUE TITLE
Tracking issue for pointer events

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1655]
Enabling pointer events is simple:  Enable the commented-out code in `touch.js`.
```
// if (window.PointerEvent) {
//   Blockly.Touch.TOUCH_MAP = {
//     'mousedown': ['pointerdown'],
//     'mousemove': ['pointermove'],
//     'mouseup': ['pointerup', 'pointercancel']
//   };
// } else
if (goog.events.BrowserFeature.TOUCH_ENABLED) {
  Blockly.Touch.TOUCH_MAP = {
    'mousedown': ['touchstart'],
    'mousemove': ['touchmove'],
    'mouseup': ['touchend', 'touchcancel']
  };
}
```

This causes a variety of subtle bugs.
- Can't edit a comment after moving it or the workspace it's on
- Double event handling in iframes (handle both mouse and pointer events on a click)
- Mouse click-and-hold is treated as a longpress on the workspace, triggering the workspace context menu.

I disabled pointer events in the feb 2018 release, pending fixes for these issues.

In theory pointer events should fully replace mouse events on any platform where they are supported.

**Comment by samelhusseini** [comment]
Regarding the double event firing on iframes, we know the source of that issue, and PR https://github.com/google/blockly/pull/1615 fixes that issue. 

Regarding click and hold, I have a fix for that. Issue is we were assuming pointer events are touch events but they're not necessarily, so we need to check before we call longStart that the pointerType is not 'mouse'. I'll get a PR out for that. 

Comments: 
- using mouseup for to focus the text field (has definitely regressed, seeing the same issue here, investigating).
- there's another issue, perhaps unrelated but I'm not able to focus or type on a comment field on IOS.

**Comment by samelhusseini** [comment]
Changing the event to mousedown fixes both issues. I believe the issue here is perhaps related to the TODO in gesture.js (doBubbleClick_). 

The issue is that there's an overarching pointer event listener that's the workspace gesture.js (recognizer) that's listening to clicks / drags and classifying them. The recognizer discards any event that was meant for an input field (textarea, input, etc). so when we click on the textarea, it discards the event but in the process of doing that it's eating up the event that could have been passed to the input element itself. 

Reason why this worked, the mouseup event wasn't getting triggered at all actually, it's the browser that was focusing the textarea field in the bubble, which means bubble promotion wasn't happening when a user clicks on the comment field. (You can try this in blockly/master)

It seems the best fix for me is to change the event handler to mousedown instead of mouseup. 

One thing I still can't explain is why the mouseevent propagates to the textarea but the pointer event doesn't..

**Comment by samelhusseini** [comment]
Alright. I figured it out!!

These was a bug after all, we were treating pointer events the same as touch events (which work hand in hand with mouseevents and are not a replacement), namely we were preventing default on pointer events which meant that the overarching gesture event handler ate up events aimed at the textarea.

The issue with the comments was also another case of us preventing the event from propagating when we want the browser to handle all the interactions with the text area.

I'll prepare a PR with all the fixes.
