### ISSUE TITLE
Discussion: Possible values of Blockly.selected

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1667]
As of Feb 2018, `Blockly.selected` can only be the currently selected **block**.

With the workspace comments we set `Blockly.selected` to be the currently focused/selected comment.  By extension it should be possible to select a block comment or warning, and possibly even the flyout or toolbox category.  When moving within a block, there could be a selected field or connection.

For accessibility and keyboard navigation we probably want some concept of "selected" that encompasses all of these things.

Questions:
- Would overloading `Blockly.selected` in this way cause problems?  e.g. if someone's code assumes that if `Blockly.selected` is set, it's a `Blockly.Block`.
- @quachtina96 do you have thoughts on accessibility?
- How does this play into keyboard navigation?
- Is it worth keeping track of a selected block separately from anything else that might be selected?
- Are there categories of selectable things?  e.g. blocks, block comments and workspace comments are mutually exclusive, but a textarea within a block or a comment may be selected at the same time as that block or comment.
- How does this interact with events?

**Comment by samelhusseini** [comment]
For selection, I would say that Blockly's selection handling should be separate from the toolbox. As it's not a requirement to use Blockly's toolbox, as developers can implement their own custom toolbox.

I'm not sure if there's some other meaning for selection, but my understanding of selection is that there's a visual indicator in Blockly (not in scratch-blocks), when a block is selected. It's the last Block that a user clicked on. Perhaps in the future it would be the block that would move if you were to use the arrow keys (for accessibility). So with that assumption in mind, I'd say that selecting a block is no different to any other entity that can be moved around with arrow keys on the workspace. (ie: any other entity that lives on the workspace). That includes both workspace and block comments.

As an extension of that, the selected visual indicator is an indicator that the Block can be moved. (and I just checked, and we don't show a selected indicator for read only, so that's in alignment with my reasoning).

Perhaps down the line, all selectable objects (blocks, comments, warnings) should extend from one abstract class, and that is the type of Blockly.selected.

**Comment by 0199prabha** [comment]
I want help with my blockly code. how to remove all dragged blocks by clicking the reset button. my code only removes the child block.
Here's my code:
function reset() {
  if (Blockly.selected && !Blockly.selected.workspace.isFlyout) {
    Blockly.Events.setGroup(true);
    Blockly.hideChaff();
    Blockly.selected.dispose(false);
    Blockly.Events.setGroup(false);
}
  delete inputTextValue;
  redrawUi();
}

I also wanted to delete the parent block as well. Please help me with this problem.

**Comment by alschmiedt** [comment]
Hello!

The code you currently have will delete all blocks below the currently selected block. If you want to remove any parents of the block you could use the following code: 
```
Blockly.selected.getRootBlock().dispose(false)
```
This will get the first block in the stack and then call dispose on it. 

If you have any more questions, please use the [forum](https://groups.google.com/g/blockly?pli=1) to ask them. We like to keep all questions in one place and this will help us keep our issues decluttered.

Thanks!

**Comment by maribethb** [comment]
Closing for now. The context behind asking these questions is lost and there is no obvious need to do anything here. Current status is that Blockly.selected returns items that implement ICopyable (blocks, workspace comments, etc.)
