### ISSUE TITLE
Fix coordinates

### ISSUE THREAD

**Issue by Maluma1** [google/blockly#170]
It might be useful to add a few lines at the end of the Blockly.convertCoordinates function to adjust the coordinates of the mouse when using the zoom attribute:

    Blockly.convertCoordinates = function(x, y, toSvg) {
    ...
    xy.x=xy.x/$("body").css("zoom");
    xy.y=xy.y/$("body").css("zoom");
    return xy;
    };

Sorry for my bad English

**Comment by NeilFraser** [comment]
Since Blockly does not use jQuery, this should be:
```javascript
xy.x /= document.body.style.zoom;
xy.y /= document.body.style.zoom;
```
However, if there is no CSS zoom property set, then xy becomes Infinity.  So you need to wrap this in a check:
```javascript
if (document.body.style.zoom) {
  xy.x /= document.body.style.zoom;
  xy.y /= document.body.style.zoom;
}
```

However, body is just one place where CSS zoom can be added.  So you really need to spider up the DOM tree looking for zoom settings on every element between the SVG and the body.

But more importantly, you are apparently using a very old version of Blockly.  We have no `convertCoordinates` function any more.  Try syncing to the latest version.
