### ISSUE TITLE
Blockly.utils.getScale_.REGEXP_ is misdeclared

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1702]
[Declared](https://github.com/google/blockly/blob/master/core/utils.js#L263) as `Blockly.utils.getScale_REGEXP_`.
[Used](https://github.com/google/blockly/blob/master/core/utils.js#L236) as `Blockly.utils.getScale_.REGEXP_`.

It's unclear how or if this is working.  If it's not working and never has been, we should delete the property and its use.

**Comment by AnmAtAnm** [comment]
`Blockly.utils.getScale_()` is only called by `Blockly.utils.getInjectionDivXY_()`, which is only called by `WorkspaceSvg.getOriginOffsetInPixels()` and `Scrollbar.onMouseDownBar_()`.  For everything I've tried (zoom browser, scroll page, pan/zoom workspace), `getScale_()` always returns `1`.

Looking deeper, it looks like it is looking for SVG attribute `transform`. Scrollbars use CSS style transforms instead of SVG transform attributes. `getOriginOffsetInPixels()` is called at the beginning of a drag from the toolbox, and it uses the `transform` attribute. However, the `.match(undefined)` never errors and no scale is accumulated. Thus, the `setScale()` is always `1`. The scale must be accounted for elsewhere.

**Comment by AnmAtAnm** [comment]
@picklesrus I can gut `setScale_()` under the assumption everything is working without it, or I can hand it back to you to refactor it into what you think it should be doing. Let me know.
