### ISSUE TITLE
[Edge, IE] Zoom control mouseover is not clipped

### ISSUE THREAD

**Issue by carlosperate** [google/blockly#172]
Tested on IE11 on Windows 8.1 64bit, related to https://github.com/google/blockly/pull/165.

IE draws the zoom controls correctly (the `clippath` does crop the image to display only the expected icons), however the mouseover is activated as soon as the `image` area is reached, ignoring the `clippath`.

**Comment by rachel-fenichel** [comment]
Recent testing shows that this is still a problem.

**Comment by rachel-fenichel** [comment]
Triaged today.  This is still a bug, but low priority: it affects usability, but does not break functionality all the way.  

Help wanted: we're happy to take a pull request for this, or even just have somebody dig into it more and explain exactly what's going on.

This matters because clicks on the zoom controls don't always do the right thing, even though the controls are drawn correctly.

**Comment by AnmAtAnm** [comment]
As noted in #2031, this also affects Edge.

**Comment by mehdi-yeganeh** [comment]
@rachel-fenichel The best way i found for solving this problem is adding svg element as holder of each zoom control buttons ( image elements). I fixed it and create a pull request.

![image](https://user-images.githubusercontent.com/78925/49686299-c13ad000-fb07-11e8-8a8e-ec909d29de9b.png)
