### ISSUE TITLE
Document how to replace the mutator UI

### ISSUE THREAD

**Issue by Marclev78** [google/blockly#1747]
The documentation for "web" at https://developers.google.com/blockly/guides/create-custom-blocks/web/mutators#custom_editor_uis says:

```If your app uses a custom mutator UI...```

The implication being it is possible to define a custom mutator UI. However there seems to be no documentation for how to actually go about doing this.

Are there any examples for defining custom mutator UI's?

In my case I want to simply have a list of checkboxes instead of the toolbar / work-space style default editor UI.

**Comment by picklesrus** [comment]
You're probably better off asking this question over on the mailing list to see if any other Blockly users have implemented different UIs for mutators.  https://groups.google.com/forum/#!members/blockly
There are at least some discussions over there about using +/- buttons instead of the mutator bubble. e.g. https://groups.google.com/forum/#!searchin/blockly/mutator$20ui%7Csort:date/blockly/b6T24i__C9Y/OAqtaqynBQAJ

In terms of replacing the existing one, I *think* you should just be able to overwrite the existing code for mutator.js.  CreateEditor looks like the interesting function: https://github.com/google/blockly/blob/master/core/mutator.js#L120  But again, the mailing list might get you more folks who have actually tried it.

I'm going to repurpose this issue as a request for documentation for replacing the mutator ui. Stay tuned.

**Comment by alschmiedt** [comment]
@rachel-fenichel Is this covered by the +/- mutator? Or is there a plan to add a code lab or more documentation for this?

**Comment by moniika** [comment]
If we opt for the sample is sufficient documentation, I think we could also add a reference to the sample in developer documentation so its easier to find.

**Comment by rachel-fenichel** [comment]
I added a reference [here](https://developers.google.com/blockly/guides/create-custom-blocks/extensions).

A codelab may eventually be a good idea--I created a bug to track it: https://github.com/google/blockly-samples/issues/304

I think our documentation on mutators has improved quite a bit since this bug was filed, so I'm closing it.
