### ISSUE TITLE
npm package name

### ISSUE THREAD

**Issue by kumavis** [google/blockly#177]
Glad to see this project is alive and well.
Along time ago I published blockly on npm as `blockly` before you were self-publishing.
I haven't kept it up, its not actively required by anything, and is likely causing more damage than good.
I'm unpublishing as `blockly` and your are free to use it.

keep up the good work!

**Comment by trodi** [comment]
Since blockly doesn't use semantic versioning (see issue #4), how would the npm package version be determined? I'm interested in seeing a good solution to this as it could be applied to a number of situations (npm, web jars, [typescript d.ts files](https://github.com/trodi/blockly-d.ts)).

**Comment by kumavis** [comment]
1) semver is how npm works
2) participating in npm will increase adoption of library
3) you can conform to semver *and* never release a breaking change

**Comment by trodi** [comment]
@kumavis , you are completely correct and I agree with your 3 bullets. The package could always be 1.minor.patch, where only the minor and patch versions get updated. That wasn't my concern; what I was wondering was:
* Does the version up every time blockly does (which is often daily or even more frequently)?
* How do you make sure all references to the semver version number are pointing to the same version of blockly?
  * Publishing to [npm](npmjs.com) is great, but you could easily suggest publishing to [bower](http://bower.io/), [webjars](http://www.webjars.org/), and [Definitely Typed](http://definitelytyped.org/tsd/) etc.

This would be solved if Blockly self published to at least one of these package managers or switched to a semver version number. Either would definitively define a version number. This number could be used by anyone else to publish similar packages on different managers etc. Since it seems unlikely that either of these solutions will happen, what's the best alternative?

If you drew a line in the sand for a starting 1.0.0 commit, an automated service could update the npm package and up the patch version for every commit. Then anyone else could follow the same pattern, though this doesn't account for upping the minor version.

**Comment by carlosperate** [comment]
related to this conversation: https://github.com/google/blockly/pull/136

**Comment by samelhusseini** [comment]
Hey @kumavis. We are working towards publishing ``blockly`` to ``npm``. I've been trying to reach the owner of the npm package, but my emails have all come back as unreachable. 

If that's you, please let me know the best way to reach you so we can transfer the package over for us so that we can begin publishing regularly to ``npm``.

**Comment by samelhusseini** [comment]
We are now officially publishing releases to npm: https://www.npmjs.com/package/blockly
