### ISSUE TITLE
Block colour is broken in graph demo

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1790]
blockly/demos/graph/index.html

No warnings, no deprecation notice, just some black blocks.  Fixing the graph demo is probably trivial if one knows what just changed, but what about anyone else who was doing something similar?

Works in production.

**Comment by AnmAtAnm** [comment]
The removed constants have been marked deprecated for over a year.

The demo has avoided a warning message because it uses a JavaScript objects (with the constant reference) as JSON objects. The `colour` attribute is thus undefined and `setColour()` does not get called.

#1795 adds a new warning when the JSON object has a `colour` key but no value.  However, since this is only run at block creation, its value is questionable. A user will have to load such a block, and thus see the black block, to get the console warning. At least the warning highlights the nature of the problem at that point (see black block, open console, know the `colour` value is undefined, and search for the constant to find it missing).
