### ISSUE TITLE
RTL mutators broken on Edge and IE11

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1806]
### Problem statement
RTL mutators are broken in Edge and IE11, on both master and rc/april_2018.

The mutator's flyout is on the left side instead of the right.  The block in the mutator workspace is where it should be.  Blocks being dragged out of the flyout appear to the right of the cursor.

### Expected Behavior

RTL mutator flyout behaves the same in all browsers.

### Operating System and Browser

* Windows Internet Explorer 11
* Windows Edge

### Additional Information

Since this is already on master, I'm not going to let it block this release.  But it is important, and hopefully a simple fix.

**Comment by rachel-fenichel** [comment]
@timdawborn @samelhusseini Have you been running into this?  If so, do you know how long it's been here?

**Comment by samelhusseini** [comment]
Yep looks to have been broken for a while.  https://makecode.microbit.org/?lang=ar (is running a ~ 4 month old blockly) and it repro's there.

Issue is CSS transforms on SVG (inner) elements are not supported in IE and Edge.
I've scanned the codebase and https://github.com/google/blockly/blob/master/core/flyout_base.js#L375 (when the tagname is a <g>) is the only instance where Blockly.utils.setCssTransform is used on an SVG <g> element. All other instances apply this on the SVG <svg> element and that's okay AFAIK. 

The fix is to use the transform attribute on the element itself when the flyout is using the <g> tag.
