### ISSUE TITLE
Performance and cost of filtering events

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1891]
### Problem statement

The filter function in `Blockly.Events` combines related events (e.g. two moves of the same block) and removes events that do not need to be sent over the wire for simultaneous editing.  Events that are filtered out are never fired.

The goal is to reduce the number of events that needs to be sent over the wire, especially in cases when the two users were disconnected for long enough to build up a large queue.

This may be unnecessarily expensive when most of the events are not duplicates or when doing forseeably large batch operations, such as swapping sprites in Scratch.  We have previously improved the behaviour of the filter function to make it much faster, but 

The filter used to combine all move events without considering intervening events.  This can be a problem if the intermediate events relied on the move (e.g. connecting over a shadow block and then disconnecting).  This shows as a breakdown in undo/redo, but not in triggering action.

### Possible solutions
- Disable filtering entirely
- Allow the developer to enable or disable filtering
  - A developer who wants to send things over the wire or have heavyweight listeners would want filtering on
  - A developer with lightweight listeners and lots of batch actions might want filtering off

### To explore
- For some basic workflows, what percent of events are actually filtered out?
  - Load workspace
  - Clear workspace
- Are the current rules correct about which events get merged?

### Test code
To disable filtering, replace the first few lines of `Blockly.Events.fireNow_`.  Delete
```
  var queue = Blockly.Events.filter(Blockly.Events.FIRE_QUEUE_, true);
  Blockly.Events.FIRE_QUEUE_.length = 0;
```

and replace with

```
  var queue = Blockly.Events.FIRE_QUEUE_;
  Blockly.Events.FIRE_QUEUE_ = [];
```

**Comment by rachel-fenichel** [comment]
@kchadha @gnarf @ewpatton This may be relevant for you.  Please let me know your thoughts, or any benchmarking you can provide for event filtering in your projects.

**Comment by cpcallen** [comment]
The title of this issue is "Performance and cost of filtering events", but the major performance issue had already been dealt with in #1205.  It appears that the matters raised in this issue that were actually live at the time are

> The filter used to combine all move events without considering intervening events. This can be a problem if the intermediate events relied on the move (e.g. connecting over a shadow block and then disconnecting). This shows as a breakdown in undo/redo, but not in triggering action.

and 

> * For some basic workflows, what percent of events are actually filtered out?
> * Are the current rules correct about which events get merged?

Problems with non-sequential `BlockMove` events were mostly eliminated in PR #1892 and the changes made to `filter` in PR #8539 have eliminated any possibility of events being reordered during filtering, and ensure that filtering is strictly liner-time.  During investigations of filter behaviour, I observed that:

* Quite a lot of `ViewportChange` events get merged when zooming/scrolling.
* A few `BlockMove` events get merged—most notably, when stap-to-grid is enabled, bump moves are usually combined with the preceding non-bump move.
* Very few other events are merged (but changes to how `BlockChange` events are generated as proposed in #1717 could change that).
* There were no notable instances of events being dropped, though I was not looking for this specifically.
* There is specific code in `filter` to unconditionally drop `Click` events that immediate follow a `BubbleOpen` event, but I did not observe this actually occurring: I believe other changes in the meantime result in the `Click` event not being fired in the first place in this situation.

The usefulness of filtering could be investigated further: it certainly does not appear to have a substantial effect on the number of events dispatched.  Given that I now have much higher confidence in the _correctness_ of `fliter` behaviour, however, I do not regard there to be a pressing reason to eliminate filtering altogether.

I therefore propose that we close this issue as completed.  @rachel-fenichel: Your views?
