### ISSUE TITLE
Generate code for single block in stack only?

### ISSUE THREAD

**Issue by Marclev78** [google/blockly#2067]
### Problem statement

I have a stack of blocks, but I only want to generate code for a single block in that stack. Blockly however appends the generated code of subsequent blocks to the one I call 
Blockly.JavaScript.blockToCode() for.

The only workaround I've found is to detach child blocks, generate the code for the block I actually want, and then reattach them. Is there an easier way to do this?

### Expected Behavior

I would like some way of getting `Blockly.JavaScript.blockToCode(block)` not to call the generators of all subsequent blocks in the same stack as the one I want to generate.

### Actual Behavior

All child block code is generated and automatically attached to the block's code that I'm interested in. This causes me all sorts of issues as in on my use case I only want the code for that very specific block even though it has multiple child blocks in its stack.

**Comment by rachel-fenichel** [comment]
For your use case does a single block include its children (not next blocks)?

![image](https://user-images.githubusercontent.com/13686399/46041619-126e2280-c0c8-11e8-89c2-a4963b547be7.png)

In this example, would generating code for the for loop block include all of the blocks in box B and exclude all of the blocks in boxes A and C?

**Comment by Marclev78** [comment]
Yes, so in the example I would want to get all the generated code for [B] (including any the `in list` it encloses) but not have the generator automatically  generate and append the code for [C] to it.

My actual use case is letting my user step through a stack of blocks one by one, so I want to generate and evaluate each block individually.

**Comment by ewpatton** [comment]
We have a feature for doing this in App Inventor. I think it should be relatively trivial to back port.

**Comment by rachel-fenichel** [comment]
@ewpatton we'd be interested in getting that backported.  It seems straightforward, and doesn't break old APIs.

**Comment by ewpatton** [comment]
@rachel-fenichel The feature is accessed through two menu items [`Generate YAIL`](https://github.com/mit-cml/appinventor-sources/blob/7e13229bb3d7c815fe4e347a3d1054e18d40261c/appinventor/blocklyeditor/src/blocklyeditor.js#L54) (admin only) and [`Do It`](https://github.com/mit-cml/appinventor-sources/blob/7e13229bb3d7c815fe4e347a3d1054e18d40261c/appinventor/blocklyeditor/src/blocklyeditor.js#L70) (sends to phone REPL). This relies on a function called [`blockToCode1`](https://github.com/mit-cml/appinventor-sources/blob/7e13229bb3d7c815fe4e347a3d1054e18d40261c/appinventor/blocklyeditor/src/generators/yail.js#L619) in the YAIL generator, which basically is like `blockToCode` except it passes an additional argument to `scrub_` that turns off concatenating the `nextConnection` block.

To back port, I think it might make sense to add the optional `opt_thisOnly` argument to `blockToCode` and `scrub_` so that we can collapse the two code paths. In the case of providing a menu option, one might also need a method to tell the system which language to generate. We don't have this coded since we only have one target language.
