### ISSUE TITLE
FieldDropdown.validateOptions_ bug

### ISSUE THREAD

**Issue by duzc2** [google/blockly#2090]
### Problem statement
![a](https://user-images.githubusercontent.com/564778/47565893-8a946600-d95c-11e8-989c-1ce93109749f.png)

**Comment by rachel-fenichel** [comment]
Next steps:
- use `tuple` instead of `options`, to validate the correct object
- add a passing test for the case where `tuple` is an array and a failing test for the case when `tuple` is anything else

The current code is too permissive, which probably leads to later bugs.

@duzc2 feel free to make a pull request for this one.

**Comment by RoboErikG** [comment]
Underlying bug has been fixed but this could still use a field_dropdown_test.js file in the [jsunit folder](https://github.com/google/blockly/tree/master/tests/jsunit) before we close out the bug.
