### ISSUE TITLE
Debug and reenable macOS CI on GitHub Actions

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2114]
Generator tests require firefox instead of chrome, but our current setup has issues with geckodriver on osx.  Low priority because we do regularly build on osx, and because ubuntu tests are running.

**Comment by cpcallen** [comment]
Working on this in PR #4903.  Looks like the generator tests are fine on macOS, but mocha tests are failing in CI (not locally).

**Comment by cpcallen** [comment]
I looked at this a bit but I am unable to figure out what is going wrong.  Comparing test logs from my own machine vs. [our CI servers](https://github.com/google/blockly/pull/4903/checks?check_run_id=2802943075) it looks like the CI servers are actually running MORE mocha tests than get run locally.  Here are the test output files, trimmed to start with the mocha tests and modified to remove timestamps and element IDs for easier diffing:

* [test-local.txt](https://github.com/google/blockly/files/6639547/test-local.txt) - output from `npm run test:run` on my machine.
* [test-ci.txt](https://github.com/google/blockly/files/6639548/test-ci.txt) - taken from [the CI logs for PR #4903)](https://github.com/google/blockly/pull/4903/checks?check_run_id=2802943075) doing the same thing.

Could it be that tests are passing locally *only because we are not running all of them*?

I'm going to leave this for the time being because I do not understand mocha, selenium, webdriver, etc.

**Comment by cpcallen** [comment]
One further possible clue about what is going on: it seems that the mocha tests are flaky on macOS, and sometimes succeed and sometimes not; e.g., for the same commit:

* [v12 passed](https://github.com/google/blockly/pull/4903/checks?check_run_id=2804483638), and
* [v14 passed](https://github.com/google/blockly/pull/4903/checks?check_run_id=2804483673), but
* [v16 failed](https://github.com/google/blockly/pull/4903/checks?check_run_id=2804483713)

I don't think its v16 specific, however, because at earlier commits v12 passed but v14 and v16 failed.

**Comment by rachel-fenichel** [comment]
To work on this bug:
- Add `macos-latest` back in [`browser_test.yml`](https://github.com/google/blockly/blob/osd/.github/workflows/browser_test.yml#L19)
- Create a pull request
- [Look at logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs) to verify that the tests ran on both ubuntu and macos.
  - Usually creating a PR kicks off the actions, and there will be links to the logs next to each check.

**Comment by alicialics** [comment]
@BeksOmega looks like all tests passes on macos for now: https://github.com/alicialics/blockly/actions/runs/6830615442/job/18578823354?pr=2

**Comment by maribethb** [comment]
Reverting #7640 in #7692 because CI does not pass consistently, but is unrelated to macos actually failing.
