### ISSUE TITLE
Can Blockly use upload file button?

### ISSUE THREAD

**Issue by yenming** [google/blockly#2194]
### Problem statement
I want use FileUpload function (https://www.w3schools.com/jsref/dom_obj_fileupload.asp) in blockly ,but i don't see  any solution in document. Will have this function in the future?Or it has any function to do this it ?

**Comment by rachel-fenichel** [comment]
Blockly just handles the representation of code as blocks on the screen, and the generation of text code from those blocks.  File upload and download are part of your application that uses Blockly, rather than something the library does.  To get the text to save, follow the steps [here](https://developers.google.com/blockly/guides/get-started/web#importing_and_exporting_blocks).

**Comment by yenming** [comment]
Thank you, Let's me try.

**Comment by animeshk-me** [comment]
@yenming could you figure out how to do this?
