### ISSUE TITLE
block colour

### ISSUE THREAD

**Issue by silps** [google/blockly#23]
Is there a good reason that we can only change the HSV hue value ?
Otherwise I could make a pull request with a setHSV function :)

btw, I check out the repository of http://code.org/ https://github.com/code-dot-org/code-dot-org/tree/staging/blockly-core they have done some nice upgrades, their Blockly works much better on small screens

**Comment by NeilFraser** [comment]
You can set the Saturation and Value constants globally (0.0 to 1.0):

Blockly.HSV_SATURATION = 0.45;
Blockly.HSV_VALUE = 0.65;

The purpose of using HSV (instead of RGB) and only changing the Hue per block is to provide a pallet of colours that work well together.  Other graphical programming environments don't have this restriction and, as a result, often look like an angry fruit salad.
http://www.catb.org/jargon/html/A/angry-fruit-salad.html

**Comment by silps** [comment]
ok, I see
thank you for the explanation and a peaceful and successful new year ^_^

**Comment by mspanish** [comment]
While I can understand the desire to avoid a fruit salad arrabiata, it's quite difficult to try and create this feature on your own, and changing a block here and there to customize your app would be enormously helpful. Code.org would look pretty lousy if they just overrode the globals rather than using specific cheerful colors for things like events and the "whenRun" fn. 

I would think adding it as a hidden thing, that only programmers like me willing to spend 3 hours on this would probably find... would certainly enhance Blockly rather than detract from how great a system it is! Just my 2 cents...

**Comment by aroberge** [comment]
@mspanish I started using Blockly and found the same need (basically, I wanted a fairly bright red block to have a "stop" command).  I did it by using the following hack added after I loaded blockly, where I pass an hexadecimal colour explicitly when neeeded:
```javascript
Blockly.makeColour = function(hue) {
  if (typeof hue == "string"){
      return hue;
  }
  return goog.color.hsvToHex(hue, Blockly.HSV_SATURATION,
      Blockly.HSV_VALUE * 255);
};
```

**Comment by deanliou** [comment]
For anyone else finding this post by searching for "blockly block colour hex" in trying to figure out how to get hex colors in: Just supply the hex value in string format - "#RRGGBB". Even though the documentation encourages you to supply with hue integers, you can supply hex color values as string for both toolbox and blockly blocks.

**Comment by silps** [comment]
@deanliou thx for the tip, it works great

**Comment by CleoQc** [comment]
Thanks! Just what I needed!
