### ISSUE TITLE
Blocks unplugged during drag can be lost/deleted

### ISSUE THREAD

**Issue by dalnefre** [google/blockly#2336]
### Problem statement

It appears that dragging some blocks with mixed external input types can result in losing already-created blocks that are unplugged by dragging over them. This can result in significant loss of work, and "undo" does not restore the lost block(s).

### Expected Behavior

Dragging a new block across existing blocks should never cause loss of existing blocks.

### Actual Behavior

Dragging, without dropping, can orphan and/or delete existing blocks.

### Steps to Reproduce

I couldn't get the problem to occur with any of the "standard" blocks, so I created a set of block definitions to demonstrate the problem. The issue seems to require a mixture of type-checked inputs, and seems to be related to the auto-healing/insertion logic, although I don't know what code is effected. I've created a branch in github to demonstrate the issue, with instructions at the top of the page.

https://github.com/dalnefre/blockly/tree/bugged-drag/demos/bugged

### Stack Traces

none

### Operating System and Browser

demonstrated on 
  * Desktop Chrome
  * macOS Mojave (10.14.3)

but probably not browser/OS-specific

**Comment by RoboErikG** [comment]
This looks like an interaction between insertion markers and how we decide if we'll insert between two blocks, and is probably a bug in the insertion marker code.

Notes on the behavior in the demo:

This is happening when a block has an output and more than one value input, but there's a single value input that is legal to connect the block being replaced to and it is not the first input. In this case, Blockly decides to insert instead of replacing, but the insertion marker doesn't reconnect it since it's not on the first input.

**Comment by RoboErikG** [comment]
Here's a set of blocks that reproduces on the Playground. Turns out it doesn't have to be the first input, the block just has to have multiple inputs but only one that matches the block being replaced.

<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="text_charAt" inline="false" x="113" y="13">
  </block>
  <block type="lists_repeat" inline="false" x="88" y="113">
    <value name="ITEM">
      <block type="text">
      </block>
    </value>
  </block>
</xml>

**Comment by rachel-fenichel** [comment]
Thanks for the repro cases.

It's either a bug in insertion marker code or in unplug.  [Here's](https://github.com/google/blockly/blob/master/core/insertion_marker_manager.js#L623-L667) the relevant function in the insertion marker manager.

**Comment by rachel-fenichel** [comment]
And here's our [culprit](https://github.com/google/blockly/blob/master/core/block.js#L382):

```
Blockly.Block.prototype.unplugFromRow_ = function(opt_healStack) {
  var parentConnection = null;
  if (this.outputConnection.isConnected()) {
    parentConnection = this.outputConnection.targetConnection;
    // Disconnect from any superior block.
    this.outputConnection.disconnect();
  }

  // Return early in obvious cases.
  if (!parentConnection || !opt_healStack) {
    return;
  }

  var thisConnection = this.getOnlyValueConnection_();
  if (!thisConnection ||
      !thisConnection.isConnected() ||
      thisConnection.targetBlock().isShadow()) {
    // Too many or too few possible connections on this block, or there's
    // nothing on the other side of this connection.
    return;
  }

  // Only disconnect the child if it's possible to move it to the parent.
  var childConnection = thisConnection.targetConnection;
  if (childConnection.checkType_(parentConnection)) {
    // Disconnect the child block.
    childConnection.disconnect();
    parentConnection.connect(childConnection);
  }
};
```

There's a check for `getOnlyValueConnection` which should be more like `getOnlyValidValueConnection`
