### ISSUE TITLE
Make onFinishEditing_ Better

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2496]
### Problem statement

Currently the text input field has a few little lines inside its widgetDispose_ function that call an onFinishedEditing_ function if it is defined. This is like a secret callback used by the [procedure mutator blocks](https://github.com/google/blockly/blob/9c4f9d6c1693c3c25160f008d3eaa2539127c9e8/blocks/procedures.js#L530) for deleting unnecessary variables.

This is all good, but there's probably a cleaner way to structure the code than directly adding a function to the field object.

### Proposals

A) Create an actual onFinishedEditing API. If one is created, it should probably apply to more than just the text input field (possibly every field). 

B) The procedures_mutatorarg block should clean up after itself as it creates new variables. I'm not sure how possible this is because I haven't looked into it.

### Additional Information

N/A

**Comment by BeksOmega** [comment]
C) Instead of creating variables, just rename them. Also not sure how possible this is because I haven't looked into it.

**Comment by mattbishop** [comment]
Text fields are a different beast than other inputs like checkbox and dropdown because text fields have and intermediate 'editing' state where the user is composing their change with the keyboard. Right now it is almost never correct to create field change events on every keypress because the user doesn't intend to use the intermediate value in the rest of the model.

If I wanted to enter a value into a field called 'firstName', I just want 'Matt' as the change event, not 'M', 'Ma', 'Mat' and finally 'Matt'. The final value is the real change event because the user clicks away from the text field, or hits Return. Similarly, they want to cancel an editing session by pressing ESC.

**Comment by BeksOmega** [comment]
To fix this, we want to add a new type of event that signals that a field edit has been completed.

This has recently come up again in the context of updating App Inventor, because they want to trigger workspace saves when a user has finished editing a field (rather than on every keypress). And we'd like to have a fix for this this quarter.

The first part of fixing this is to create a new event type that includes the workspace ID, block ID, field name, original value, and final value.

And the second part is modifying the existing fields to actually fire these events when their editors are closed. Here are some examples of how this should work for different fields:

- Text Input: The event would be fired when the input is closed (i.e. click away, or enter). It would contain the text of the field pre-edit and post-edit.
- Angle: The event would be fired when the DropDownDiv is closed (i.e. on click). It would contain the value of the angle field pre-edit and post-edit.
- Checkbox: The event would be fired every time the checkbox is clicked. In this case it would function identically to the BlockChange event.
- Dropdown: The event would be fired when a new dropdown option is clicked. In this case it would function identically to the BlockChange event.
