### ISSUE TITLE
Date picker should fire change events

### ISSUE THREAD

**Issue by ufalak** [google/blockly#2534]
After i change the value of a Date Field in the workspace, doesnt raise the "change" event

**Comment by rachel-fenichel** [comment]
@BeksOmega is this from one of your recent changes, or does it predate it?

**Comment by BeksOmega** [comment]
Predates, will be fixed in the next push to master.

Gif of events:
![DateField_Events](https://user-images.githubusercontent.com/25440652/59215796-04d1cd80-8b6f-11e9-9d58-5d7b4afdba14.gif)

Snip of expanded event:
![Date_Events](https://user-images.githubusercontent.com/25440652/59215790-000d1980-8b6f-11e9-8710-2f746ce9f8b4.jpg)

**Comment by ufalak** [comment]
> Predates, will be fixed in the next push to master.
> 
> Gif of events:
> ![DateField_Events](https://user-images.githubusercontent.com/25440652/59215796-04d1cd80-8b6f-11e9-9d58-5d7b4afdba14.gif)
> 
> Snip of expanded event:
> ![Date_Events](https://user-images.githubusercontent.com/25440652/59215790-000d1980-8b6f-11e9-8710-2f746ce9f8b4.jpg)

when you estimate to push that?

**Comment by rachel-fenichel** [comment]
About two weeks.
