### ISSUE TITLE
Trashcan drop target misbehaves on iOS Chrome

### ISSUE THREAD

**Issue by geppy** [google/blockly#26]
Using the "graph" demo (with PR #25 applied) on iOS 8 gives strange results with detecting whether or not something was dropped over the trashcan.  When zoomed out, I'm unable to throw things away.  When zoomed in, any time I move a block it gets deleted.

**Comment by NeilFraser** [comment]
The issue is located in the getScreenCTM call made by Blockly.mouseToSvg.  The input is correct: the absolute location of the touch event on the physical screen.  The output is incorrect: in Safari getScreenCTM compensates for the zoomed-in scroll, whereas Chrome does not account for the scroll.

https://code.google.com/p/chromium/issues/detail?id=81995

**Comment by AnmAtAnm** [comment]
Tested this on 9.3.5 (released on August 25, 2016) and I'm not seeing issues detecting the mouse over (trash can animates) or throwing away blocks. Tested at multiple zoom levels.

Please reopen if this remains an issue on any more recent version iOS.
