### ISSUE TITLE
Change Events before Create Event

### ISSUE THREAD

**Issue by twodee** [google/blockly#2627]
### Problem statement

In the `Block` constructor, we effectively have this code:

```
if (typeof this.init == 'function') {
  this.init();
}

// Fire a create event.
if (Blockly.Events.isEnabled()) {
  Blockly.Events.fire(new Blockly.Events.BlockCreate(this));
}
```

The create event is fired after `init`, but `init` may itself fire events. The events that `init` triggers appear in the undo stack earlier than the create event. Undoing the create event deletes the block, but further undoing has no block on which to operate.

### Expected Behavior

The create event should be triggered first. Even if the user never invokes undo, change listeners may expect a create event before change or move events.

Additionally, `init` probably shouldn't record undoable events. It seems to me that the creation and initialization should be an atomic operation that can't be undone in pieces.

### Actual Behavior

Depending on the block configuration, events appear in this order:

- Any change events fired from init, which may be defined by the developer or ultimately be a call to `jsonInit`.
- A create event for the block fired by the block constructor.

### Steps to Reproduce

Fire off this code once the workspace is ready:

```
Blockly.Blocks['formal'] = {
  init: function() {
    this.jsonInit({
      isMovable: false,
      output: null,
      inputsInline: true,
      message0: '%1',
      args0: [
        { type: 'field_input', name: 'identifier', text: '' },
      ]
    });
  }
};

let formal = workspace.newBlock('formal');
formal.initSvg();
formal.render();
```

Inspect the events and you will see a change event for `inputsInline` followed by the create event. If you undo twice, you will see this warning:

```
Can't change non-existent block: EC/e%VuMA:tL==lXW53!
```

### Additional Information

I'm happy to submit a pull request after getting input from others.

**Comment by twodee** [comment]
There are two other places where a `BlockCreate` is fired: `core/contextmenu.js` and `core/workspace_svg.js`. Both of these situations disable events fired by the preceding code.

**Comment by maribethb** [comment]
I spent some time looking at this today and I believe the correct solution is to just set recordUndo to false before this.init() is called in the Block constructor. We should also probably set the group id here to match the same group id as the create event.

We actually don't want the create block event to come first, because that event could refer to newly created variables, etc. I do agree it may be a bit weird for change listeners that the create event comes after the change event, but hopefully setting the group id to match will help alleviate that weirdness. That's already how it works in some situations and the create event being first actually causes other issues in the flyout, see #3584 for more discussion.

However, you are right that init shouldn't record undoable events, because it should be all one atomic operation that you can't undo in pieces. I don't want to disable events completely as developers might want to do things in their own block init that can be listened for, but it doesn't make sense to partially undo creating a block. I'm working on a change for this now and will do a bit more thorough testing after the weekend before submitting a PR. But right now it seems to resolve the issue where creating a single block causes the undo button to be clickable more than once and the second one just prints a warning.
