### ISSUE TITLE
Translate Github Wiki

### ISSUE THREAD

**Issue by Clonewayx** [google/blockly#278]
Is here any place for translating [Blockly GitHub Wiki](https://github.com/google/blockly/wiki) in to other languages?

**Comment by NeilFraser** [comment]
There is currently no plan to translate those pages.  When we started Blockly we assumed that having good end-user documentation would be one of the most critical features.  In the four years since then we have never once seen a student intentionally go to a help page and read it.  Tooltips appear to be useful, but the help links remain are unused.

**Comment by carlosperate** [comment]
Quick question, is there a license to the wiki contents? If not, could one be applied so that it could be used as a base for documentation of projects based on blockly?

**Comment by NeilFraser** [comment]
The wiki is part of the Blockly repo, and is thus Apache 2.  (Translation: do anything you want.)

**Comment by carlosperate** [comment]
Well, while I appreciate the sentiment, the wiki is its own git repository, and if you clone it there is no licence file, nor statement ttached to the content. So while it might be part of Blockly, there is nowhere indicating this explicitly or if it follows the same licensing.

**Comment by NeilFraser** [comment]
I'll check in a licence next time I edit the wiki.  Probably make it Creative Commons Attribution 3.0 License to match the content on developers.google.com/blockly  Reopening this issue.

Historically this wasn't a problem since the wiki was explicitly open source back when we were hosted on code.google.com.

**Comment by carlosperate** [comment]
:+1:

**Comment by NeilFraser** [comment]
Fixed.  Now using Creative Commons Attribution 4.0 License.
