### ISSUE TITLE
Create and Delete Events Generate Lots of Detached Nodes

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2795]
**Describe**

Create and delete events generate lots of detached nodes.

This is because those events[ store the xml](https://developers.google.com/blockly/guides/configure/web/events#blocklyeventsblock_delete) of the created/deleted blocks.

**To Observe**

Steps to observe the behavior:
1. Go to the playground.
2. Run the spaghetti stress test.
3. Delete all of the blocks.
4. Create a [heap snapshot](https://developers.google.com/web/tools/chrome-devtools/memory-problems/#discover_detached_dom_tree_memory_leaks_with_heap_snapshots).
  A) Go to the memory tab of the chrome dev tools.
  B) Select the Heap Snapshot button.
  C) Press the "Take Snapshot" button.
  D) In the "Class filter" type in "Detached"
5. Observe the large number of detached nodes:
![Detached_1](https://user-images.githubusercontent.com/25440652/62796549-65f22080-ba8e-11e9-8e74-b212aa6165d8.png)
6. Expand the detached node, and select the first entry.
7. Observe how it is part of a delete event:
![Detached_2](https://user-images.githubusercontent.com/25440652/62796696-afdb0680-ba8e-11e9-8d2f-89a91e70d3eb.png)

**Describe the solution you'd like**

Honestly, I know that detached nodes are bad but I don't know what you're supposed to do instead, since these are being used for storage purposes.

Maybe storing the block information as JSON would be better? I have [designed a system](http://bekawestberg.me/blog/blockly-serialization/) for adding JSON serialization to the Blockly serializer.

**Describe alternatives you've considered**

Maybe converting the dom to text would be better? But again I really have no knowledge in this area.

**Additional context**

Tracking issue [requested by Rachel](https://github.com/google/blockly/pull/2770#issuecomment-518856258).

**Comment by rachel-fenichel** [comment]
These are being kept alive by the undo stack on the workspace--calling `Blockly.mainWorkspace.clearUndo()` in the playground clears them out.  A reasonable solution is to set a depth on the undo stack.  64 [undos ought to be enough for anybody](https://en.wikiquote.org/wiki/Talk:Bill_Gates#640_k/1_MB).

**Comment by rachel-fenichel** [comment]
@picklesrus @ewpatton Do you folks already have a depth on the undo queue to solve this?

**Comment by ewpatton** [comment]
We do not set a limit in App Inventor.

It would be interesting to do some performance tests to see how much it affects us, but based on previous experience it’s the layout and render passes over many blocks that tend to make our workspace bog down once N is large. I’d be interested in seeing how that ends up changing with the new rendering pipeline.

**Comment by rachel-fenichel** [comment]
I think this would matter if you have a long-lived workspace, like a tab you've had open for a lot of time and have been poking at.  Maybe also when opening a giant workspace, since that would create these all at once, so that could be a good way to check.

**Comment by ewpatton** [comment]
Long lived workspaces, possibly, but it’s not yet clear exactly how much memory is “leaking” there. Since we don’t record events during load, there shouldn’t be anything on the undo stack at the start of a session even for large projects. I can run some tests and get concrete numbers on Thursday.

**Comment by NeilFraser** [comment]
I ran some tests in Chrome.  My results were fairly consistent between runs, so I have confidence in the results.

* Load playground, memory snapshot: 5.3 MB.
* Run Spaghetti test, memory snapshot: 21.2 MB.
* Delete playground, wait a minute for garbage collection, memory snapshot: 5.7 MB.

Now comment out the two lines where oldXml is set and repeat:

* Delete playground, wait a minute for garbage collection, memory snapshot: 5.6 MB.

This indicates that the XML (the detached Nodes) takes 100 KB.  By comparison, converting this XML to text:

`Blockly.Xml.domToText(workspace.undoStack_[2].oldXml).length/1024 -> 326`

My conclusions are:
1) XML nodes are being stored three times more efficiently than the easiest text-based representation.
2) The leak of about 33 bytes per block deletion (100 KB for 3,000 blocks) seems low enough not to worry about, since it serves a genuine purpose (undo).

**Comment by NeilFraser** [comment]
I should follow up and say that this is absolutely a topic that should be explored.  There may be monsters lurking in our memory management that we aren't aware of.  Like that time when we discovered that the connection database was O(n^2) and was using the majority of our CPU time due to a trivial inefficiency.

There are not a lot of eyes on our memory heap, so it's a promising thing to poke at.  Thank you @BeksOmega!

**Comment by rachel-fenichel** [comment]
Turns out we have a MAX_UNDO, so this is bounded (as well as being small per-block).  Closing.
