### ISSUE TITLE
Alignment issues

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2894]
Old renderer:
![Screen Shot 2019-08-21 at 09 35 24](https://user-images.githubusercontent.com/250480/63450885-dfc3cb80-c3f7-11e9-8e90-8e2de45bb038.png)

Current renderer:
![Screen Shot 2019-08-21 at 09 35 05](https://user-images.githubusercontent.com/250480/63450888-e18d8f00-c3f7-11e9-97b8-a2614b16255c.png)

There are three issues:

1. (Blue line) Blocks on the toolbox used to be left-aligned, not counting the tab.  This was a deliberate design choice.  Now they are aligned including the tab.
2. (Green line) Text on a row used to be straight.  Now text height undulates between labels and fields.
3. (Red arrow) The gap between the bottom of a statement block and its enclosing control block used to be zero if there was no "next notch" (indicating that no more blocks could be added), and the height of the "next notch" if there was one (indicating that more blocks could be added).  Now there's a huge gap.

I'm also not convinced that the mutator/comment/warning icons ought to be center-aligned on the first row (new behaviour), rather than fixed to the top corner (old behaviour).  These icons are block-related, not row-related.

**Comment by rachel-fenichel** [comment]
1. This is #2828
2. Text is now center-aligned in a row (everything is center-aligned in a row) instead of absolutely positioned.  Text now undulates slightly within a single block but is significantly improved within a multi-block row (and connections will follow soon):
old: ![image](https://user-images.githubusercontent.com/13686399/63453766-40ee9d80-c3fe-11e9-93cf-f28c461b8c83.png)
new: ![image](https://user-images.githubusercontent.com/13686399/63453779-464be800-c3fe-11e9-94f7-cd258d6ac81d.png)

We have a couple of options here:
- Undo the vertical centering entirely
- Define a "baseline" property and align on that instead of centering
- Make text input fields (and fields that inherit from them) place their text slightly lower.
3. Yup, this is a bug.  Statement input sizing isn't quite right overall at this point.

Block related icons should still be aligned with the text, in my opinion.  Fixing them to the corner will mean they'll be misaligned with the text in the row by a variable amount and looks weird.

**Comment by RoboErikG** [comment]
Relatively fixed. We'll take another look at text baseline alignment later.
