### ISSUE TITLE
Stack blocks can splice into immovable blocks

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2988]
**Describe the bug**

Stack blocks can be placed inbetween an immovable block and its parent.

**To Reproduce**

1. Load the following xml to the playground:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="text_print" id="wlc#l2D-,6mSLKY=E$VL" x="-76" y="-112">
    <next>
      <block type="text_print" id="T9cdR}mwDn3Xl!*g|mw8" movable="false">
        <comment pinned="true" h="32" w="88.5333251953125">Immovable</comment>
      </block>
    </next>
  </block>
  <block type="text_print" id="ZgFlirwB{~}%l/BZ+j?R" x="47" y="-118"/>
</xml>
```
2. Drag the orphaned text_print block between the two other text_print blocks.

**Expected behavior**

You should not be allowed to move an immovable block, even through splicing.

**Screenshots**

![ImmovableStacks](https://user-images.githubusercontent.com/25440652/64539941-3aa06280-d2d4-11e9-8e4b-bb297d6b3374.gif)

**This is not browser specific**

**Additional context**

This does not occure with input/output connections:
![ImmovableRows](https://user-images.githubusercontent.com/25440652/64540255-bef2e580-d2d4-11e9-927c-960ac0ca5156.gif)

**Comment by moniika** [comment]
There's definitely some inconsistency here in behavior.
If going by the documentation of [movable state](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#movable_state), an immovable block cannot be moved directly, though it can be moved with its parent, and it cannot be disconnected from its parent. 

I think in this example, it is ok that the immovable block moves because it would introduce a lot of additional complexity to be able to handle some edge cases like: a stack in between 2 immovable blocks. However, based on the rules we've set, we shouldn't be able to put a block between an immovable block and a connected parent.
There's also a question of whether you should be able delete the parent block connected to an immovable block. Currently you can (in both the stack example and the input/output connection) but it doesn't seem consistent with the rule that it cannot be disconnected from its parent.

**Comment by BeksOmega** [comment]
I know it's unrelated to this issue, but with regard to parent deletion, I think it sort of makes sense that immovable blocks would get deleted with their parents? but then that also kinda causes problems with the deletable property.

The only use case I can think of for making a sub-block immovable is if you want it to be kind of "sticky". Basically it and its parent act like one block, but they're separate blocks because you're trying to teach programming.

In that case you'd want the sub-block to:
1) Only move with its parent (check)
2) Delete with its parent (currently doesn't happen)
3) Don't allow deleting it alone (you can add the deletable tag)

But number 2 and number 3 create a conflict.

In this case you want the deletable tag to mean "don't delete me directly, but I can be deleted if my parent is" while[ other cases](https://github.com/google/blockly/issues/2158) you want the deletable tag to mean "never delete me, ever, under any circumstances".

I guess you _could_ create a check that goes like:
If my child is not deletable, don't delete it. Unless it is also not movable, then do delete it.

But really, that doesn't make a lot of sense either.

**Comment by maribethb** [comment]
Code dot org has a "lock to parent" property in their fork, which works similarly to what Beka described above. You want two blocks to always be moved/deleted together, nothing can be placed in between. They are separate blocks because they are trying to teach programming. 

It's not fully recreatable with only the movable/deletable properties because of the behavior described here. This is causing them problems with their de-forked environments. It's possible for students to get into a state where they dragged blocks between, and can't figure out how to remove that block (they could just delete the one they added but they may not know that and try to solve problems via dragging)
