### ISSUE TITLE
False connection highlights

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#308]
Connection highlighting is borked:
https://www.youtube.com/watch?v=gLdb_Ioo0VQ

And if you drop while the highlight is on, Blockly crashed hard:
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

Visible on master in production.

**Comment by rachel-fenichel** [comment]
Taking a look.  Do you have more details on when this happens?  I can reproduce what you showed; I can't get it to happen with inputs/outputs.

**Comment by rachel-fenichel** [comment]
Got it.  The way we check if we're connecting to a block in the stack we're dragging assumes that the current connection is on the top block fo the stack.  When connecting to the last block in the stack is allowed, that assumption is broken.

For now we can fix this by not allowing the last block in the stack to be considered.  Going forward, a list of dragging connections (rather than explicitly walking the chain of parents) will let us re-enable this feature.
