### ISSUE TITLE
IE11 Undoing after deleting block breaks

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3174]
**Describe the bug**
Undoing after moving the block to the trashcan breaks.

**To Reproduce**
1. Move a block to the workspace 
2. Move the block to the trashcan
3. Undo

Observe: The block is still next to the trashcan

**Expected behavior**
The block should go back to it's original location

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**
warning in console: 'Can't move nonexistent block'

```
Replace with error stack trace.
```

**Additional context**

**Comment by RoboErikG** [comment]
I think this is the same as #2627 , but needs some investigating

**Comment by RoboErikG** [comment]
@rachel-fenichel to investigate why this is a browser specific issue

**Comment by rachel-fenichel** [comment]
- Not a regression
- Getting the block id out of the event XML isn't working on IE11
- It fails this way on drag-to-delete (could not repro by clicking on the block and hitting the delete key)
- Drag to delete causes two events: Move and Delete.
  - Undoing causes two events: Create and Move
  - The result of the Create has a different ID from what it had on the way into the trash
  - Then the Move fails because no block with the original ID exists

ID is null here: https://github.com/google/blockly/blob/master/core/xml.js#L604
Not null here in Chrome.

**Comment by alschmiedt** [comment]
Repro steps for hitting the delete key: 
1. Connect a block to a statement input
2. Delete the nested block 
3. Undo

The block is in the correct location but is not actually connected to the parent.

**Comment by rachel-fenichel** [comment]
Oh okay, that makes sense--restoring a block that's connected has a Move to reconnect it.  Same issue though.

**Comment by samelhusseini** [comment]
Looks like the issue is serialization. (reason it's not getting the block id from the xml is because it's not there). You can repro this by just adding any random block to the workspace in IE, and "Export to XML". Notice how the xml has no block ids.

**Comment by samelhusseini** [comment]
Setting id like this, doesn't work in IE. https://github.com/google/blockly/blob/develop/core/xml.js#L149

I wonder what else is affected..

**Comment by samelhusseini** [comment]
Looks like setting id like that only affects XML nodes, and not HTML elements.

**Comment by samelhusseini** [comment]
Fixed.
