### ISSUE TITLE
RenderedConnection.moveTo should check whether anything changed before modify the db

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3215]
```
/**
 * Change the connection's coordinates.
 * @param {number} x New absolute x coordinate, in workspace coordinates.
 * @param {number} y New absolute y coordinate, in workspace coordinates.
 */
Blockly.RenderedConnection.prototype.moveTo = function(x, y) {
  // Remove it from its old location in the database (if already present)
  if (this.inDB_) {
    this.db_.removeConnection_(this);
  }
  this.x_ = x;
  this.y_ = y;
  // Insert it into its new location in the database.
  if (!this.hidden_) {
    this.db_.addConnection(this);
  }
};
```

We move connections when we go up the stack, but most of those movements are no-ops.  Don't touch the DB if nothing changed.

**Comment by rachel-fenichel** [comment]
@samelhusseini to profile if you're bored :)

**Comment by rachel-fenichel** [comment]
This may be handled already by a check in `RenderedConnection.tighten_`

**Comment by BeksOmega** [comment]
Based on some logging, I don't think there are actually many noops. I did some testing with the spaghetti blocks in the playground, and for one movement I got 51k actual operations vs 30 noops.

The connection DB is "keyed" primarily based on the vertical position of the connections, so it makes sense that when blocks are moved up/down a stack, the connection positions in the db would actually need to be moved. And it makes sense that it is "keyed" primarily based on vertical position, because (using the default renderer) Blockly has a lot more vertical differentiation, which makes the binary searches for connections more efficient.

Perhaps we could elliminate some operations if blocks are only moving horizontally? But since this is rarer (Blockly being primarily vertical) I don't think we would actually see any benefits to this.
