### ISSUE TITLE
workscape.zoomToFit() gives an error if there are no scrollbars

### ISSUE THREAD

**Issue by miguel76** [google/blockly#325]
`Blockly.WorkspaceSvg.prototype.zoomToFit()` calls some methods on `this.scrollbar` without checking if it is defined.
It gives thus an error in the case of a workspace without scrollbars (option `scrollbars: false`).
See how instead `zoom()` and `zoomReset()` deal with that case.

**Comment by miguel76** [comment]
Same problem if there is no toolbox (`this.toolbox_` is not defined)

**Comment by NeilFraser** [comment]
I think this fixes the issue, but I'll test it some more tomorrow before merging with master.

Unsolved problem: In the case of a workspace with a fixed flyout (rather than a category toolbox) the flyout changes size depending on the zoom level.  So computing the zoom level is dependent on the zoom level.  This means that calling zoomToFit multiple times will result in either asymptotically approaching the optimum zoom, or will alternate between over and under zoom.
