### ISSUE TITLE
Paste on current workspace & view

### ISSUE THREAD

**Issue by miguel76** [google/blockly#334]
Right now, the behaviour of a copy/paste operation is equivalent to duplicate. That is, the new copy of the block is created close to the original one, irrespective of the current part of the workspace that the user is viewing.
This behaviour is counter-intuitive for the users, that expect the block to be pasted were "the focus is".
Considering also --thanks to last improvements-- the chance to work with multiple workspaces, it is also counter-intuitive that the block get pasted in source workspace, instead that in the currently focused workspace.

I propose that the paste operation positions the new block in the current focused workspace, at center (or around the center) of the area currently on view.
To the method `Blockly.WorkspaceSvg.prototype.paste()` a boolean parameter could be added to select the current behaviour (that would be used by `Blockly.duplicate_()`, say with `false` or `undefined`) or the new one (say with `true`).
From `Blockly.onKeyDown_()` the paste operation would be something like `Blockly.mainWorkspace.paste(Blockly.clipboardXml_, true)` instead of `Blockly.clipboardSource_.paste(Blockly.clipboardXml_)`.

**Comment by NeilFraser** [comment]
Pasting across workspaces is a bit challenging since different workspaces may have different blocks.  For instance, a mutator's workspace and the main workspace should not allow copy and paste between them.  Likewise an application like the Block Factory should not allow copy and paste between its two workspaces.  Implementing cross-workspace copy/paste also involves creating some form of access control so that workspaces can choose to accept or reject pastes from other workspaces.

Cross-workspace copy/paste also surfaces a second issue.  Users would naturally expect that they could copy between workspaces on separate browser tabs.  Now we need to start using the system clipboard (something that is borderline impossible -- I know because I worked on this while implementing Google Docs), or else we need to set up a cloud-based clipboard service.

It is definitely a desirable feature, but it opens up a can of worms that will take a lot of effort to resolve.  As such, I chose to just implement single-workspace copy/paste for now.  It is easier for developers to add cross-workspace copy/paste for their specific application than it is for us to solve the general case.

**Comment by miguel76** [comment]
I have to admit I had not think about all the potential complicacies of how to manage copy/pasting among potentially heterogeneous workspaces.

Anyway, my basic reason to open this issue was related to the fact copy/paste in the same workspace happens close to the original block, rather than where the user focus is.
I think this is counter-intuitive for the user and it could be solved with a reasonable amount of work.
What do you think?

**Comment by NeilFraser** [comment]
Agreed, pasted blocks should not appear offscreen if the workspace has been scrolled.

**Comment by MNSDivya** [comment]
Blocks are pasted close to the original block, not wher the user focus is. 
Reported Issue still persists

**Comment by luddilo** [comment]
> Blocks are pasted close to the original block, not wher the user focus is.
> Reported Issue still persists

Any plan on looking into this or is there any known work-around - perhaps scrolling to the new pasted block?

**Comment by kstanitzok** [comment]
Any update on this issue?

**Comment by BeksOmega** [comment]
> Any update on this issue?

You can now paste across workspaces using the [cross-tab-copy-paste plugin](https://www.npmjs.com/package/@blockly/plugin-cross-tab-copy-paste) =) Currently it doesn't have handling for heterogeneous workspaces, but a contributor recently added an [error callback](https://github.com/google/blockly-samples/pull/1291) which will allow you to handle them. That should be released this week or next!

**Comment by BeksOmega** [comment]
I'm closing this in favor of #6848 (which tracks pasting within the viewport) and #6849 (which tracks pasting across workspaces).
