### ISSUE TITLE
Closure Compiler is not tree shaking

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#3415]
Search entire Blockly codebase for `domToPrettyText` and there is only the definition in xml.js, along with a few calls in various demos and tests (but notably not the compile test).

Run the compile test then search main_compressed.js for `/(<(\w+)\b[^>]*>[^\n]*)\n *<\/\2>/g` (a literal that's exclusively found in domToPrettyText).  There's one match.  

Closure Compiler is failing to tree shake.  Inspection of the compressed file reveals similar unused functions.

**Comment by DimuDesigns** [comment]
@NeilFraser @rachel-fenichel Going off on a tangent here (but I'll wrap it back around). Are there any plans to migrate Blockly away from using closure and move to the ES module standard instead? ES modules seem to have better tooling to support tree-shaking as well as a number of other advantages.

**Comment by rachel-fenichel** [comment]
It's something I want to investigate next year.  As we've added more options for Blockly, we have more code that goes completely unused for simple applications, and I want to get that code shaken out in a way that's supported by common development setups.

However, we don't have a specific timeline for that work.

**Comment by cpcallen** [comment]
This is presumably due to `blockly_compressed.js` [being built with `options.compilation_level = 'SIMPLE_OPTIMIZATIONS'`](https://github.com/google/blockly/blob/9a93ca486f556490294e4fc115db87c9428db040/scripts/gulpfiles/build_tasks.js#L117); per [the documentation](https://developers.google.com/closure/compiler/docs/compilation_levels), dead code removal is a feature of `ADVANCED_OPTIMIZATIONS`.

Enabling `ADVANCED_OPTIMIZATIONS` is going to require a more clearly defined API, so this is dependent on the `goog.module` work, and so this bug is not a good candidate for Bug Bash for this quarter (2021 Q2).

**Comment by NeilFraser** [comment]
@cpcallen No, this is the [compile test](https://github.com/google/blockly/tree/master/tests/compile) which does do `--compilation_level ADVANCED_OPTIMIZATIONS`

**Comment by NeilFraser** [comment]
Got it!

The reason for Closure Compiler not tree-shaking was this PR:
https://github.com/google/blockly/pull/1749
It added a function called `Blockly.checkBlockColourConstant_` which walked over the Blockly tree in ways the compiler could not predict.  Deleting this function dropped Blockly's compile size down by 10%.  I've verified that this (uncalled) code is enough to break tree-shaking:
```
Blockly.checkBlockColourConstant_ = function() {
  var value = Blockly;
  var blocklyNamePath = [];
  for (var i = 0; i < blocklyNamePath.length; ++i) {
    value = value[blocklyNamePath[i]];
  }
};
```

**Comment by cpcallen** [comment]
> Deleting this function dropped Blockly's compile size down by 10%.

Note that this refers to the advanced compilation test only.

I can confirm that the offending function was removed in PR #5262 and so this bug has been resolved.
