### ISSUE TITLE
Workspace options should always be parsed

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3459]
**Describe the bug**

Because options are parsed in inject instead of the workspace constructor, you can get headless workspaces the opperate differently from svg workspaces. [https://groups.google.com/forum/#!topic/blockly/tfHCA7afoC0](https://groups.google.com/forum/#!topic/blockly/tfHCA7afoC0)

This also makes working with flyouts confusing, because while they do have workspaces they may not work as you first assume.

**To Reproduce**

1. Create a rendered workspace and a headless workspace. Pass options to neither.
2. Deserialize the following xml to both workspaces.

```
<xml xmlns="https://developers.google.com/blockly/xml">
  <variables>
    <variable>i</variable>
  </variables>
  <block type="variables_set">
    <field name="VAR">i</field>
    <value name="VALUE">
      <block type="lists_create_with">
        <mutation items="3"/>
        <value name="ADD0">
          <block type="text">
            <field name="TEXT">1</field>
          </block>
        </value>
        <value name="ADD1">
          <block type="text">
            <field name="TEXT">2</field>
          </block>
        </value>
        <value name="ADD2">
          <block type="text">
            <field name="TEXT">3</field>
          </block>
        </value>
      </block>
    </value>
    <next>
      <block type="text_print">
        <value name="TEXT">
          <shadow type="text">
            <field name="TEXT"/>
          </shadow>
          <block type="lists_getIndex">
            <mutation statement="false" at="true"/>
            <field name="MODE">GET</field>
            <field name="WHERE">FROM_START</field>
            <value name="VALUE">
              <block type="variables_get">
                <field name="VAR">i</field>
              </block>
            </value>
            <value name="AT">
              <block type="math_number">
                <field name="NUM">1</field>
              </block>
            </value>
          </block>
        </value>
      </block>
    </next>
  </block>
</xml>
```
3. Export both workspaces to javascript.

```
// Rendered.
var i;


i = ['1', '2', '3'];
window.alert(i[0]);
```

```
// Headless
var i;


i = ['1', '2', '3'];
window.alert(i[1]);  //Bad!
```
4. Observe how the headless workspace behaves differently.

**Expected behavior**

Both workspaces should result in `window.alert(i[0]);`.

**Additional context**

Flyouts, mutators, and mutator flyouts should get a thorough testing if this is fixed, because there may be code relying on their current behavior.

**Comment by rachel-fenichel** [comment]
The issue as reported on the forum is about oneBasedIndexing:
"This isn't really a Blockly bug, but it tripped me up so I wanted to share. While workspaces are usually created with Blockly.inject(), headless ones use the workspace constructor. Both accept options. But if no options are provided, inject() will use the default options while the constructor just uses an empty options object. That difference hardly matters because most workspace options have no effect on headless workspaces, but then there's oneBasedIndex which affects code generation. So be sure to pass options to your workspace constructors. To the team: maybe mention this behaviour in the headless demo source, or make the constructor use the default options too."

The work item for the q4 release is to figure out what it would take to parse options for headless workspaces and post a write-up here.
