### ISSUE TITLE
disable trashcan (and deleting) at runtime (for offline mode)

### ISSUE THREAD

**Issue by mattbishop** [google/blockly#3467]
**Is your feature request related to a problem? Please describe.**

My app has to be connected to a backend server to send change events. When offline, I disable all the blocks in the workspace and flyout, so new blocks cannot be added or edited.

However, these blocks are still deletable by dragging them to the trash or with the DEL key. These changes are not sent to the server because it isn't available. 

**Describe the solution you'd like**

I'd like to be able to switch a workspace to readOnly mode dynamically so that when the app detects it is offline, it can disable all editing, including delete.

**Describe alternatives you've considered**

I currently hack the workspace to disable/enable all blocks, which works for adding and changing.

I have tried hacking the trashcan contents and options but it doesn't work so well. I will probably figure it out but it will be ugly. Better to ask for help! 

**Additional context**

Here is the code I used to disable/enable the workspace blocks:
```
function setBlocklyEnabled(isEnabled) {
  const workspace = Blockly.getMainWorkspace()
  if (workspace) {
    workspace.getFlyout()
      .getWorkspace()
      .getAllBlocks(false)
      .forEach((block) => block.setEnabled(isEnabled))

    workspace.getAllBlocks(false)
      .forEach((block) => block.setEnabled(isEnabled))
  }
}
```

**Comment by BeksOmega** [comment]
Sorry I didn't reply to your post on the group in time! It turns out it's actually really hard to make readonly toggleable, because there are loads of event handlers that need to be added and removed.

I don't believe the team wants to add that functionality at the moment (but idk I'm not there ¯\\\_(ツ)_/¯).

One method I recommend for changing config options is to:
1. Serialize the workspace to XML.
2. Dispose of the workspace.
3. Re-inject a new workspace with the new config.
4. Deserialize the XML.

I've used this method before to change the language of a workspace, and I think it works pretty well!

Do you think that could work for your situation?

*Additional Info*
See #3049 and https://groups.google.com/forum/#!msg/blockly/NCukwTKMR0U/30BABGu4BQAJ

**Comment by rachel-fenichel** [comment]
+1 to what Beka said.  Our recommendation is to dispose and re-inject.
