### ISSUE TITLE
use Ctrl + z can delete moveable = false ,deleteable = false block

### ISSUE THREAD

**Issue by tuxianchao** [google/blockly#3486]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by RoboErikG** [comment]
@tuxianchao please provide repro steps. There's not normally a way to create non-movable/deletable blocks in a way that they're added to the undo stack.

**Comment by RoboErikG** [comment]
Unfortunately, we'll need repro steps to understand the issue you're seeing. Closing for now but will re-open if we get more detail.

**Comment by justinvvitale** [comment]
> Unfortunately, we'll need repro steps to understand the issue you're seeing. Closing for now but will re-open if we get more detail.

When you load up a workspace (e.g from a database) with multiple blocks but the action list is empty. If you press ctrl z, it'll undo all the loaded blocks even if they're not deletable. Is there a way around this?

**Comment by BeksOmega** [comment]
> When you load up a workspace (e.g from a database) with multiple blocks but the action list is empty. If you press ctrl z, it'll undo all the loaded blocks even if they're not deletable. Is there a way around this?

@justinvvitale you should be able to call [Blockly.Events.disable()](https://developers.google.com/blockly/reference/js/Blockly.Events#.disable) before loading and [Blockly.Events.enable()](https://developers.google.com/blockly/reference/js/Blockly.Events#.enable) after loading so that no events are fired. If you have any further questions I (and others) are happy to help, but please ask on the [developer forums](https://groups.google.com/g/blockly) so we can keep the github clean :D Hope that helps!
