### ISSUE TITLE
Flyout contentTop should not be zero

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#349]
ContentTop should be optionBox.x
https://github.com/google/blockly/blob/master/core/flyout.js#L226

But setting it to a nonzero value breaks scroll: https://github.com/google/blockly/blob/master/core/flyout.js#L246

and also causes weird scroll behaviour on a window:resize.  This seems to indicate that contentTop is being used in ways that it shouldn't be, but that those problems have been masked by the fact that it is always zero in the flyout.

**Comment by MNSDivya** [comment]
URLs redirecting 404 error. 
![image](https://user-images.githubusercontent.com/56336353/81277477-1c148600-9072-11ea-8058-70c8b9eb3777.png)
@rachel-fenichel can you please assist what exactly is the issue here.

**Comment by alschmiedt** [comment]
Updated Links:
https://github.com/google/blockly/blob/17ef4c536463bdb509c557ecf15b82535bb285c6/core/flyout.js#L226 & https://github.com/google/blockly/blob/17ef4c536463bdb509c557ecf15b82535bb285c6/core/flyout.js#L246

Closing since I think this is an out of date issue. The flyout was refactored in June 2017 into a horizontal and vertical flyout. It looks like the contentTop is no longer used when deciding the scroll value ([horizontal flyout](https://github.com/google/blockly/blob/edd475f37b02888819b87ddfca1d6eeebe68898a/core/flyout_horizontal.js#L114) & [vertical flyout](https://github.com/google/blockly/blob/edd475f37b02888819b87ddfca1d6eeebe68898a/core/flyout_vertical.js#L118)). 
[contentTop in the vertical flyout](https://github.com/google/blockly/blob/edd475f37b02888819b87ddfca1d6eeebe68898a/core/flyout_vertical.js#L90) seems to be set properly.
contentTop in the horizontal flyout uses 0, however that seems correct for that use case.
@rachel-fenichel feel free to reopen if I missed something
