### ISSUE TITLE
Drag connected inmovable block with parent movable block

### ISSUE THREAD

**Issue by radovan76** [google/blockly#3521]
**Is your feature request related to a problem? Please describe.**
I have connected blocks in toolbox, where child block is unmovable and parent movable (I want to disallow to disconnect them). It is possible to drag them to the workspace by dragging by mouse on the child block, but it is not possible after placing to the workspace (mouse is not moving group, but workspace).

**Describe the solution you'd like**
Allow to drag inmovable block which is child of a movable blok. Move it with the parent block (like you drag parent block with child)

**Describe alternatives you've considered**
Another way, how to disallow disconnection of child block.

**Comment by moniika** [comment]
You should be able to move the block group by dragging the parent block (which is not movable), but making the immovable block able to be dragged is not something we would want to support (immovable blocks should not be able to be moved directly).

The alternative you suggested, adding a feature to disallow disconnection of a child block and override the behavior on drag of that child block so that it drags the whole group connected to the parent could work.
Since there is a workaround (you set child to immovable and drag parent) and we haven't seen high demand for this, it isn't a feature we are likely to prioritize for now.

**Comment by rachel-fenichel** [comment]
I see two cases for requesting a child block that can't be removed or disconnected, and which drags the parent around.

The first case is when you want to ensure that the input on the parent is always filled. In this case, a shadow block gives the desired behaviour.

The second case is when you want those two blocks *in particular* to be connected, and to never delete or remove the child block. In that case it's better to have a single block that represents both the parent and the child, rather than expressing it as two blocks.
