### ISSUE TITLE
[Help needed] How to get a variable inside a block accessible in other blocks in workspace

### ISSUE THREAD

**Issue by gomathykailas** [google/blockly#356]
Hi,

I am new to Blockly , I am facing a problem in blockly variable accessibility.

I have an array inside my **generator** code in blockly block named '**operation**' like this:

_Blockly.JavaScript['**operation**'] = function(block) {
for (var x = 0; x < blocks.length; x++) {
if (func.type == Blockly.Msg.constant) {
 **varnames**[i] = block.getFieldValue('datatype');
.....
}_

I want this array **varnames** **outside this block **  in another block called  **'constant'**  like this:

_Blockly.JavaScript['**constant**'] = function(block) {
// need to access **varnames**
}_

so that I can read **varnames** in **constant** block.

Please help me with solution to access variables outside a Blockly block.

Thanks in advance

**Comment by NeilFraser** [comment]
First, I recommend posting questions like this to the Blockly Google Group rather than filing an issue.  There are more people who can help there.

As to this issue, why not just use a global?
```
window.varnames[i] = block.getFieldValue('datatype');
```
Then in your constant block:
```
alert(window.varnames[i]);
```
This code assumes you set `window.varnames = [];` at the start of execution.
