### ISSUE TITLE
Probably bad event order in createBlock

### ISSUE THREAD

**Issue by radovan76** [google/blockly#3584]
**Describe the bug**
When I create Block with side effect of creating nonexisting variable, mirroring is not functioning properly due to bad order of Create and VarCreate events.

**To Reproduce**
1. Define block with variable field and put it into toolbox
2. Move it to the workspace
3. Nonexisting variable is created as side effect of creating block
4. Fired events in this order: BLOCK_CREATE, VAR_CREATE (in Blockly.Flyout.prototype.createBlock)
5. Due to first event is created block  on mirrored environment - side effect is creating new nonexisting variable.
6. Due to second event is created new variable, but it was created in 5. => error

**Expected behavior**
In mirrored environment is variable created before the block, so it is existing before block creating and has not attempted to create is as side effect.

**Additional context**
If You swap:
`Blockly.Events.fire(new Blockly.Events.Create(newBlock));
`
and: 
```
for (var i = 0; i < newVariables.length; i++) {
  var thisVariable = newVariables[i];
  Blockly.Events.fire(new Blockly.Events.VarCreate(thisVariable));
}
```
All is ok.

Or do not disable events when creating block and do not test for newly created variables. Only set event group before creating block. It would be clearer in my opinion (but I don't know about another effects).

**Comment by samelhusseini** [comment]
I was unable to reproduce the issue described here using your repro steps. I can see in the console that createVariable is called twice, but if the variable already exists it would just return that variable and not create a duplicate one. (Not sure if that's an issue).

I did come across a different issue: https://github.com/google/blockly/issues/3593, maybe that's what you were describing?

If not, could you please elaborate on the repro instructions and perhaps use the built-in Blockly blocks as examples. Screenshots would be helpful too.

**Comment by radovan76** [comment]
I think this is different issue. 
It is not problematic in mirroring example, because new variable is tested for same name & type before testing id. I have tests before calling createVariable, so I had error. But attempt to call createVariable twice for same id is nonstandard in my opinion.
And this order of events is problematic also in undo. If You create "i" block in mirroring example and call primaryWorkspace.undo() in console:
At first is fired variable deletion => Block is deleted during variable deletion
At second is fired block deletion, but block is not exist already => see warning in the console "**Can't uncreate non-existent block**"

If You swap it, undo will be without warning (did not try, but I am almost sure).
 
But better could be during block creation to: set group, no disable events and delete variable map comparison. I don't know why is it made by this complicated way.

**Comment by radovan76** [comment]
A similar routine is in `Blockly.Xml.domToBlock` but in good order of events.
Events are disabled during block deletion too, thus when anybody deletes variable in `block.dispose`, event is not fired (have to enable events before and disable after variable deletion).
Events are disabled probably because the whole block tree with children and values is stored in the event after creation/deletion. But when is something changed outside the block tree during block creation/deletion, it is not recorded.
Wasn't it better to leave events enabled and delete all block+change events with blockId from deleted/created tree after the creation/deletion? I suppose, that they are fired later, so they can be deleted before they are fired.

**Comment by maribethb** [comment]
After some investigating, it does seem like the Block Create event should come after the VarCreate event(s). In fact, in xml.js this is how it's done and there is even a comment saying so:  `// Block events come after var events, in case they refer to newly created variables.`

I think this can also be seen just by dragging a for loop out of the flyout and then undoing it. You'll see a console warning about deleting a non-existent block. This is because when you drag the block out, currently the events are:
1. Create block
2. Create var

So when you undo, the order is
1. Delete var
1a. all blocks that use the variable are disposed while deleting the variable. in this case it's a newly created variable, the block we just dragged out is the only one using it, so it is deleted without asking the user
2. Delete block
well, it's already been deleted so now we throw that warning. 

Swapping the order solves this problem because now we delete the block first when undoing.

I haven't tested with mirroring, but I have a change I will prepare early next week that addresses this, and I will try to test it using your repro steps as well.
