### ISSUE TITLE
Can't hide contextMenu options of variable block

### ISSUE THREAD

**Issue by gomathykailas** [google/blockly#361]
Hi,

Context menu's **Rename variable** and  *_New variable *_ can't be removed from variable block.

I have a scenario in a custom block, where i want to hide Context menu's of variable block.

The **variable_get** block looks like this below:

_Blockly.Blocks['variables_get'] = {
   init: function() {
    this.setHelpUrl(Blockly.Msg.VARIABLES_GET_HELPURL);
    this.setColour(Blockly.Blocks.variables.HUE);
    this.appendDummyInput().appendField('column-name')
        .appendField(new Blockly.FieldVariable(
        " "), 'VAR');
    this.setOutput(true);
    this.setTooltip(Blockly.Msg.VARIABLES_GET_TOOLTIP);
   **this.contextMenu = false;**
  }
}_

I have tried setting contexMenu as false , but the result is that the options like **"Duplicate" , "Add Comment" ,"Collapse Block" , "Disable Block" ,"Delete Block" ,"Help","Create 'set assets' "**  will be hidden when we right-click the variable block are removed from view.

I have attached screenshot of that below:
![screenshot from 2016-05-06 10 43 46](https://cloud.githubusercontent.com/assets/13237259/15068893/da5c730e-1397-11e6-84ce-781672eada36.png)

What I want is to hide **Rename variable** and  **New variable** from variable context menu.
I have attached screenshot of that below:

![screenshot from 2016-05-06 10 38 53](https://cloud.githubusercontent.com/assets/13237259/15069382/d71f4330-139a-11e6-9614-7fb84b7013d9.png)

In the above screenshot , we can see set item to variable , along with **Rename variable** and **New variable**. 
What i want is to remove those menus **Rename variable** and **New variable** from variable.

My original snerario is like:

I have a Blockly custom block named operation_block to define **operand** and also a **variable-name** for that operation block.

I used **field variables** for both **operand** and **variable-name** for the above custom block.
I want the context menus( **Rename variable** and **New variable**)  to be hidden in case of **operand** while context menus should be displayed in case of **variable-name**.

I think these context menus are added in blockly-compressed code.I found this while debugging the variable block.

**Please find me find the solution to hide/unhide the context menus appropriately according to scenarios.**

**Comment by rachel-fenichel** [comment]
The original poster has probably moved on, but here's an explanation for anyone else with the same problem.

The *context menu* refers to the menu that appears when you right-click on that block.  That includes options like "Duplicate" and "Delete Block"

The "Rename variable" and "New variable" options are part of the dropdown menu in the variable field, rather than the context menu.  FieldVariable extends FieldDropdown, so it has an array of options that it displays when clicked (see the [documentation](https://developers.google.com/blockly/guides/create-custom-blocks/dropdown-menus) for more details).

The array of options is returned by `Blockly.FieldVariable.dropdownCreate`.  That function adds every existing variable in the workspace, plus options for rename and delete. 

This behaviour is built into the Blockly library.  Showing certain options only some of the time, and depending on which variable is being shown, is not a built in behaviour.  A developer would need to modify or extend the FieldVariable class with a `dropdownCreate` function that contains any additional logic that they want.
