### ISSUE TITLE
CSS in readonly Blockly instances no longer apply.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#3624]
Here's one of the help dialogs in Blockly Games Pond:

<img width="582" alt="Screen Shot 2020-01-21 at 14 14 19" src="https://user-images.githubusercontent.com/250480/72848014-871f8580-3c58-11ea-9177-a2a6f82c28bd.png">

Current develop, used to work fine.  No errors on the console.  Both compiled and uncompiled.

**Comment by moniika** [comment]
After looking into bug, looks like a blockly-games specific issue.
The blocks in the help text are not read-only Blockly, but are svgs.

The issue was that the html elements are missing the css class "geras-renderer", which caused the css rules provided to specific to the geras renderer to not be applied. A PR is in progress to fix this problem.
