### ISSUE TITLE
"Zelos" the List field is not aligned properly

### ISSUE THREAD

**Issue by GAUTAMRAJU15** [google/blockly#3662]
***I was going through toolbox and i found that **LIST** and **TEXT**  has some misaligned field***

The ***create list with*** and ***create text with*** inputs are not properly aligned, as external inputs

**To Reproduce**

1. Go to 'Toolbox'
2. Click on 'TEXT'
3. Scroll down to 'create text with ' block

**Expected behavior**
Should have properly aligned fields in one straight line

**Screenshots**

<a href="https://ibb.co/rMJVFTp"><img src="https://i.ibb.co/rMJVFTp/misaligned.png" alt="misaligned" border="0"></a>
<a href="https://ibb.co/H7Nk5Rb"><img src="https://i.ibb.co/H7Nk5Rb/TEXTBUG.png" alt="TEXTBUG" border="0"></a>

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : chrome
 - Version latest

**Comment by samelhusseini** [comment]
The problem here is the zelos takes inputsInline: false and creates new rows, but aligns rows the same way it would had they beed on a single row. That means the default is left aligned. Visually if we think about external inputs as separate rows, their alignment is right by default.
So there are two ways to get deal with this:
- Make it so the alignment is right aligned by default for additional rows created in zelos when inlineInputs: false.
- Update the block definition for create text and create list to setAlign(right) for its value inputs.

@rachel-fenichel thoughts?

**Comment by GAUTAMRAJU15** [comment]
i think that ***create list with*** and ***create text with*** are just any blocks just like other , and we have the option to modify it with the methods available (e.g. setAlign() ) , i would go for second option , but let's discuss about both

**Comment by rachel-fenichel** [comment]
I prefer updating the block definitions.
- We already have the API to do it
- It's the simplest solution
- If a developer doesn't get the new block definitions, their blocks will still be fully functional

**Comment by GAUTAMRAJU15** [comment]
i agree @rachel-fenichel

**Comment by samelhusseini** [comment]
Fixed.

**Comment by GAUTAMRAJU15** [comment]
actually i am using
```https://blockly-demo.appspot.com/static/blockly_compressed.js```

but this change is not being reflected ? :(
the link is not updated ?

**Comment by alschmiedt** [comment]
We have yet to push our release to https://blockly-demo.appspot.com. It should happen later today and I will send out a post on the [forum](https://groups.google.com/g/blockly) with more information once it has been updated.
