### ISSUE TITLE
Feature request: Collapsing/expanding blocks

### ISSUE THREAD

**Issue by mikij** [google/blockly#368]
Hi everyone, I'm searching for possibility of collapsing-expanding a some type of block like statement input. This could be helpful in some situations and it will mimic folding feature we have in text editors. Is this feature planned maybe, because I can't find any todo list for this project anyway?

**Comment by NeilFraser** [comment]
Is this not already implemented?  Right-click on a block and choose
"collapse".

Send (awkwardly) from an Android phone.

**Comment by mikij** [comment]
Well which example I should use to see collapse on right click? Right now I have only options like duplicate, external inputs, delete and help or in my case where I made custom elements all these except external inputs. Thanks for your reply anyway.

**Comment by NeilFraser** [comment]
If you don't have categories in your toolbox, add 'collapse: true' to the configuration options:
https://developers.google.com/blockly/installation/overview#configuration

**Comment by mikij** [comment]
Thank you man it is working now. Can you tell me one more thing? Is it possible to put some button on block instead of right click to initiate menu to be able to collapse-expand? Or to assign some mouse event like double click on block if this first case can not be applied.

**Comment by mikij** [comment]
And what happens if I have categories in toolbox? Will I be able to collapse-expand blocks in that case?

**Comment by NeilFraser** [comment]
You could program a new type of icon (like mutator, comment or warning) that triggers a collapse or expand.  But one of our design goals of Blockly is to create something that does _not_ look like the bridge of the starship Enterprise, with hundreds of buttons everywhere.

You can have (or not have) categories, there's no problem.  It is just that some of the more advanced options (collapse, comments, scrollbars) default to off if there are no categories (since these are typically simpler applications) and default to on if there are categories (since these are typically complex applications).  As you saw, you can always override the default behaviour.

**Comment by alexNecroJack** [comment]
Hey, I'm just leaving a comment here for anyone coming from Google, looking for a feature "(Un-)Fold All",
because my way of finding it had quite some guessing, I didn't find it in the guide.

```
function foldAll (fold = true) {
    // let workspace = ....; //Assign the Workspace which you are supposed to have stored somewhere on Blockly Injection
    workspace.blockDB.forEach(block => block.setCollapsed(fold))
});
```

This approach is for ALL blocks. If one want's only top level, property topBlocks should be used instead.

Actually it can be found here: https://developers.google.com/blockly/reference/js/blockly.block_class.setcollapsed_1_method.md
But you know, the Search at the reference does not point you to "Block" so you have to guess that too, or read the whole Reference... not good.

**Comment by alexNecroJack** [comment]
@BeksOmega , here are some printscreens, I'm not sure it's what you asked for.
Also, expand / fold would be EXTREMELY useful to add as search tags if possible (for indexing). Maybe it would be enough to mention them in the text? Anyhow.
![image](https://user-images.githubusercontent.com/16266778/221981573-f3447dd4-1132-4386-bba0-191f60ddc72c.png)
![image](https://user-images.githubusercontent.com/16266778/221981585-5f01c054-8688-4027-ba35-8e76779198f7.png)

I should not forget to mention: THANK YOU ALL!
For this AMAZING tool you build!!!
<3
