### ISSUE TITLE
Adding shadows to "any" inputs makes that input only accept the shadow output type

### ISSUE THREAD

**Issue by AlexejheroYTB** [google/blockly#3737]
**Describe the bug**

Adding shadows to inputs which accept "Any" makes that input only accept the output type of the shadow (clearly not intended, block looks like it's supposed to connect, but snaps back)

**To Reproduce**

1. Add the following to the toolbox:
```xml
<block type="logic_compare">
  <value name="A">
    <shadow type="text"></shadow>
  </value>
  <value name="B">
    <shadow type="text"></shadow>
  </value>
</block>
```
2. Add a `logic_compare` block to the workspace somewhere where it's enabled
![8AyUtLo21R](https://user-images.githubusercontent.com/32238504/76468605-075e9d80-63f5-11ea-95d1-e8eb15cf27cd.gif)
3. Try to override the shadow with a block of another output type and see what happens
![pogQZTGvyh](https://user-images.githubusercontent.com/32238504/76468834-92d82e80-63f5-11ea-821b-5cf8abe1e462.gif)

**Expected behavior**

The shadow should be overridden 

**Version**

Using `master`

**Comment by BeksOmega** [comment]
I think this has to do with the logic_compare block in particular. It has a [change listener](https://github.com/google/blockly/blob/9a466fe212db47faba8a8bb36ff20e12aa4d27dc/blocks/logic.js#L541) that forces the types on the different inputs to be the same. And because your shadows are text blocks, the number block is not compatible.

Based on https://github.com/google/blockly/issues/1408 this is the desired behavior :/

**Comment by AlexejheroYTB** [comment]
Okay, thank you.
