### ISSUE TITLE
Extra padding on some dropdown fields on ios

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3782]
**Describe the bug**
There is extra padding on top of the = on the logic_boolean block. I've looked at other dropdown fields and they don't seem to have the same problem. They have a bit of extra padding, but not as much (or maybe not as noticeable) as the logic boolean block.

**To Reproduce**

1. Go to Safari on iOS
2. Click on Logic category
3. Observe the extra padding on the logic_boolean block

**Expected behavior**

**Screenshots**
Master:
![IMG_0114](https://user-images.githubusercontent.com/23059043/78058586-60a75600-733d-11ea-9594-f262639148ff.PNG)

Develop:
![IMG_0113](https://user-images.githubusercontent.com/23059043/78058591-6309b000-733d-11ea-981a-8402b7280f46.PNG)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
 - Device: iPad and iPhone
 - OS: iOS
 - Browser: safari

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by samelhusseini** [comment]
Looked into this, and it all has to do with the text height calculation per platform: 
With out default font styling: sans-serif, 16px, normal. Text height calculations are: 
- Chrome: 16
- Safari: 17
- Firefox: 15
- IOS Safari: 19
- Android (Pixel 4): 17
- IE 11: 17

I think this is an okay side effect as we need to respect the browsers pixel height calculations in order to ensure things appear pixel perfect when sizing a widget div for a text input perhaps.

Also not by using ``sans-serif`` as our default Blockly font. we're deferring to the specific platform to use which ever default sans serif font it wants. In the case of IOS 13, that's SF Pro.

**Comment by samelhusseini** [comment]
I'm happy to close this as won't fix. I'll defer to you @alschmiedt to close unless you have other questions.

**Comment by alschmiedt** [comment]
No other questions. That makes sense to me.
