### ISSUE TITLE
Close the Mutator dialog bug

### ISSUE THREAD

**Issue by yanyusanqian** [google/blockly#3865]
Hi

**I can't close my mutator dialog with outside click after drag mutator blocks.** 

**To Reproduce**
I added this code to the program to close the mutator dialog each time i click outside the box.
```javascript

var mutatorID = "1";

var myUpdateFunction = function(event) {
    if (mutatorID == "1" && event.type == Blockly.Events.UI && event.element == 'mutatorOpen') {
        mutatorID = event.blockId;
    } else if (mutatorID != "1" && event.element != 'mutatorOpen' && event.element != "mutation") {
        workspace.getBlockById(mutatorID).mutator.setVisible(false)
        mutatorID = "1";
    }
}
workspace.addChangeListener(Code.myUpdateFunction);
```
But this method only closes the mutator dialogs when I don't do anything with the mutator, such as drag blocks in mutator dialog. It doesn't seem to receive a click event after the `event.element` becomes `mutation`.
So I asked questions on the mailing list.  Then I was told it might be a bug.
This is the question link. Someone demonstrated the detailed process.>>>>>>https://groups.google.com/forum/#!topic/blockly/QCWU89pe4Os
Could you please tell me if this is a bug? Then how can I fix it?

Thanks ! 

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [3.20200123.1]

**Comment by rachel-fenichel** [comment]
There's definitely a bug with the event generation that's making it not emit the next click event.  We've added it to our bug list for the Q2 (end of june) release.

**Comment by samelhusseini** [comment]
Two events missing there: 
- [ ] When the user sets focus on the mutator, the block is de-selected from the main workspace but we're not firing a "deselect" UI event.
- [ ] When the user sets focus back on the main workspace, after having focused on the mutator workspace, the block currently selected on the mutator workspace is de-selected, again we're not firing a "deselect" UI event.

**Comment by alschmiedt** [comment]
Looking into this more, I am not entirely sure this is a bug. In both cases the event is getting dispatched on either the mutators workspace or the flyout's workspace. Since we do not have a 'deselect' event and are just using the 'select' event I think the behavior makes sense (even if it is a bit strange). 

In the first case, this only happens if someone clicks on a block in the mutator's flyout. Since we don't have a deselect event the 'deselect' of the block on the workspace is lumped with the select event of the block on the flyout. ex: Event (newId: new block on flyout, oldId: old block on ws)

In the second case, since we are clicking on the main workspace and not selecting a block the event is dispatched on the mutator workspace. 

I'm not sure it makes sense to dispatch these events on the main workspace. However, that does fix the problem. 

It also seems like fixing both these cases will not completely fix this use case. If you click on a block in the flyout and then delete it nothing is selected in the mutator and so no deselect event can be fired.
![69534f69-aaa1-42eb-a0dc-c0e65739a4a5](https://user-images.githubusercontent.com/23059043/84088830-525f6100-a9a2-11ea-8512-8b3e19518c69.gif)
I think we might want to instead consider making the correct APIs on workspace/block public.

**Comment by alschmiedt** [comment]
Closing this in favor of #3947 to create a better API for closing the mutator, and #3946 to create better documentation for how to listen to events on all workspaces.

**Comment by alschmiedt** [comment]
@yanyusanqian, just FYI there is a way to do this with the upcoming release (scheduled for the end of this week), but the design will probably change in our next release so you might need to update then as well. More information can be found [here](https://github.com/google/blockly/issues/3975#issuecomment-647747046).

**Comment by yanyusanqian** [comment]
Thank you very much！I will remember to update the code.

**Comment by luddilo** [comment]
> @yanyusanqian, just FYI there is a way to do this with the upcoming release (scheduled for the end of this week), but the design will probably change in our next release so you might need to update then as well. More information can be found [here](https://github.com/google/blockly/issues/3975#issuecomment-647747046).

I'm trying to understand what this workaround would be - i.e how to do this in the recent release. Could you please shine some (more) light on this @alschmiedt ?
