### ISSUE TITLE
Modal window instead of window.prompt

### ISSUE THREAD

**Issue by MarkusBordihn** [google/blockly#393]
Renaming and creating variables is using the window.prompt function.
In some envoriments it would be better to use and modal window / custom function instead.

The best example are Chrome Extensions / Chrome Apps which are blocking window.prompt.
If this would be fine I could prepare an CL for supporting something like this.

**Comment by carlosperate** [comment]
I would welcome this as well, I went the same route than the espruino webide and ended up with a "new variable" option that generated a new variable name automatically rather than prompting the user. So a proper async solution would be great.
https://github.com/carlosperate/ardublockly/commit/544cdb941949185121b82f0f98df0449ddd54f25

**Comment by MarkusBordihn** [comment]
@carlosperate 
Thanks for the details, the change #396 works fine for my use-case.
Would be great if you could check if this works for your use-case as well or if we should adjust this further.

**Comment by NeilFraser** [comment]
Issue #446 should take care of this (and fix a ton of other problems at the same time).
