### ISSUE TITLE
Trashcan Fires Workspace Click Event

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3975]
**Describe the bug**

If you click on the trashcan to open it a workspace click event is fired. Not sure if this is the way it should work or not.

**To Reproduce**
1. Turn on event logging.
1. Delete a block.
3. Click on the trashcan to open it.
4. Observe the fired click event.

**Expected behavior**

Probably shouldn't fire an event? Although in the case of closing mutators maybe it should fire. I'm not sure.

**Comment by alschmiedt** [comment]
Hey, thanks for bringing this up!

Looking into this a bit more I think we are going to end up changing to a design that supports clicking on multiple elements on the workspace, including but not limited to a block, field, workspace, and trashcan. We think this will probably look like a UI event that has a ‘click’ type and would have more information on what element was clicked. This would either be in the form of the source element or a string that describes the element. 

Since we try to limit this week to testing and major bug fixes we aren’t going to be including it in this release, but will implement something like the above design for next release.

**Comment by moniika** [comment]
Closing this issue as trashcan no longer fires workspace click event and filing new bug to track firing of event for closing trashcan flyout #4033

**Comment by alschmiedt** [comment]
#4306 re opens this since it was causing #4303.

When this is looked into the test for "Click with contents - fires trashcanOpen" should also be looked into.
