### ISSUE TITLE
Allows flyout button callbacks to pass a parameter

### ISSUE THREAD

**Issue by seldomU** [google/blockly#4027]
**Problem**
I'd like to add a help-button to my toolbox categories. When pressed, the app should show help content for that category. Currently that requires defining a callback along with each button. I'd prefer if toolbox category authoring had not to be mixed with writing code.

**Suggested solution**
Allow the flyout button callback to pass an argument. That way, my app could provide a function `openDocs( categoryId )`, which the buttons would use as callback. Toolbox authors could then stick to editing XML and whatever format the help content has.

**Comment by samelhusseini** [comment]
Adding a `callbackArg` would work for your case, but I wonder if we should just surface the entire json object to the developer. That would work for passing in a single value, but what if you needed more than one. Sure you could serialize more than one value in that parameter. Here's an alternative, and let me know what you think of it: 

Instead of adding another callbackarg, what if we left it up to the developer to decide what additional tags they wanted to add to their xml, eg: `<button callbackKey="CALLBACK" text="TEXT" dataPoint="DATA"></button>`.

When the callback is called, it already passes in the entire FlyoutButton object, so all we'd have to do is surface that json info object. ie: 

In the constructor of FlyoutButton:
```js
  /**
   * The JSON specifying the label / button.
   * @type {!Blockly.utils.toolbox.Button|!Blockly.utils.toolbox.Label}
   */
  this.info = json;
```

In your callback method you can then do something like:
```
const CALLBACK = function(button) {
  const dataPoint = button.info['dataPoint];
  ... 
};
```

**Comment by seldomU** [comment]
I prefer your way and was thinking of doing the same thing. In my fork the button class still deals with xml, and I was hesitant about passing the xml object to callbacks. Now that the data is a js object, why not!

**Comment by samelhusseini** [comment]
Fixed.
