### ISSUE TITLE
Cannot re-append a field after Input.removeField()

### ISSUE THREAD

**Issue by mattbishop** [google/blockly#4037]
**Describe the bug**

I have a feature where, given a mutation change, I move an existing field from one dummy input to another. The code looks like this:

```javascript
fromRow.removeField(moveField.name)
toRow.appendField(moveField)
```

I get an exception at appendField() stating the field is already bound to a block. If I add 

```javascript
moveField.sourceBlock_ = null
```

before the append() call, I do not get an exception.

**Desktop (please complete the following information):**
 - OS: MacOS 15.5.5
 - Chrome
 - 83

**Stack Traces**

At the appendField() call I get this exception:
```
Uncaught Error: Field already bound to a block.
    at Blockly.FieldTextInput.Blockly.Field.setSourceBlock (field.js:265)
    at Blockly.Input.insertFieldAt (input.js:105)
    at Blockly.Input.appendField (input.js:77)
```

**Additional context**

Blockly 3.20200625.2

**Comment by rachel-fenichel** [comment]
Thanks for the clear report! The short answer is that `removeField` calls `dispose()` on the field, and reattaching it somewhere else (instead of recreating it) is not safe.

You can see this by checking whether `moveField.disposed` is `true`.

You're still able to use it because you have a handle on it and that's stopping garbage collection, but it's not actually safe or guaranteed to behave. 

I suggest creating a new field instead.
