### ISSUE TITLE
Advanced Playground Not Working On Master

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4074]
**Describe the bug**
Advanced playground is not working on master.

**To Reproduce**
1. Pull from master
2. Try opening the advanced_playground.html
3. Blank purple screen 

**Expected behavior**
The advanced playground should load.

**Screenshots**

**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**

**Stack Traces**

```
Uncaught Error: Error: Extension "test_dropdown_mutator" is already registered.
    at Object.Blockly.Extensions.register
```

```
Uncaught ReferenceError: toolboxCategories is not defined
```
**Additional context**

**Comment by AramNasser** [comment]
On my local machine, advanced_playground.html still shows an empty, purple page. Am I missing something??

**Comment by BeksOmega** [comment]
> On my local machine, advanced_playground.html still shows an empty, purple page. Am I missing something??

Hi @AramNasser! You'll probably have better luck asking this question on Blockly's [email list](https://groups.google.com/g/blockly). The core team tries to keep the github purely developement focused hehe.

I'm not sure what's going wrong with your advanced_playground, but when you post a message on the [mailing list](https://groups.google.com/g/blockly), it might be helpful to include:
1) The steps you followed to get blockly (eg did you install via npm? what order did you install things in?)
2) Any error messages you might be seeing in the browser console.

I think that'll give you the best chance of someone knowing what the issue is =)

Best of luck! --Beka

**Comment by AramNasser** [comment]
Dear Beka,

Thank you very much indeed for your feedback and I am sorry for my
late reply.

Yours sincerely
Aram
