### ISSUE TITLE
Getter for value block output types

### ISSUE THREAD

**Issue by ryandrew14** [google/blockly#4087]
**Is your feature request related to a problem? Please describe.**

When generating code, I have a block with a value input. This value input can take one of four different types, and I want to conditionally generate different code based on which of the four types the value block belongs to.

**Describe the solution you'd like**

A nice function `BlockSVG.prototype.getOutputType` that returns the output type array of a given value block, or null if there's no output.

**Describe alternatives you've considered**

The current method for this is a bit unclear but seems to be using the Blockly.Connection object's `getCheck`. This was tough to figure out and I think it's a little unintuitive to use. I think that another valid solution to my issue would be to make documentation a little clearer for programmatically accessing types.

Another alternative is having a function like `getInputValueTypeMatch` to get the matched types for a given input value.

**Extra context**

Here's a code snippet of this. It's not quite the code generation use case, but rather a programmatically generated dropdown:
```javascript
"options": function() {
        const parent = this.getSourceBlock();
        if (!parent) return DEFAULT_DROPDOWN;

        const objInput = parent.getInputTargetBlock('OBJ')
        if (!objInput) return DEFAULT_DROPDOWN;

        // array of all output types
        const objTypesArray = objInput.outputConnection.getCheck();
        if (!objTypesArray) return DEFAULT_DROPDOWN;

        if (objTypesArray.includes(types.Location)) {
          return TYPES_TO_FIELD_OPTIONS[types.Location];
        } else if (objTypesArray.includes(types.Time)) {
          return TYPES_TO_FIELD_OPTIONS[types.Time];
        } else if (objTypesArray.includes(types.Mob)) {
          return TYPES_TO_FIELD_OPTIONS[types.Mob];
        } else if (objTypesArray.includes(types.BlockObject)) {
          return TYPES_TO_FIELD_OPTIONS[types.BlockObject];
        }

        return DEFAULT_DROPDOWN; // empty dropdown list
      },
```

You can see how this would be a lot cleaner if we had a function for getting a block's output type directly, or even maybe getting the inputValueTypeMatch or something like that. Currently we have to first grab the value block, then get the output connection on that, then use a function `getCheck` to get the entire array of types. 

Notice also that none of these API functions have the word "type" in them, which I found confusing when working with this.

**Comment by rachel-fenichel** [comment]
It looks like there are four issues here:
1. Accessing the output connection is not direct (need to use a few helper functions)
2. The type is not explicit: you have to look at the checks array
3. Connection type checks are described with `getChecks`, not `getType`
4. Documentation was unclear for you

As a start, here's the [type checking documentation](https://developers.google.com/blockly/guides/create-custom-blocks/type-checks).

1 is mostly a convenience issue, correct?

2 is tricky because there is no guarantee that the connection has a single type. It's not that it has an array of available types but transforms into a single type as soon as you make the connection--all of the possible types are still there, as expressed by the checks array.

3 is a naming issue, and probably best clarified more in our documentation. I struggled with this in one of my recent PRs. A connection has a type that indicates its role on the block--previous, next, input, or output. That means type is an overloaded term when you consider both that and the type checking array.

4 is documentation, and I think that's really the best place we can resolve this. What would have made it clearer for you? Was the issue that you did not find the documentation that I linked above, or that it was unclear?
