### ISSUE TITLE
Collapsed block performance

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#4229]
**Describe the bug**

Hidden child blocks of collapsed blocks are being re-rendered when a block is being dragged to connect to it.
This causes unnecessary performance issues.

**To Reproduce**

1. Go to the Blockly playground, and use the Spaghetti option to add a long list of connected blocks to the playground.
2. Click on each of the top level if statements and collapse them.
3. Drag another block and attempt to place it in between these blocks.
4. Notice the lag.

**Expected behavior**

Even though there aren't that many visible blocks, we are still re-rendering the block and all of it's (hidden) children as we drag a block to connect to it.

If we can't easily avoid rendering all blocks (even if they're hidden) on first pass, we can probably skip re-rendering blocks if they're hidden during re-render.

**Additional context**

**Comment by samelhusseini** [comment]
Looks like we used to only re-render child blocks if they're visible, but that changed in https://github.com/google/blockly/pull/3806/files

**Comment by moniika** [comment]
Adding checks for `updateDisabled` significantly improves performance, however lag is still observed.

Possible areas of optimization:
- `Blockly.Block.prototype.toString` - the `opt_maxLength` could be used to only partially traverse the dom tree. Since collapsed blocks do not need the full string, but have many elements in the tree, preventing full traversal would improve performance
- `Blockly.BlockSvg.prototype.moveConnections` - Currently doesn't  (but used to) optimizes by skipping blocks that are children of collapsed blocks (previously the `this.rendered == false` check could find this case, but we no longer set `rendered` to false for children of collapsed blocks)
- `Blockly.InsertionMarkerManager.createMarkerBlock_` - Currently (but used to not) copies over fields on invisible inputs (children of collapsed block) triggering unnecessary `render` calls when the insertion maker is created.

When observing performance issues on collapsed block, lag is observed in cases:

- Dragging a collapsed block over a stack of collapsed blocks (repro steps described in issues description)
- Connecting a collapsed block inside stack of collapsed block

These two cases trigger different code paths.

**Comment by BeksOmega** [comment]
> Blockly.Block.prototype.toString

You may have seen it already, but I optimized this when I added updating collapsed blocks to App Inventor. You can view the optimized function [here](https://github.com/mit-cml/appinventor-sources/blob/48e25212630d2cb201525e01444b4d686bd93e20/appinventor/blocklyeditor/src/block.js#L187). I didn't move it over originally since I didn't know if the improvement in performance would be worth the deterioration in readability.

**Comment by immakermatty** [comment]
Any updates?

**Comment by BeksOmega** [comment]
On master, following the original reproduction steps (inserting a normal block into collapsed blocks) took ~900ms. On develop it now takes ~170ms. ~130ms are dedicated to rendering.

On master, following the additional test case outlined in the above comment (inserting a collapsed block into collapsed blocks) took ~1180ms. On develop it now takes ~350ms. ~300ms are dedicated to rendering.

For all collapsed blocks, I used the top block in the stack produced by the spaghetti test.

The main remaining sink is for script time is `toString`.
