### ISSUE TITLE
Multiple resize event handlers.

### ISSUE THREAD

**Issue by svbatalov** [google/blockly#425]
Blockly commit: c2368107c54e
An `onresize` event handler remains after disposing workspace and another one is added on next `Blockly.inject()` (according to Chrome DevTools). As a result resizing does not work after second `Blockly.inject()`. Resizing works if I remove onresize handler manually before second injection.

Resize handlers still leak in latest commit 04d6d119c076, but this does not seem to affect resizing.

**Comment by picklesrus** [comment]
@svbatalov: just to confirm, you called something like Blockly.getMainWorkspace().dispose() and that's when you expect the resize handler to be removed?

@NeilFraser: What's the expected way to clear up Blockly? We actually seem to be leaving a bunch of event handlers around after calling workspace.dispose()  Most of them are from bindDocumentEvents_ so they don't get re-added and are probably less obvious than resize.  For resize specifically, there's one per workspace, so I could cache the handler in workspace_svg and then remove it when we call dispose.   I hacked this up and it works okay, though it seems a little awkward since the flyout workspaces shouldn't have this.

**Comment by svbatalov** [comment]
Yes, I expect `workspace.dispose()` to remove the `resize` handler since in the current code it is workspace-specific.

**Comment by picklesrus** [comment]
Should be fixed in the develop branch now.

**Comment by svbatalov** [comment]
Thanks!
