### ISSUE TITLE
Punctuation marks not displayed appropriately for the tooltip text while hovering the blocks _RTL all toolboxPositions

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#4305]
**Describe the bug**
Punctuation marks not displayed appropriately for the tooltip text while hovering the blocks _RTL all toolboxPositions

**To Reproduce**

1. Go to 'http://google.github.io/blockly/tests/playgrounds/advanced_playground.html'
2. Click on rtl checkbox under Blockly Playground options on right side
3. Drag a block from flyout and hover on the block for tooltip message

**Expected behavior**
Punctuation marks should be 
**Screenshots**
![image](https://user-images.githubusercontent.com/56336353/93865475-0089df00-fce4-11ea-8d52-780991761910.png)
![image](https://user-images.githubusercontent.com/56336353/93866854-d9cca800-fce5-11ea-9def-ff64ccb73d39.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [ 80.0.1 64bit]

**Comment by moniika** [comment]
After investigating, it appears that this error in punctuation location is caused by the css: `direction: rtl`.
This example is a ltr language using rtl blocks. As rtl blocks were designed to be used with rtl languages (and this css, the punctuation behavior is correct), we may want to consider this as "working as intended".
