### ISSUE TITLE
Blockly Developer Tools - No Preview Displayed

### ISSUE THREAD

**Issue by AgiletechSolutionsLLC** [google/blockly#4339]
I have been working with Blockly for close to a year, and have noticed that over the last few months the Block Preview, in the upper right corner of the following URL is not being generated.

https://blockly-demo.appspot.com/static/demos/blockfactory/index.html

This was working previously, so wanted to open an issue, as the preview is very helpful while designing custom blocks.

Keep up the great work, it is an excellent tool.

**Comment by alschmiedt** [comment]
Hello!

Thanks for the issue. Someone also reported a bug on the [developer forum](https://groups.google.com/g/blockly/c/Jm4_bSpjNes/m/m6HXBZNEBwAJ). There is a fix in develop #4334 and we will be releasing a patch to fix the issue. If what you are referring to is different than the reported bug let me know so that we can look into it as well. 

Cheers,
Abby

**Comment by alschmiedt** [comment]
Hello! This should be fixed with the most recent patch, and blockly developer tools has been updated: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html
