### ISSUE TITLE
How to dynamically generate dropdown options?

### ISSUE THREAD

**Issue by theonlygusti** [google/blockly#4606]
**Where**

https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/dropdown#dynamic_dropdowns

**What**

  
- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

> A dropdown can also be provided with a function instead of a list of static options, which allows the options to be dynamic. The function should return an array of options in the same `[human-readable-value, language-neutral-key]` format as static options. Every time the dropdown is clicked the function is run and the options are recalculated.

**Suggested content**

> A dropdown can also be provided with a function instead of a list of static options

How to do this?

**Additional context**

  
Please could you show me how to make the dropdown call a custom function to generate its options, every time the dropdown is clicked.

**Comment by alschmiedt** [comment]
Hello!

You can pass a function into the Blockly.FieldDropdown in order to create a dynamic dropdown. I think the example that you pointed to above shows this, but let us know if there is anything we can do to make it more clear. There are more examples in [this file](https://github.com/google/blockly-samples/blob/2375735a192ba713af812424cf4071fd896f5029/plugins/block-test/src/fields/dropdowns.js#L403).

In the future, if you have a question on how to use Blockly please use our developer [forum](https://groups.google.com/g/blockly). This give others a chance to answer your question and benefit from the answers you receive as well. 

Thanks!
