### ISSUE TITLE
Immovable blocks can no longer be edited.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#473]
This change by @drigz broke the ability to edit fields on a block that can't be moved:
https://github.com/google/blockly/commit/2dcb6cb68b199b45fbe5f84f65f5734fc19e7605
As a consequence, none of the dropdowns on the root block of the [Block Factory](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html) are usable.

Steps to recreate:
Go to Playground and import this XML:
`<xml><block type="logic_compare" movable="false"></block></xml>`
Note that the dropdown is unusable.

**Comment by drigz** [comment]
If you'd prefer to roll-back instead of fixing live, it's probably easiest and safest to change [isDragging](https://github.com/google/blockly/blob/c9437ec7c473e96178535076fe848f1ad1727645/core/workspace_svg.js#L721) to ignore isScrolling, as that won't conflict with the later changes to code using isDragging.
