### ISSUE TITLE
Bad paths of dependencies in `blockly_uncompressed` / `test/deps.js` under Windows

### ISSUE THREAD

**Issue by seldomU** [google/blockly#4762]
blockly_uncompressed.js contains lines like this:
```javascript
goog.addDependency('../../C:/myBlocklyPath/core/blocks.js', ['Blockly.Blocks'], [], {});
```

Which makes the playground unusable. Compressed builds work correctly. I believe this problem has been existing for a while.
The file was generated under windows 10 with `gulp buildUncompressed` on the master branch, commit from March 31, SHA 4be82c0b30

**Comment by seldomU** [comment]
Since the problem is internal to closure, I could only add a sort of band-aid in build_tasks.js buildUncompressed()

Before:
```javascript
    const addDependency = closureDeps.depFile
        .getDepFileText(closurePath, deps)
        .replace(/\\/g, '\/');
```

After:
```javascript
    const addDependency = closureDeps.depFile
        .getDepFileText(closurePath, deps)
        .replace(/\.\..*core/g, '../../core')
        .replace(/\\/g, '\/');
```

**Comment by cpcallen** [comment]
You should check if this issue still exists in the goog_module branch, which uses a new mechanism (`closure-make-deps`) to generate the dependency info, which is now written to `test/deps.js` instead of `blockly_uncompressed.js`; see #5019.

**Comment by cpcallen** [comment]
A commit in @himanshujaidka's PR #5407 [has added lots of DOS file paths in  `test/deps.js`](https://github.com/google/blockly/blob/0c65792284f79b7ebf70bc093fad27c62b32dc10/tests/deps.js), making it reasonably clear that this bug still exists in the revised dependency generation mechanism now used in `goog_module`.

I'm going to mark this for re-triage, since I think that not being able to update deps on Windows is not a great situation and might merit a slightly higher priority.

**Comment by gonfunko** [comment]
Closing as obsolete since we're no longer using Closure and have #5000 to track general build issues under Windows.
