### ISSUE TITLE
Can I provide an interface to directly obtain the fast overall configuration of JSON

### ISSUE THREAD

**Issue by PaulMing** [google/blockly#4795]
We need the overall configuration item of JSON instead of a single parameter

**Comment by alschmiedt** [comment]
Hello!

I'm not entirely sure what you are asking here, but I think it is a question and so would be better if it was asked on the [forum](https://groups.google.com/g/blockly?pli=1) with an example of what you are looking for. If this is a feature request, please explain your problem and the solution that you would like preferably with examples. I'm going to close right now because I believe this is a question, however feel free to respond if it is a feature request and I can re open.

Thanks!

**Comment by PaulMing** [comment]
How to get block JSON configuration  @alschmiedt 

Solution: whether we can provide an interface to directly obtain the fast JSON configuration, we need to obtain the fast JSON configuration, and then carry out subsequent operations
