### ISSUE TITLE
Invalid connections in XML results in hidden block

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#4803]
Go to the playground https://blockly-demo.appspot.com/static/tests/playground.html and paste this XML:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="math_trig">
    <value name="NUM">
      <block type="text"></block>
    </value>
  </block>
</xml>
```
This is a 'sin' math block that has a text block connected to it.  This isn't legal and Blockly could never generate this.  When this illegal XML is imported, only the 'sin' block appears on the workspace.  This is a perfectly acceptable result (amongst others, such as displaying the block disconnected, or (worst case) throwing a fatal error).

However, the text block did get created.  It's hiding invisibly on the workspace.  You can verify this by right-clicking on the workscape and noting that it's offering to "Delete 2 blocks".  Also, if you export to XML you'll see the text block at the top level.

**Comment by jschanker** [comment]
Haven't investigated the reason for this, but this may be related.  Importing the following XML causes a prompt block to be hidden behind a text block until you drag it.  After dragging the text block, the prompt block appears and the two move together since they're connected but it renders with space between the two.  The issue is a prompt for NUMBER with message can't be an input block for text in a find first occurrence of block.  Calling `workspace.render()` fixes the issue.

```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="text_indexOf">
    <field name="END">FIRST</field>
    <value name="VALUE">
  <block type="text_prompt_ext">
    <mutation type="NUMBER"></mutation>
    <field name="TYPE">NUMBER</field>
    <value name="TEXT">
      <shadow type="text">
        <field name="TEXT">abc</field>
      </shadow>
    </value>
  </block>
    </value>
    <value name="FIND">
      <shadow type="text">
        <field name="TEXT">abc</field>
      </shadow>
    </value>
  </block>
</xml>
```

**Comment by BeksOmega** [comment]
In the new JSON serializer invalid connections throw clear errors instead of failing silently. The XML system will not be fixed as it is being iceboxed.
