### ISSUE TITLE
Variable management breaks function parameters

### ISSUE THREAD

**Issue by geppy** [google/blockly#493]
The [variable management branch](https://github.com/google/blockly/issues/446) appears to have broken function parameters.  I can define functions with parameters, but they no longer appear in the Variables flyout.

**Comment by rachel-fenichel** [comment]
Design for function parameters:

- [ ] Adding a parameter through the mutator creates a variable with that name.
- [ ] Renaming a parameter through the mutator (hitting enter/focusing away from the text input specifying the name) creates a variable with the new name *and does not delete the variable with the old name.*
- [ ] Reusing the name of a variable that already exists is allowed.
- [ ] Deleting a variable that is a parameter for a function is disallowed, with an alert saying why.
- [ ] Final wording on the alert TBD.

In order to implement the constraint on deleting variables specified above, we also need to implement @RoboErikG 's suggestion from #446:
- [ ] When deleting a variable, check if it's the last instance.
- [ ] If it's not the last instance ask the user for confirmation and specify how many blocks using the variable will be deleted.

@geppy any of these in particular look interesting to you?

FYI I'll be out next week and won't respond to reviews, but will be back the following week.

**Comment by rachel-fenichel** [comment]
Hi @geppy, 

Have you had a chance to look at this?  And have you found any other issues with the variable management branch?  This is currently the only blocker I'm aware of.
