### ISSUE TITLE
Calling showEditor on a dropdown M times shows the option list repeated M times

### ISSUE THREAD

**Issue by jschanker** [google/blockly#4933]
**Describe the bug**

Calling `showEditor` on a dropdown field M times consecutively results in the dropdown displaying the option list M times.

**To Reproduce**

1. Go to the Blockly playground.
2. Drag in a math_arithmetic block.
3. Enter `workspace.getAllBlocks()[0].getField("OP").showEditor()` multiple types in the Developer console.

**Expected behavior**

The list of displayed options should not be repeated if `showEditor` is called multiple times, consecutively.

**Comment by BeksOmega** [comment]
I don't think we expect showEditor() to be called programmatically by developers because [it is marked as package](https://developers.google.com/blockly/reference/js/Blockly.Field#showEditor) (the references make this hard to notice as well). But I'm still a bit confused about package vs public vs protected wrt what we expect plugins to access, so I'm not sure hehe.

**Comment by moniika** [comment]
For `package` methods, it is true that we don't expect this method to be called outside of Blockly core. So, for that reason I'll mark it as low priority for now.

This is unexpected behavior though, so I'd probably consider it a bug. There may be a check that could be added somewhere to fix this.

**Comment by jschanker** [comment]
Thanks, Beka and Monica!  Definitely overlooked that `@package` tag; I think I just automatically assume intended public when I don't see that trailing underscore.  And yes, definitely a low priority in that case, particularly with what I would imagine is a lot of work before the quickly approaching Q2 release date!

**Comment by jschanker** [comment]
Resolved by #5429.
