### ISSUE TITLE
Error to generate blocks on complex input

### ISSUE THREAD

**Issue by BreakingPanda** [google/blockly#4964]
I noted that Blockly does NOT render a complex combination of `Join` and `Where`. Example:
```
Join(',', Where(['A','B'], x => x != 'C')
```
Which `Where` block should returns a list of `A` and `B` and final result should become `A,B`. If I try to open blockly and set up blocks, it will fail and output render becomes `Join(',',)`.

Expected to construct blocks accordingly and keep rendered expression identical to provided input.

P.S. I lodged #4891 but recieved no respond so I lodge a new one.

**Comment by BeksOmega** [comment]
Hello, thank you for filing this issue :D We definitely always want blocks to render correctly so this is something we want to get fixed. Could you provide some additional information to help us reproduce the issue?

Some things that would be helpful are:
  1) A picture of the bad behavior, so we can know if we've reproduce it correctly.
  2) Your block definitions, or a link to them (eg pastebin, github, etc).
  3) Any errors you're seeing in the browser console. If you're not sure how to open your browser's console you can google "how to open <your browser> console" (it's a bit different for every browser).

I'm really sorry your previous issue didn't get a response :/ There has been a lot of internal stuff happening in the past few weeks, so that's probably what caused it to slip through the cracks. Once we have a bit more information hopefully we can get this sorted out!

Thank you again for filing this! --Beka

**Comment by BreakingPanda** [comment]
Hi Beka,
Thanks for replying. Here is another example to study the bug in more details:
```
Iif([NextAdhocInspection_FormAnswers::InspectionType]='PTSKININSP', 'Skin Inspection', Iif([NextAdhocInspection_FormAnswers::InspectionType]='PTSKINRINSP', 'Skin Reinspection', 'None'))
```

Which simply should return a string. It's a nested `IIF` and when blocks try to render, they fail to render nested `IIF`. In my console, I see no error but many warnings all as of `No message string for %{BLAH_BLAH}.`. Due to error in nested `IIF` in this example, my expression changes to `iif([NextAdhocInspection_FormAnswers::InspectionType] == 'PTSKININSP', '', )`. 

And sadly we have no open repo in GitHub to share. 

![error](https://user-images.githubusercontent.com/16007636/124047447-9282fd00-da57-11eb-9d7c-61e5ac076399.PNG)

_P.S. I'm using Ms Edge browser._

**Comment by BeksOmega** [comment]
Hello,
I'm not sure that we'll be able to help unless we can see the block definitions :/ There are a lot of things that could be causing this issue. For example, the connection checks could be set up incorrectly, some mutators could be encountering an edge case, or maybe an invalid field value is getting assigned somewhere.

I totally get if your block definitions are internal and you're not allowed to share them. In that case, would you be able to create a minimal example (using different block definitions) that reproduces the problem? Before we can try to fix it, we really need to be able to reproduce the issue.

I really want to get this issue fixed! But we just need a bit more info first :/

Oh! and with regard to the `No message string for...` errors, you probably need to include a [language file](https://developers.google.com/blockly/guides/configure/web/fixed-size#injection):
```
<script src="msg/js/en.js"></script>
```

Best =)
--Beka

**Comment by moniika** [comment]
Blockly doesn't provide an API for generating blocks from an expression string.
This seems like it might be a bug outside of Blockly in the code where you construct the blocks from the expression string.

If it is in Blockly, then we can try to help you if you provide us a minimal reproduction sample, as Beka mentioned above, otherwise it's unclear what or where the problem is.
The only suggestion I can think of at the moment to help you with debugging is to look at where you load the Block into the Blockly workspace. I'm making a guess that you generate xml or json after parsing the expression string and load that. You could look at the generated xml/json and see if it is what you expect.

About the console warnings: 
Beka's suggestion about the language file might solve your console warnings, or it might be another instance of an existing bug https://github.com/google/blockly/issues/4369

**Comment by BreakingPanda** [comment]
Hi Beka and Moniika,
As Moniika made a good guess, I create a XML of blocks definitions and then load them into Blockly workspace. So if any of my blocks is wrong, Blockly crashes for me which is obvious.
As my code constructs those blocks, I had to deal with situation where user gives me invalid input. So a simple solution is to better error handle when call `domToWorkspace(...)`.

Thanks for your help. I am closing this issue now.
