### ISSUE TITLE
Values of fields defined in the toolbox should use the message localization system

### ISSUE THREAD

**Issue by ndahn** [google/blockly#4992]
When defining comments or default values for fields in the toolbox definition, e.g. for example programs, these strings will usually be localized to the user's language. However, AFAIK the values of fields cannot be localized. At the very least a description of how this can be done is missing from the toolbox documentation at [https://developers.google.com/blockly/guides/configure/web/toolbox](https://developers.google.com/blockly/guides/configure/web/toolbox).

More specifically, the following was expected to work, but does not:
```xml
<block type="myblock">
    <field name="FIELD_1">%{BKY_MY_VALUE}</field>
</block>
```
This will display `%{BKY_MY_VALUE}` verbatim and not the value defined for `MY_VALUE` as defined in the loaded localization.

**Preferred solution**
To me the ideal solution would be if the above syntax worked, passing the field's value through `Blockly.utils.replaceMessageReferences`. 
Alternatively the field could also accept a `value="%{BKY_MY_VALUE}"` attribute, although this begs the question whether it should override the value between the `<field>` tags or be overridden by it.

**Comment by BeksOmega** [comment]
Hi @ndahn so I brought up your [proposal](https://github.com/google/blockly/pull/5126#issuecomment-883564468) with the team, and one of them mentioned that if all you want to do is localize field values for your custom blocks, you can do that using [JSON block definitions](https://developers.google.com/blockly/guides/create-custom-blocks/localize-blocks). As you can see [here](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/core/field_textinput.js#L112), when fields are created via JSON they do dereference the messages.

But that only solves the problem of fields, and only if you only want to localize values in your custom blocks. Given that, do you think this could work for you?

(sorry for jumping back to your issue rather than your PR, but I want future peeps to be able to find this if it does work for you)

**Comment by ndahn** [comment]
Hey @BeksOmega! Unfortunately field values are not enough, I also need to localize some comments. However, since I'm in full control of my project and aware of the limitations, monkey patching or your suggestion from #5126* work fine for me.

*) convert XML to text, localize text; will result in invalid XML with special symbols like "©" (should be "&copy;")

Should we close this and continue on the PR?

**Comment by BeksOmega** [comment]
> Should we close this and continue on the PR?

I think we can leave this open for now, but definitely continue on the PR :D

**Comment by BeksOmega** [comment]
Closing this because #5238 has more info.
