### ISSUE TITLE
Where is the stable/production version of Blockly?

### ISSUE THREAD

**Issue by bkisdi** [google/blockly#502]
Several contributors work on this project and develop it heavily - which is very good.
But - as the github notifications often say - bugs may occur in new code, even in "master".
Where can I find the stable version of Blockly which is recommended for my production environment? Are there milestones of the project where new code is not inserted until completely debugged?
Thanks.

**Comment by picklesrus** [comment]
master is generally the most stable branch - usually things are committed to develop, then merged into master when they are (hopefully) stable. But, yes, bugs do slip through.
I just took a look over the past few months and it looks like the merge happens ~1/week, though there isn't a definite schedule.

**Comment by NeilFraser** [comment]
One strategy is to look at the master branch and pick a commit that stayed live for a long time (not counting routine updates from Translatewiki).  That's a good indication that it was successful.

But your point stands that as we grow as a project we need to be doing a better job at keeping master stable.  We are currently investigating options for automated end-to-end testing.  Additionally, I propose that we stop accepting any PRs on master (excepting Translatewiki or other obvious safe changes); everything must go to develop first.

**Comment by carlosperate** [comment]
> One strategy is to look at the master branch and pick a commit that stayed live for a long time (not counting routine updates from Translatewiki). That's a good indication that it was successful.

This is actually a slight headache I've had myself whenever I try to catch up. It's hard to identify commits that contain fully implemented stable features. Since the merges from PRs and from the develop branch are not squashed, all the commit history goes into master, and reading that chronologically is not an easy way to understand how some features have been implemented as a whole.

That being said, I quite appreciate the fact that PRs to the develop branch are used properly to encapsulate features and code reviews, so instead I can go through the PR section and see the new changes (or scan through the git history looking for merges). Unfortunately, since everything get's a bit scrambled in the general commit history, that's the only way I have to easily check out the new code, and any commits pushed directly into the branches are likely to get overlooked.
