### ISSUE TITLE
Bug with Precision 0.1 on Numeric Input

### ISSUE THREAD

**Issue by pip8786** [google/blockly#516]
I think there is some sort of bug when inputting numbers where the block is defined to have 0.1 precision. If I enter 2.3, 2.4, 2.8, 2.9 into the block linked below, the resulting value is 2.X0000000000003 or something like that. Seems like a floating point error of some sort, but I haven't dug deeper yet. 

https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#7oz88h

Anyone know a solution to this?

**Comment by rachel-fenichel** [comment]
Definitely a floating point error.  Offending line is https://github.com/google/blockly/blob/master/core/field_number.js#L96:
    n = Math.round(n / this.precision_) * this.precision_;

For instance, 
Math.round(2.3 / 0.1) => 23
23 * 0.1 => 2.3000000000000003

**Comment by rachel-fenichel** [comment]
Since the function returns a string no matter what, I think the correct solution is to use [toFixed](http://www.w3schools.com/jsref/jsref_tofixed.asp).  I need to confirm that this is correct.

Relatedly, we don't actually apply the precision term to the min and max, and we clamp to within min and max after rounding to precision.  This means that you can get a number that doesn't match the precision requirements.  For instance, if precision is 0.1 and max is 100.55555, entering 101 results in 100.55555.

**Comment by pip8786** [comment]
How would you determine the number to pass to toFixed? 

Say the precision is 0.25, would you run it through toFixed(2)? In that case, 0.5 would come out to 0.50. Is that the desired result?

**Comment by AnmAtAnm** [comment]
FWIW: I'm pretty sure Android applied precision to min/max, so that the above scenario would output 100.5.  Sounds like there is a discrepancy.
