### ISSUE TITLE
Coordinates are wrong after mutator is dragged.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#521]
https://youtu.be/lO_lvv0gxbE

**Comment by picklesrus** [comment]
This isn't as simple as I'd hoped. The workspace inside the mutator needs to update its mouse coordinate ->workspace coordinate transformation matrix when it moves. The cases I can think of  are when the parent workspace changes in the following ways:
1. The block it is attached to moves
2. The parent workspace is dragged
3. The bubble containing the mutator is dragged
4. The parent workspace is zoomed.

I added a change listener to the parent workspace and reset the matrix then and that fixes 1, but not the rest since those don't fire events. I could add events for 2, 3, 4 and listen for those.

Or, I could try and figure out a way for the Bubble to communicate to its contents that something has changed and it needs to update itself.

Thoughts?  Perhaps I will try and grab you in person tomorrow to ask your opinion.

**Comment by picklesrus** [comment]
Or, I could also make the mutator listen to more general mouse events...  Something like this: https://github.com/picklesrus/blockly/commit/1e255f1d149935eb3a498089351f25c32fed5d8a

**Comment by rachel-fenichel** [comment]
Fixed in #540
