### ISSUE TITLE
Blockly field_colour widget changes block color - only in Zelos renderer

### ISSUE THREAD

**Issue by markdeloura** [google/blockly#5377]
**Describe the bug**

Using field_colour in a block is a great way to enable the user to choose a color. But if using the Zelos renderer it will also change the block color. Other renderers seem fine.

**To Reproduce**

1. Use the Block Factory
2. Create a block with a dummy input
3. Add the colour field to the dummy input
4. Add text fields with some random text above and below the colour field in order to give the block a little extra width so you can see its color.

**Expected behavior**

The renderer should produce a block with the block's background Hue or Color, and the color chosen by colour field shown in just that inset block. Instead the entire block's color will change based on what is chosen in the colour field.

**Screenshots**

Here's an example block from Block Factory:
![color-block](https://user-images.githubusercontent.com/1282817/129603443-7ff22c11-5c8f-47d5-b7a8-3968e5d56352.png)

It should produce a block like this, and does in non-Zelos renderers:
![blah-color-blah](https://user-images.githubusercontent.com/1282817/129603468-8440daf7-c961-4313-a8c0-7927cbc1191e.png)

In the Zelos renderer it looks like this... two views:
![green-zelos](https://user-images.githubusercontent.com/1282817/129603528-b2ea74f3-c524-4de3-b764-bb5d99f8250a.png)
![zelos-blah-color-blah](https://user-images.githubusercontent.com/1282817/129603559-82fa755a-a162-4df2-a945-be8a593ca17d.png)

It's worth noting that the blend-colour block, which is a standard block, uses a different mechanism for displaying a color picker. It works fine, for cases where you want the user to be able to either pick a color from the field or drag in a variable or other value field to replace the field.
![zelos-blend-color](https://user-images.githubusercontent.com/1282817/129603669-09ca97dc-ad97-4387-810b-7d2738c1c289.png)

**Desktop (please complete the following information):**
 - OS: Win11 Pro x64 22000.132
 - Browser: Firefox x64 92.0b3, Chrome x64 92.0.4515.131, Edge x64 92.0.902.73
 

```
Ignoring non-existent field COLOR in block colour_picker
```

**Additional context**

This message shows up in console no matter what renderer is being used.

**Comment by alschmiedt** [comment]
Thanks for the issue! 

So I think this might be an unfortunate side effect to a zelos specific feature. When we are in the zelos renderer we use [this field](https://github.com/google/blockly/blob/f94b1db85018b5a7261fa01f7d04cd5c8367fe2c/core/renderers/zelos/constants.js#L311) to color the entire block. This is necessary for the color picker block to look like this: 
<img width="82" alt="Screen Shot 2021-08-17 at 4 35 17 PM" src="https://user-images.githubusercontent.com/23059043/129814256-11447ca7-af7e-4a7a-a878-24a5ce597f4a.png">
instead of this: 
<img width="93" alt="Screen Shot 2021-08-17 at 4 37 32 PM" src="https://user-images.githubusercontent.com/23059043/129814273-4f9e9d97-8f06-4fec-b8c5-2ac11ad16c68.png">

The reason the blend colour block you mentioned in your issue works is because the colour field is on its own block that is then connected to the blend block. For your case, we can similarly create a block with an input and add a shadow block to it. This would look like: 

**Block definition**
```
  {
    "type": "colour_test",
    "message0": "Blah %1 Blah",
    "args0": [
      {
        "type": "input_value",
        "name": "INPUT_1"
      }
    ],
    "colour": 230,
    "tooltip": "",
    "helpUrl": ""
  },
```
**Toolbox definition**
```
    <block type="colour_test">
      <value name="INPUT_1">
        <shadow type="colour_picker">
          <field name="COLOUR">#ff0000</field>
        </shadow>
      </value>
    </block>
```

Since this issue has multiple work arounds (use the above solution, subclass the colour field, subclass the renderer) I plan on iceboxing the issue. But let me know if this solution does not work for you and we can take another look : )

**Comment by markdeloura** [comment]
Yup sounds good! I wasn't sure if it was a bug or a feature - I should have dug further into Zelos to be sure but am still a little unsure making my way around the code base. Getting there though! Thanks for your reply!

**Comment by alschmiedt** [comment]
No worries! Also here are some good getting started resources just in case they are helpful!
- [Blockly codelabs](https://blocklycodelabs.dev/)
- [Blockly forum ](https://groups.google.com/g/blockly?pli=1)
- [Plugins](https://google.github.io/blockly-samples/)

**Comment by markdeloura** [comment]
Thank you! I'm making some good progress now and keep referring back to docs and labs and forums - all extremely helpful! At some point I'll summarize on the forums what I've done to get my environment working well enough with Typescript, I had to do some fiddling and continue to learn a lot as I push into more subsystems. :) The worlds of plugins and mixins and mutators currently remain a mystery, but probably not for much longer ;) Thanks for your help!
