### ISSUE TITLE
Undoing a variable rename doesn't work on a parameter definition

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#541]
Steps to reproduce:
- Create procedure with one input (x)
- Drag a block containing x from the flyout (e.g. set x to ___)
- Rename x to y (from the block created in the previous step)
- Note that the procedure's parameter is renamed to y, and that change is reflected in the mutator workspace
- Undo the rename with ctrl-z
- Note that the "set y to" block changed back to "set x to"
- Note that the procedure's parameter is not renamed back to x.

Expected behaviour: Undo undoes parameter renaming as well.

**Comment by vicng** [comment]
Undoing a regular variable rename exhibits a similar problem.

Steps to reproduce:
1) Create a variable named "foo".
2) Drag a "foo" variable block into the workspace.
3) Rename the variable "foo" to "bar".
4) Undo, by pressing ctrl-z. This will set the variable name back to "foo" on the block.
5) Open the variable toolbox. 

Expected behavior:
At the very least, "foo" should exist as a variable in the toolbox.

Actual behavior:
"bar" is the only variable block in the toolbox.

**Comment by marisaleung** [comment]
@rachel-fenichel these bugs have been fixed by commits long long ago. Feel free to close.

**Comment by rachel-fenichel** [comment]
@marisaleung can you verify that they're still fixed and then close this issue?

**Comment by marisaleung** [comment]
Verified! And closing.
