### ISSUE TITLE
Review contents of `utils.js`

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#5428]
`core/utils.js`, which provides `Blockly.utils`.  The contents of `core/utils/*.js` formerly provided leaf modules `Blockly.utils.*`; they have now been migrated to `goog.module` and (provisionally) `declareLegacyNamespace`; ~~this is unfortunately incompatible with having `utils.js` be a `goog.module`~~.

We were considering evacuating and removing `Blockly.utils` entirely, but this is probably not the correct course of action.  Instead, we will probably remove the calls to `declareLegacyNamespace` from `core/utils/*.js` and have this module import and reexport those leaf modules instead.

It would nevertheless be sensible to consider whether any/all of the contents of this module should be moved to other module(s) in any case.

Needs decision:
* [x] `runAfterPageLoad`
* [x] `arrayRemove`
* [x] `getBlockTypeCounts`
* [x] `noEvent`
* [x] `isTargetInput`
* [x] `getRelativeXY`
* [x] `getInjectionDivXY_`
* [x] `isRightButton`
* [x] `mouseToSvg`
* [x] `getScrollDeltaPixels`
* [x] `tokenizeInterpolation`
* [x] `replaceMessageReferences`
* [x] `checkMessageReferences`
* [x] `genUid`
* [x] `is3dSupported`
* [x] `getViewportBBox`
* [x] `getDocumentScroll`
* [x] `screenToWsCoordinates`
* [x] `parseBlockColour`

**Comment by rachel-fenichel** [comment]
Groupings that I see so far:

### Browser events
These take in an `Event` and do some checks or extract some information. I propose that we move these to `browserEvents`

- `isTargetInput`
- `noEvent` -- this is also only used in one place (contextmenu.js, to prevent the system context menu), so maybe just move the definition in there and get rid of this function entirely?
- `isRightButton`
- `mouseToSvg`
- `getScrollDeltaPixels`

### Coordinates
These could go in a new file for coordinate/svg math specifically--or perhaps there's an existing file that they could live in? I would say `Coordinate`, but that's a class. The common thing I see here is that these inspect the dom to figure out where something is/how to compute where something is. There are some regexes that go along with these but can be module-internal in whichever file they end up in.

- `getRelativeXY` -- used quite a bit, depends on the XY regex and on `Blockly.utils.Coordinate`
- `getInjectionDivXY_` -- only used internally
- `getViewportBBox`
- `getDocumentScroll`
- `is3dSupported`
- `screenToWsCoordinates` -- maybe. This one relies a lot on the actual workspace. The other option I see is to move it into workspaceSvg, if we want it to move.

### Messages/parsing
- `tokenizeInterpolation`
- `tokenizeInterpolation_`
- `replaceMessageReferences`
- `checkMessageReferences`
- `parseBlockColour` -- this one is a bit tricky. Everything in `utils.colour` doesn't need to know about blockly stuff; this function does, which is why it lives up a level.

Only two of the functions in this file rely on knowledge of Blockly outside of utils, and both can be handled with requireType. A few others need `Blockly.Msg` and Blockly.internalConstants`, but neither of those will lead to a large dependency tree getting pulled in.
- `getBlockTypeCounts` -- needs a `requireType` for `Block`, but not a full require.
- `screenToWsCoordinates` -- needs a `requireType` for `WorkspaceSvg`, but not a full require.

**Comment by BeksOmega** [comment]
I'll take a stab at the browser events fixes.

**Comment by BeksOmega** [comment]
Grabbing coordinates stuff.

**Comment by BeksOmega** [comment]
I'm moving `parseBlockColour` into `utils.colour` and renaming it to `parseWithHueAndReference`.

**Comment by rachel-fenichel** [comment]
Done!
