### ISSUE TITLE
centerOnBlock centers on stack

### ISSUE THREAD

**Issue by seldomU** [google/blockly#5432]
The workspace method _centerOnBlock_ uses the block's _getHeightWidth_ to calculate its center point, but that returns the size of the block including the stack below it, so the center of the stack is used as focus point. The block that I want to highlight to the user can get moved off screen by this. Using the block's own width and height instead works fine.

To reproduce, load a long stack like this on the playground:
```xml
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="controls_repeat_ext" id="|EJ:%,F@Xek)^?D/MKcJ" x="88" y="63">
    <value name="TIMES">
      <shadow type="math_number" id="4nvyR*s(VEkSM;qF,.}e">
        <field name="NUM">10</field>
      </shadow>
    </value>
    <statement name="DO">
      <block type="text_print" id="tQhTU%5$@Y4K[FCV=QGr">
        <value name="TEXT">
          <shadow type="text" id="0)JyE?fA`SNPe?f8|qM1">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
        <next>
          <block type="controls_if" id="IzY7=mrt)3GJ;MzhWC%8">
            <mutation elseif="20"></mutation>
          </block>
        </next>
      </block>
    </statement>
  </block>
</xml>
```

Zoom in a bit and center on the print block with `Blockly.mainWorkspace.centerOnBlock('tQhTU%5$@Y4K[FCV=QGr')`

**Comment by gonfunko** [comment]
Thanks for reporting this! I agree this behavior is confusing; in the short-term, I've opened https://github.com/google/blockly/pull/5442 to at least clarify the JSDoc. Since this is part of the public API and the existing behavior/name is relied on we don't want to update the method name right now to avoid breaking changes, but will look into addressing this through a rename/introducing a method to center on the block itself in the future.

**Comment by rachel-fenichel** [comment]
After discussion: let's add an argument (`opt_blockOnly` or similar). The default behaviour will be to center on the stack, but it can center on the block if the optional arg is true. That keeps backwards compatibility while making the desired behaviour available.
