### ISSUE TITLE
Simplify globalThis export

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#5506]
Currently (on the goog_module branch) the [Blockly.utils.global](https://github.com/google/blockly/blob/goog_module/core/utils/global.js) sets `exports.globalThis`.  As a result, its users invoke:
 `const {globalThis} = goog.require('Blockly.utils.global');`

Since this util only does one thing, wouldn't it be better to set `exports`, allowing its users to invoke:
 `const globalThis = goog.require('Blockly.utils.global');`

Simplifies the API.  Not a breaking change as long as we make the change before the next release.

**Comment by cpcallen** [comment]
This was in fact exactly what `Blockly.utils.global` did until PR #5451.

It was changed to a named export in part because the style guide says not to use default exports, but more particularly because exporting the global object (`window`) as the default export from a `goog.module` fails because (absent a call to `goog.module.declareLegacyNamespace`) [`base.js` attempts to seal the `exports` object](https://github.com/google/blockly/blob/d79640592f5efdf68a4f53e5c94bdce4365db950/closure/goog/base.js#L1113), and this cases an error to be thrown (at least by V8 in Chrome):
```
> Object.seal(globalThis)
VM103:1 Uncaught TypeError: Cannot seal
    at Function.seal (<anonymous>)
    at <anonymous>:1:8
(anonymous) @ VM103:1
```
(Interestingly enough, in node.js V8 _will_ let you seal the `global` object, and doing so causes any subsequent `var` declarations in the global scope to fail with `TypeError: Cannot add property <name>, object is not extensible`, as one would expect.)

We could leave the `declareLegacyNamespace` call in this one module, or unset `goog.SEAL_MODULE_EXPORTS` to disable sealing more generally, but since we want to get rid of default exports anyway I went with the solution proposed in #5451 as amended by my note in #5503.

**Comment by NeilFraser** [comment]
Thanks for the explanation.
