### ISSUE TITLE
Encountered "Page is unresponsive " often during refreshing/loading the test URL

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#5557]
**Describe the bug**

Encountered "Page is unresponsive " often during refreshing/loading the test URL

**To Reproduce**

1. Go to 'https://google.github.io/blockly/tests/playground.html'

**Expected behavior**
User expects to load the page successfully 

**Screenshots**
![Screenshot 2021-09-28 3 18 29 PM](https://user-images.githubusercontent.com/56336353/135065139-f02e0dbb-b16a-471e-bb7f-22bbe5df3d01.png)

**Desktop (please complete the following information):**
 OS: [ChromeOS]
Browser [chrome]
Version [93.0.4577.85 (Official Build) (64-bit)]

**Comment by alschmiedt** [comment]
Looked into this a bit. This is a known issue with how modules load. The files are now loading synchronously instead of in parallel as they were doing before. `base.js` used to add a script tag to load the file, however now it uses xhr to load the files in [loadFilesSync_](https://github.com/google/blockly/blob/c9329ea8eb39fa9b774ddc915b2357ec5137c6d1/closure/goog/base.js#L1190).

I don't know of any work around for this, and from talking with Chris sounds like there is not one. However, keeping this open because having it take 20 seconds every time we try to refresh a testing page in the future is going to be really annoying.
