### ISSUE TITLE
blockly-demo.appspot.com demo's give 500 for cloud storage

### ISSUE THREAD

**Issue by IBlackI** [google/blockly#5584]
**Describe the bug**

https://blockly-demo.appspot.com/static/demos/ Cloud storage does not work. Gives a popup window with message ```There was a problem with the request.

httpRequest_.status: 500```

**To Reproduce**

1. https://blockly-demo.appspot.com/static/demos/storage/index.html
2. Press save blocks

**Expected behavior**

Blocks would be saved. Blockly Developer Tools is also unable to load / save.

**Screenshots**

![image](https://user-images.githubusercontent.com/4059637/136043098-abe27755-8d06-4d22-b71b-a2715e821ae3.png)

**Stack Traces**

No errors in console

**Comment by NeilFraser** [comment]
This is concerning.  Findings so far:
* Can't create new database entries (as described in this bug, for both code demo and storage demo).
* Can't load existing database entries (Klingon demo: https://blockly-demo.appspot.com/static/demos/code/index.html?lang=tlh#ortpyd).
* App Engine logs do NOT show any 500 errors.  It's as though the requests don't even reach App Engine.  But artificial 404s don't seem to show up in the logs either, so I'm not sure I trust App Engine's logs.
* Affects all versions of blockly-demo, even back to 2018.  https://20180629-dot-blockly-demo.appspot.com/  So it's nothing to do with the Python script.
* Blockly Games uses virtually the same database, but it can load and save fine.
* The last push to blockly-demo was 1 July, so there's no way this bug has been unnoticed since then.
* The internal Datastore dashboard shows everything normal: 1.7 GB of data, across 400k elements.

@cpcallen You've got some familiarity with Google Cloud, can you take a quick peek to see if I'm missing anything obvious?

Otherwise, next step is to push a non-migrated version where storage.py just prints 'Hello World', then progressively add back functionality until it breaks.

**Comment by IBlackI** [comment]
I use the Blockly Developer Tools demo often, and can confirm it was working last week on Monday.

**Comment by NeilFraser** [comment]
@cpcallen Recognized the issue.  It was a permissions issue deep within Google's App Engine instance, unique to us.  All fixed.  Sorry about this, and thanks for reporting it!
