### ISSUE TITLE
Re-enable compile test in run_all_tests.sh

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#5602]
```
$ npm run test:compile:advanced

> blockly@7.20211209.0-beta.0 test:compile:advanced
> gulp buildAdvancedCompilationTest

[11:22:24] Using gulpfile ~/Code/blockly/gulpfile.js
[11:22:24] Starting 'buildAdvancedCompilationTest'...
gulp-google-closure-compiler: tests/compile/test_blocks.js:15:0: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "Blockly.Blocks" never defined.
  15| goog.require('Blockly.Blocks');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s)

[11:22:26] 'buildAdvancedCompilationTest' errored after 2.35 s
[11:22:26] Error: gulp-google-closure-compiler: Compilation errors occurred
    at CompilationStream._compilationComplete (/Users/fraser/Code/blockly/node_modules/google-closure-compiler/lib/gulp/index.js:238:28)
    at /Users/fraser/Code/blockly/node_modules/google-closure-compiler/lib/gulp/index.js:208:14
```

Furthermore, in Blockly Games, nearly all games fail with:
```
compressed.js:289 Uncaught Error: Error when registering mutator "controls_if_mutator": Mutations must contain either XML hooks, or JSON hooks, or both
    at Hh (compressed.js:289)
    at Object.Fh.ut (compressed.js:286)
    at compressed.js:713
```

**Comment by cpcallen** [comment]
Thanks to closure compiler updates in the mean time, `npm run test:compile:advanced` now completes successfully.  Output ends with `0 error(s), 200 warning(s), 93.9% typed`.  The preponderance of the warnings are for bad type annotations for `Blockly.Block` in files in `blocks/`:

```
blocks/lists.js:115:12: WARNING - [JSC_UNRECOGNIZED_TYPE_ERROR] Bad type annotation. Unknown type module$exports$Blockly$Block
  115|    * @this {Blockly.Block}
                   ^
```

I propose reenabling this in `tests/run_all_tests.sh` once #5597 is finished, as this should reduce the number of warnings to a small handful.

**Comment by cpcallen** [comment]
Commit 526e600 of PR #5721 refactors `buildAdvancedCompilationTest` (implementation of the `test:compile:advanced` script).  Following additions of `@suppress` annotations in earlier commits in that PR, the updated results from the compiler are `0 error(s), 11 warning(s), 94.1% typed`.  The remaining warnings are almost all JSC_PARTIAL_NAMESPACE warnings, e.g.:

```
core/blockly.js:685:20: WARNING - [JSC_PARTIAL_NAMESPACE] Partial alias created for namespace module$exports$Blockly$constants, possibly due to await/yield transpilation.
This may prevent optimization of anything nested under this namespace.
See https://github.com/google/closure-compiler/wiki/FAQ#i-got-an-incomplete-alias-created-for-namespace-error--what-do-i-do for more details.
  685| exports.constants = constants;
                           ^^^^^^^^^
```

Loading the build `tests/compile/main_compressed.js` (via `index.html` in the same directory) succeeds and the playground is mostly usable, but the mutator on the 'if' block is  it opens and can be manipulated, but does not mutate the if statement.  Instead, the following error appears in the console:

```
logic.js:505 Uncaught TypeError: h.Ec.g is not a function     (browser_events.js:69)
    at Z.Uo (logic.js:505)
    at Z.Ad (logic.js:404)
    at Km (mutator.js:432)
    at Rd.f.La (mutator.js:355)
    at Rd.f.El (icon.js:142)
    at Rd.f.El (mutator.js:145)
    at SVGGElement.k
```

The line in question is:
```JS
    Blockly.Mutator.reconnect(elseStatementConnection, this, 'ELSE');
```

@NeilFraser  and I were able to verify that the `reconnect` static method on `Blockly.Mutator` is being tree-shaken out.  Adding `@nocollapse` prevents the tree-shaking (and prevents `Blockly.Mutator.reconnect` from being replaced by variable), un-breaking mutators.  But this fix is not a good one:

* This situation is not one for which `@nocollapse` is expected to help (e.g., calling a static method on an unknown-at-compile-time constructor).
* The compiler appears to not be connecting the usage `Blockly.Mutator.reconnect` with the `reconnect` property on the `Mutator` export  of the `Blockly.Mutators` module.  (This may relate to the `JSC_PARTIAL_ALIAS` warnings, although none of them appear to relate directly to this class.)
* Adding `@nocollapse` to other static methods (e.g. `Mutator.findParentWs` in the same file) appears to cause them to not be tree-shaken _but does not prevent them from being collapsed_.  😫  We don't really want to just arbitrarily prevent any static methods from being tree-shaken!

I suggest that instead we finish migrating `blocks/*.js` to `goog.module` and check back to see if this problem is still occurring.
