### ISSUE TITLE
hide and show toolbox

### ISSUE THREAD

**Issue by mrredo-and-josetrindade1** [google/blockly#5608]
is there a way of doing a button that can hide and show tooblox?

**Comment by gonfunko** [comment]
`Blockly.getMainWorkspace().getToolbox().setVisible(false)` allows you to hide (or show, if you pass `true` instead) the toolbox; calling that from your button's click handler should do what you need. Also, for general questions like this, please use [Blockly's forum](https://groups.google.com/forum/#!forum/blockly) rather than filing a bug; we try to respond to all questions there, and there's a community of other developers who have worked with Blockly and can offer suggestions and advice too!
