### ISSUE TITLE
Blockly.common.setSelected is dangerous

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#5674]
The docs for `Blockly.common.setSelected` state:
```
* Sets the currently selected block.
* @param {?ICopyable} newSelection The newly selected block.
```
This is a public function.  Calling it sets the internal `selected` property, but does not do any of the UI involved in selecting or deselecting a block.

To test, open the playground, create two blocks and select one.  In the console, execute: `Blockly.common.setSelected(null)`

Actual result: block remains highlighted, but internally the block is not selected (e.g. if you click the second block, there are now two visually selected blocks)
Expected result: block visually unhighlights.

Maybe this function should update the UI.  Maybe this is just a documentation issue.

**Comment by cpcallen** [comment]
I think this is _mostly_ a documentation issue, but I would also suggest renaming this function to `recordSelected`, since that more accurately describes its purpose.  (I admit that `record`/`get` is not as nice a pairing as `set`/`get`, but this would also leave room for a `setSelected` that actually 'does the work' of selecting the block visually.)

The existing function should probably be marked `@package`.

**Comment by maribethb** [comment]
I made the function package visibility and added to the documentation, pointing the reader to `BlockSvg.prototype.select` if they want to programmatically select a block, including updating the UI, etc. Since that is already the canonical function to do so, I don't think we'll need to add a different function for this in the future and so I decided not to rename the function.
