### ISSUE TITLE
Provide API for setting max width of a flyout

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#5684]
**Is your feature request related to a problem? Please describe.**
When we have very large blocks the flyout can get to the point where it covers the entire workspace. 
This is especially annoying in cases where the flyout is constantly open. Like in the case of a simple toolbox or the continuous toolbox.

**Describe the solution you'd like**
A `getMaxWidth` function for vertical flyouts and `getMaxHeight` for horizontal flyouts that a developer can override to return their max width. This allows them to check whether the targetWorkspace `isMutator` if they want a different max width in that case.

*I chose this one over having hooks because I think that we have leaned into this pattern of overriding classes more than providing hooks in the recent years. However, adding the hooks seem a bit lighter weight so I could be convinced either way.

**Describe alternatives you've considered**
- We could have a static property on the horizontal and vertical flyout class, however it seems pretty likely that developers would want different max widths for the mutator flyout and the workspace flyout. 

- `getMaxWidth` and `getMaxHeight` hooks that developers can set. 

**Additional context**
There is currently a work around but I believe it requires quite a bit of copy/pasting and it seems like a common/general enough use case where it should exist in core.

Adding this after talking with @ajpal.

**Comment by maribethb** [comment]
I think we should close this for now because it doesn't make sense to add this to core without additional UX decisions. What should happen if you set a max-width? Should the blocks just be cut off or should they be scaled to fit? Just being cut off wouldn't be a great UX in my opinion and scaling to fit would be more involved than just setting the max-width.

Since this can be accomplished anyway by subclassing Flyout, and so isn't a blocking issue, I don't think this is something we should work on in this particular form. Feel free to reopen if you disagree.
