### ISSUE TITLE
How do contributors add a new programming language to Blockly?

### ISSUE THREAD

**Issue by hamirmahal** [google/blockly#5933]
**Where**
https://developers.google.com/blockly/guides/modify/ seems like an appropriate place to add documentation on how to modify Blockly such that it supports a new programming language.

**What**

- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**
Nothing

**Suggested content**
It would be helpful to have a step by step guide on all the changes necessary to add support for a new programming language to Blockly.

**Additional context**

[#98](https://github.com/google/blockly/pull/98) has some instructions, but it appears out of date. For instance, [that pull request modifies a `build.py` file](https://github.com/daarond/blockly/blob/ced61e5c58571358ea7b398c2c92497ea9b6f082/build.py), but a `build.py` file no longer exists in this repository's root directory.

**Comment by BeksOmega** [comment]
Heyo! Thank you for filing this issue :D Currently there's nothing in the guides about creating your own language generator. However! There is a codelab you can check out that walks you through creating a JSON generator as an example. Hopefully that gives you all of the information you need to get started.

Also since you mention contributing in the title: Currently Blockly is not accepting any new language generators in core, because 5 is already quite the workload. However! If you want to create a third party plugin for generating code in a given language, that would be rad and the core team would be happy to promote it (eg in our quarterly release notes).

I hope that helps! If you have any further questions about implementing a language generator please direct them to the lovely [forums](https://groups.google.com/g/blockly).
