### ISSUE TITLE
It is possible to have a caller block inconsistent to its definition

### ISSUE THREAD

**Issue by gpfernandezflorio** [google/blockly#5971]
**Describe the bug**

Taking a block from the trashcan allows you to have a caller block inconsistent to its definition.

**To Reproduce**

1. Create a procedure definition.
![image](https://user-images.githubusercontent.com/5846063/156425353-5daa8366-6700-4b7a-afad-a25f01bb2cde.png)
2. Create and delete a caller for that procedure
![image](https://user-images.githubusercontent.com/5846063/156425640-41c2e70d-1425-4e71-9bf4-fb84d87c74b8.png)
3. Add a parameter to the procedure
![image](https://user-images.githubusercontent.com/5846063/156425508-8512125a-46b5-455e-bfeb-073814408a0a.png)
4. Open the trashcan and add the caller to the workspace
![image](https://user-images.githubusercontent.com/5846063/156425841-67039f86-7728-40c3-a5f9-b946c8bea8f2.png)

**Expected behavior**

Not sure. I guess the caller should mutate to be consistent to it's definition.
Another option could be that it renames to a new procedure.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome v98.0.4758.102

**Comment by alschmiedt** [comment]
Thanks for reporting! I think the first option where the caller mutates makes the most sense to me (it is similar to what we do in the flyout). Just a heads up we are unlikely to get this out for the upcoming release in a couple of weeks, but we always accept PRs if you are interested in contributing : )

**Comment by BeksOmega** [comment]
I don't think this is a problem specific to the trashcan. It can also occur when you paste a copied caller into the workspace:
https://imgur.com/qywiPYR

Ideally the pasted block would mutate to match the procedure def, but callers don't save the UUID of the block definition, only the name, which can change, so that behavior isn't possible. I think the correct behavior is for the newly pasted caller to have its name change to match the generated procedure definition. I think would should be able to add that [here](https://github.com/google/blockly/blob/c9be8d984d6cc459917f2a777e03ba858f2e623d/blocks/procedures.js#L970).

**Comment by BeksOmega** [comment]
Closed by #6014
