### ISSUE TITLE
Flyout position and dimensions

### ISSUE THREAD

**Issue by Nekomajin42** [google/blockly#598]
Hi guys!

I'd like to know whether I can change the position and dimensions of the flyout with some config options.

I am building a turtle graphics application with Blockly and `<canvas>` layered above each other. I have a bigger canvas then the browser window, but I managed to adjust the size of the workspace to fit to the size of the canvas. So instead of using the built-in config option `scrollbars`, I can move together the workspace and the canvas behind it.

But the problem is the flyout, because it is sticked to the upper left corner of the workspace, so it moves with it on scroll. Is it possible to configure this behaviour?

**Comment by picklesrus** [comment]
What you're doing sounds pretty interesting - did you do this for performance reasons?
Do you have a link I could play with?  I'm particularly interested in this in terms of performance improvements.

I have been working on a version of blockly where I separate out the pieces (workspace, flyout, scrollbars, etc) into separate svgs to try and improve performance.  In that case, the flyout is its own separate <svg> so not pinned to the  main workspace anymore See http://blocktests-1261.appspot.com/bt/tests/playground.html?dir=ltr&toolbox=simple&side=start for a demo and the html structure (Use chrome to view since it is the least buggy there).  This is still a ways off from being finished due to some problems I've found in certain browsers though.

Another, non-ideal option is to try and use a toolbox instead of a flyout since that should be pinned to the surrounding div, not the workspace svg.

**Comment by Nekomajin42** [comment]
I have not taken the performance into consideration. I've just simply needed a bigger canvas, because we use 1024×768 old LCDs in the school where I teach. And since the canvas and the workspace are layered above each other, it is practical to be able to pan them together.

You can find an online version here: https://nekomajin42.github.io/teknocgrafika/
It is a work in progress, so you may encounter a few bugs. And it's in hungarian, but I think you can play with it.

Can you explain the last paragraph? How can I use a toolbox?

**Comment by picklesrus** [comment]
Oops, sorry. You are using a toolbox.  Some of the simpler apps just use a flyout (e.g. https://blockly-games.appspot.com/maze). You can ignore that part of my comment.

I see what you mean by the flyout doesn't stick to the toolbox.  There might be a way to use different css/html structure to make what you want work (maybe by messing with the blocklyToolboxDiv class?  For now we pin the flyout to the workspace since all blockly svg elements have the same parent.  The toolbox, however, is a div so attached to that injection div.  I'm not sure you'll have luck changing the blocklyToolboxDiv.  I haven't seen anyone using a canvas layered on top of blockly before, but you might try asking in the blockly group (https://groups.google.com/forum/#!forum/blockly) to see if anyone there has a better idea.

**Comment by Nekomajin42** [comment]
You can not see the changes yet, but I had to use a workaround where I dinamically change the content of the flyout. I tried to use my own CSS, but it was a big mess. So, for now, I use a simple flyout sticked to the left of the workspace. It's not ideal, but I can live with it.

Is there any chance that the Scratch Blocks projekt will allow more customization?

**Comment by RoboErikG** [comment]
Hi Tóth,

You might have better luck if you modify the Blockly code that handles workspace drags to also update your canvas position instead of trying to do your own drag handling.

We also have options for putting the toolbox at the left, right, top, or bottom, but they depend on Blockly's default drag handling to move the window into the workspace instead of the svg element. If you need more help debugging your code please ask on the mailing list (blockly@googlegroups.com).
