### ISSUE TITLE
Implicit conversion to string in text manipulation blocks

### ISSUE THREAD

**Issue by bkisdi** [google/blockly#604]
These blocks:

set **text** to <-[1234]
print <-[**text**]
print <-[in text **text** get substring from letter #<-[**2**] to letter #<-[**3**]]
print <-[to UPPER CASE] <-[**text**]

generate the following JavaScript code:
```
var text;

text = 1234;
window.alert(text);
window.alert(text.slice(1, 3));
window.alert(text.toUpperCase());
```

JavaScript stops az the third line with the
```
Uncaught Unhandled exception: undefined is not a function
```
message. :(
Expected: print the "23" string.

(Disable the 3rd line to reach the last one. The error message is the same.)

Cause: 1234 is not converted to string.
Solution: generate .toString() for the **text** arguments of ALL text manipulation blocks. Please.

Other arguments (such as the "letter #" above) and other blocks (like Math +-×÷^ etc.) may need implicit conversion to number. (?)

"Implicit" (from the end user's viewpoint) here means that Blockly should care about **explicit** conversion of the arguments, if the target language does not do so.

Other languages may be affected as well.

Thanks!

**Comment by NeilFraser** [comment]
> Other arguments (such as the "letter #" above) and other blocks (like Math +-×÷^ etc.) may need implicit conversion to number. (?)

JavaScript has no problem with `'101' - true`, the only time errors are thrown are when there's a `value.call` construct.

Also Note that your solution would blow up if a variable were null or undefined.  Using String(x) is safer than using x.toString().

One approach to this issue is to wrap every value into a casting call.  This means that generated JavaScript would look like this:
```
s = String(text).substring(1, String(text).length)
```
There are two problems with this.  One problem is that the resulting code looks far more complicated which is not good for teaching environments where the generated code is shown to students.  It is teaching students that one needs a bunch of (usually) unneeded boiler plate.  Blockly tries very hard to generate minimal code, rather than bullet-proof code.  The second problem is that it only addresses Strings.  Numbers and Booleans don't have the issue, and Arrays and Colours can't be converted.

A second approach to this issue is to use typed variables.  If one cares about this level of correctness, then typed variables are the way to go and the whole problem goes away with no additional generated code.  This is being handled in issue #446.
