### ISSUE TITLE
Typing issue - inject from "core/inject"

### ISSUE THREAD

**Issue by J-Bastian** [google/blockly#6075]
**Describe the bug**

The Typescript typing for the exported function "inject" from "core/inject" is quite strange.
The "opt_options" parameter type is either an undefined (OK) or a function taking no parameter and returning nothing.
In the documentation, "opt_options" is of type "BlocklyOptions" which is an object.
The documentation seems to be correct regarding the code found in "inject.js"
 
Excerpt from [blockly.d.ts](https://github.com/google/blockly/blob/master/typings/blockly.d.ts#L25689)
```
declare module "core/inject" {
    /**
     * Inject a Blockly editor into the specified container element (usually a div).
     * @param {Element|string} container Containing element, or its ID,
     *     or a CSS selector.
     * @param {BlocklyOptions=} opt_options Optional dictionary of options.
     * @return {!WorkspaceSvg} Newly created main workspace.
     * @alias Blockly.inject
     */
    export function inject(container: Element | string, opt_options?: (() => void) | undefined): WorkspaceSvg;
    import { WorkspaceSvg } from "core/workspace_svg";
}
```

**Expected behavior**

A typing similar to the [version 7.20211209.4](https://github.com/google/blockly/blob/7.20211209.4/typings/blockly.d.ts#L25191) : 

```
declare module "inject" {
    /**
     * Inject a Blockly editor into the specified container element (usually a div).
     * @param {Element|string} container Containing element, or its ID,
     *     or a CSS selector.
     * @param {BlocklyOptions=} opt_options Optional dictionary of options.
     * @return {!WorkspaceSvg} Newly created main workspace.
     * @alias Blockly.inject
     */
    export function inject(container: Element | string, opt_options?: BlocklyOptions | undefined): WorkspaceSvg;
    import { BlocklyOptions } from "blockly_options";
    import { WorkspaceSvg } from "workspace_svg";
}
```

**Additional context**

If the new typing is correct, the samples/documentation should be updated.

**Comment by janhink** [comment]
I encountered a similar issue with the module declaration change from "blockly/core" in version 7.20211209.04 to "core/blockly" in version 8.0.0. This caused a lot of issues in my development chain because webpack wasn't able to resolve the module. Why this change happened? I ended up adding aliases into my webpack configuration but still there are other issues...

**Comment by maribethb** [comment]
Hi,

We currently generate typings from the TypeScript compiler reading our JsDoc - it's not perfect and since we don't use TS ourselves (yet) it's hard for us to see these issues. We will accept PRs fixing the .d.ts files - if they come from those of you using TS then I have more confidence in them being correct vs me trying to anticipate what works for you all.

In particular BlocklyOptions is a bit weird as it has its own separate typing - I'm not surprised that one is a bit broken.

The change to `core/blockly` from `blockly/core` -- I'm not sure exactly what's happening there. I thought you should just be referencing `index.d.ts` which exports everything as just `Blockly` so I'm not sure where the `core/blockly` comes in, but I will add this to the list of things to take a look at this quarter and compare them with last quarter's definitions.

I'm optimistic that these problems will be lessened once Blockly itself is using TypeScript. Thanks for your patience in the meantime! and please feel free to add send a PR with type improvements :)

**Comment by Cyrusky** [comment]
What is this changing for?
@maribethb ? you changing this line and no documentation updated with it.
Could you please explain it for us? Thx.

#6051 Here.

**Comment by BeksOmega** [comment]
> What is this changing for? @maribethb ? you changing this line and no documentation updated with it. Could you please explain it for us? Thx.
> 
> #6051 Here.

Hello! This wasn't changed intentionally. As  stated in that PR you linked, the typings files were automatically generated using the typescript compiler. It did its best to infer the types, but wasn't always perfect. Maribeth did notice this, and implemented a lot of great manual fixes. But catching everything just isn't possible.

As Maribeth mentioned, we're moving rapidly to typescript, which should make it easier for the typescript compiler to infer the correct types. Thank you for your patience =)

**Comment by BeksOmega** [comment]
Should be fixed by https://github.com/google/blockly/pull/6283
