### ISSUE TITLE
Lists blocks serialize unnecessary xml mutations in JSON hooks

### ISSUE THREAD

**Issue by gregdyke** [google/blockly#6176]
The following blocks get their xml mutations serialized because that is the default behaviour without an explicit saveExtraState returning null. It is either unnecessary (or would be more efficiently stored as JSON, but I think unnecessary covers all the following)

- lists_setIndex
- lists_getSublist
- lists_split

The same applies to all blocks with the comment - could be addressed in this issue or separate issues?
```
    This block does not need JSO serialization hooks 
```

- procedures.js
- math.js
- text.js

**To Reproduce**

JSON Serialize any of the above blocks

**Expected behavior**

extraState in the form of a mutation should not be serialized (if necessary it should be serialized as json - it's likely it's not necessary)

**Comment by BeksOmega** [comment]
Sounds awesome! Thank you for your interest in contributing more :D

Multiple PRs associated with this one issue sounds rad. Feel free to include the other blocks (math, text) in this issue as well. I'd recommend waiting on the `procedures_ifReturn` block though, because we might be messing with the procedures next quarter, and I don't want you to do work that gets written over hehe.

Thank you again! If you have any thoughts/questions always happy to discuss =)

**Comment by BeksOmega** [comment]
Fixed by #6177
