### ISSUE TITLE
Custom handling when the block is disposed

### ISSUE THREAD

**Issue by e-gloo** [google/blockly#6319]
**Is your feature request related to a problem? Please describe.**

If I understood correctly (and has it is in the [code](https://github.com/google/blockly/blob/master/core/field.js#L1148)), we cannot yet make a variable referenced by a field other than a FieldVariable. I needed a way to make 2 fields, a text field and a dropdown field, being linked somehow, so whenever we change the value in the text field, it is updated in the dropdown field at the same time, mainly when the value selected is the same as the value from the text field. In order to achieve this, when the block of the text field is created, it creates a variable with the same id as the block id, and the same name as the text field value. Then, when the value of the text field is updated, it renames the appropriate variable with the new value. From there, the block of the dropdown field listen when the variable is renamed, and then update the current value if needed.
Everything works just fine, except the block of the text field is disposed. As the block does not get the "delete" event of himself, it can't delete the related variable, and the value will never be updated in the dropdown field.

**Describe the solution you'd like**

There's already `init` function at the block definition, maybe we could have `destroy` function which would be called when the block is disposed, then we would have the same principle has a constructor/destructor.

**Describe alternatives you've considered**

Other ideas:

- Create a new type of extension that would be called when the block is disposed instead of when the block is created.
- Dispose the block after the `onchange` function is called which would let the current block get the event of it's deletion.

**Additional context**

Note that this is pretty much a workaround a field not being able to reference a variable. It would be better to get this feature as the variable's name would depend on the text field value, and calling `refreshVariableName` would update the dropdown field value. However, we would still need a way to delete the variable when the block of the text field is disposed.

Any other workarounds or ideas to handle this. The only thing I want to avoid if possible, is to handle this in the workspace change listener, as I would need to handle every disposed block in there.

Thank you.

**Comment by BeksOmega** [comment]
Hello, thank you for filing this :D Would you be able to post your current code for handling this? I'm curious about why you're using a dropdown field with a variable, and not either a [variable field](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/variable) or a [dynamic dropdown field](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/dropdown#dynamic_dropdowns).

> The only thing I want to avoid if possible, is to handle this in the workspace change listener, as I would need to handle every disposed block in there.

Could you elaborate on this? If you want to add extra functionality when blocks are disposed, event listeners are definitely the best way to do so =)

Best wishes,
--Beka

**Comment by e-gloo** [comment]
Hello!

> Would you be able to post your current code for handling this?

Sure! This is an example with a css class block. One block defines a css class, and the other has a dropdown with all the defined classes. If it's still unclear, don't hesitate to tell me, I will try to explain differently or update my code.

```
// cssClassBlocks.json
[
  {
    "type": "style_class_def",
    "message0": "class name %1 %2 %3",
    "args0": [
      {
        "type": "field_input",
        "name": "CLASS_NAME",
        "text": "unamed"
      },
      {
        "type": "input_dummy"
      },
      {
        "type": "input_statement",
        "name": "STYLES",
        "check": "style_stmt"
      }
    ],
    "previousStatement": "style_class_def",
    "nextStatement": "style_class_def",
    "colour": 230,
    "tooltip": "",
    "helpUrl": "",
    "extensions": ["style_class_def_on_change"]
  },
  {
    "type": "style_class_name",
    "message0": "class %1",
    "args0": [
      {
        "type": "input_value",
        "name": "CLASSES",
        "check": "style_class_name"
      }
    ],
    "output": "style_class_name",
    "colour": 230,
    "tooltip": "",
    "helpUrl": "",
    "extensions": [
      "style_value_class_dynamic_options",
      "style_class_def_on_change_name"
    ]
  }
]
```

```
// cssClass.js
import * as Blockly from "blockly/core";
import {
  dynamicDropdownFromBlockExt,
  dynamicOptionsFromVariableOfType,
} from "../../utils/dropdownBlockExtension";
import classBlocks from "./cssClassBlocks.json";

Blockly.defineBlocksWithJsonArray(classBlocks);

Blockly.Extensions.register("style_value_class_dynamic_options", function () {
  this.getInput("CLASSES").appendField(
    new Blockly.FieldDropdown(
      dynamicOptionsFromVariableOfType(this, "style_class_def")
    ),
    "CLASS_NAME"
  );
});

Blockly.Extensions.register("style_class_def_on_change", function () {
  this.setOnChange(
    dynamicDropdownFromBlockExt(this, "style_class_def", "CLASS_NAME")
  );
});
```

```
// dropdownBlockExtension.js
export function dynamicOptionsFromVariableOfType(block, varType) {
  return () => {
    // Get all variable of the block type we want
    const variables = block.workspace.getVariablesOfType(varType);
    let options = [];
    // if no variable exists, then default value
    if (!variables.length) {
      return [["unamed", "unamed"]];
    }
    // variable name as option text, merge of id and name as option value
    for (const variable of variables) {
      options.push([variable.name, `${variable.getId()};;;${variable.name}`]);
    }
    return options;
  };
}

export function createOrRenameVariable(workspace, name, type, id) {
  // check if the variable exists before creating it
  let variable = workspace.getVariableById(id);
  if (!variable) {
    variable = workspace.createVariable(name, type, id);
  } else {
    // if already exists, then rename it
    workspace.renameVariableById(id, name);
  }
}

export function updateCurrentFieldValue(event, field, varId, oldName, newName) {
  const currentValue = field.getValue();
  // if current dropdown value is the value linked to the current updated variable
  if (currentValue === `${varId};;;${oldName}`) {
    field.getOptions(false);
    if (event === "var_delete") {
      field.doValueUpdate_("unamed");
      field.forceRerender();
    } else {
      field.doValueUpdate_(`${varId};;;${newName}`);
      field.forceRerender();
    }
  }
}

export function dynamicDropdownFromBlockExt(block, blockType, blockFieldName) {
  return (event) => {
    if (block.isInFlyout) {
      return;
    }
    if (
      // if the current block is changed and the block is the type we want
      event.type === "change" &&
      event.blockId === block.id &&
      block.type === blockType
    ) {
      // then create or rename a variable on block field new value
      createOrRenameVariable(
        block.workspace,
        event.newValue,
        block.type,
        block.id
      );
    } else if (
      // if a variable of the type we want is created or renamed
      ["var_create", "var_rename"].includes(event.type) &&
      event.varId !== undefined &&
      block.workspace.getVariableById(event.varId).type === blockType
    ) {
      // then update current value to the new variable name if it's the current name
      updateCurrentFieldValue(
        event.type,
        block.getField(blockFieldName),
        event.varId,
        event.oldName,
        event.newName
      );
    } else if (
      // if a variable of the type we want is deleted
      event.type === "var_delete" &&
      event.varType === blockType &&
      event.varId !== block.id
    ) {
      // then remove the variable from the options
      updateCurrentFieldValue(
        event.type,
        block.getField(blockFieldName),
        event.varId,
        event.varName,
        event.varName
      );
    }
  };
}
```

> Could you elaborate on this? If you want to add extra functionality when blocks are disposed, event listeners are definitely the best way to do so =)

I agree, but I think that it's better to handle the event inside the block listener itself rather than handling each block that is disposed in the listener of the workspace. I'm using the same mechanic for different types of block, so I think it would be better to handle this inside the block.

In any case, I think it would be better for a block to know when it is disposed, so it can execute some cleaning if needed, like removing environment variables/context that depend on it. What do you think?

**Comment by cpcallen** [comment]
@e-gloo: thanks for the sample code.  I will let Beka look at it more closely.

But, taking a step back: I am wondering if variables are the right fit for what you are trying to do here.  AIUI `Variable`s are specifically designed to model mutable user variables—i.e. mutable state—in the generated code (e.g. `let` statements in JavaScript), and here it seems like you are using them just to link declarations with usages of your CSS classes.  That's not unreasonable, but I wonder whether CSS declarations are more akin to functions rather than variables.  That probably gets you a separate use-block for each CSS class, though, rather than a single block with a dropdown, which might not be quite what you are looking for.

**Comment by e-gloo** [comment]
Thank you @cpcallen and @BeksOmega for your time and answers!

@cpcallen: I thought about it at the beginning as well, but I just found it so handy to be able to switch classes by a dropdown, knowing that you probably get more classes in an html document than functions in a basic exercise to learn the notion. I don't know yet, maybe I'm wrong and it would be better to use it as function...

@BeksOmega: I thought about `Variables` and `FieldVariables` as well first, but visually it would be the same, and it's not a bad thing, I just thought that it would be clearer for the student to separate the notions visually. However, using `FieldVariables` means that I would need to override the `ContextMenu` to remove the rename and delete option OR renaming the class from the `FieldVariables` should rename in the `FieldTextInput` as well OR I would need to implement the `TypedVariable` plugin to create a variable manually, typed as a class, and this creates a class definition block which I put my styles in it, and then I can use the `FieldVariables`, which means that is possible to use a class that has not been defined if we don't use the class block created. I looking the create something as much error proof as possible, so that is not really what I want, but it's not like it would crash or something, so I don't know.

For the event part, I suggested a `destroy` function similar to the `init` function, but which would be call when the block is disposed, so in the `dispose` function, we could check something like ``` if (this.destroy) {this.destroy()}```. What do you think of that?

In any case, I would like to thank both of you again, for your help and interest, you made me think differently!

**Comment by maribethb** [comment]
The approach Beka suggested that allows a block to receive its own delete event seems reasonable. Yes, it would be a breaking change.

I don't think it's likely that we add another function to the block definition API, since there is a simpler way to achieve this (with the event change listeners), but I appreciate you filing this and starting the discussion!

As for priority, since this can be achieved with a workspace change listener, I would normally say it's not that high. But if this is needed for the shared procedures work, and since we are currently doing a major release next, then it may make sense to do this now, but I don't know where we've landed wrt timing on the shared procedures work.

**Comment by e-gloo** [comment]
Hi @maribethb, thank you for your answer! I understand, and for now I'm using the workspace event listener and it's working. I hope it won't get ugly when I will have many other blocks but for now it's working just fine.

Thank you for your time!

**Comment by maribethb** [comment]
This was closed by #6337

**Comment by BeksOmega** [comment]
Reopening, because #6337 didn't actually fix this (even though that was my intention).

I forgot that events are fired after a delay when /not/ running tests. So even though blocks are receiving their delete events when we're running tests, normally they are not receiving them :/

We'll have to remove the change listener after a delay as well or something.

**Comment by e-gloo** [comment]
Hi @BeksOmega, thank you for reopening the issue. To be honest, since my code was working with the workspace listener, I didn't try out to handle it in the block listener. However, I would like to suggest one last time the `destroy` function, I don't really see why it would not be appropriate since we already have the `init` function, maybe it's one more function to the api, but I just think that when you know that you have a function to setup your block, if you want to clean, you would lookup to a specific function as well, at least that's how I think, maybe I'm wrong.
Anyway, thank you for considering this issue!

**Comment by BeksOmega** [comment]
Reopening, because this still doesn't completely solve the problem I was trying to solve. Insertion markers don't fire delete events, so they can't receive their own delete events, which means they can't do cleanup. I think we do need a `destroy` method to facilitate insertion markers doing cleanup.

**Comment by BeksOmega** [comment]
## Problem Statement

To summarize the above discussion: some blocks need to have backing data models (e.g. `VariableModel`s or new `ProcedureModel`s). They can create these in their `init` methods, or using [extensions](https://developers.google.com/blockly/guides/create-custom-blocks/extensions). However, currently there is no way for them to /clean up/ their own data.

## Solutions

### Workable but sad: Use a change listener registered separately from the block

This is the solution that the original filer (@e-gloo ) is using.

When the [change listener](https://developers.google.com/blockly/guides/configure/web/events#listening_to_events) receives a [delete event](https://developers.google.com/blockly/guides/configure/web/events#blocklyeventsblock_delete), it can inspect the block and clean up the block's data. This is not ideal because it means that the logic for cleaning up a block's data has to be separate from the definition of the block itself.

### Attempted and failed: Use a change listener registered from the block

This is the solutoin that I attempted to get working.

Theoretically, a block should be able to receive its own delete event, and clean up its data when it is received. However, this has two problems:
  1) Insertion markers don't fire delete events. Insertion markers have backing data just like non-insertion marker blocks (because insertion markers are blocks, see #5375 ) But they don't fire delete events, so there is no way for them to clean themselves up.
  2) If you have events disabled for any reason when you dispose of the block, your block won't be able to clean up its own data, because it will never receive its own delete event.

### Adding a `destroy` lifecycle hook

In this solution, we would add a new lifecycle hook (similar to `init`) which the block can use to clean up its own data. The lifecycle hook could be added to the JS definition mixin, or added as paret of a registered registered mixin [extension](https://developers.google.com/blockly/guides/create-custom-blocks/extensions).

The `destroy` method would be called near the end of the `Block` `dispose` method. After events have been enabled (so that `VarDelete`, `ProcedureDelete`, and similar events can be fired). But before `disposed` is set to true.

Alternatively, we could fire it at the beginning of the `Block` `dispose` method. But this seems inconsistent because the `BlockSvg` `dispose` method will already have destroyed things like icons and tooltips, but the `Block` `dispose` method won't have destroyed child blocks or connections yet. I prefer calling `destroy` at the end of the disposal process, rather than in the middle.

Wrt tradeoffs: This solution does add a new lifecycle hook that we are committed to maintaining. However, it seems to be the only workable + clean solution.

Documentation for the `destroy` method will be added to the [defining blocks docs page](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks).

**Comment by cpcallen** [comment]
This seems reasonable, but why not just override _dispose_?

**Comment by BeksOmega** [comment]
> This seems reasonable, but why not just override `dispose`?

We specifically disallow overriding of built-in methods, so that people don't /accidentally/ do this. See the [mixin logic](https://github.com/google/blockly/blob/1cccc3cb4a185d84b455e956201d7ff2d434acc8/core/block.ts#L1684).

We disallow this because there's no way for the methods external developers add to their block definitions to access the original implementations (e.g. via `super`). So if we did allow them to "override" `dispose`, we're really just allowing them to *overwrite* dispose. This is itself a problem because we're using mixins and not subclasses.

So to allow people to just add "a little bit of extra logic" we need to add an additional hook.

**Comment by cpcallen** [comment]
> We specifically disallow overriding of built-in methods, so that people don't /accidentally/ do this.

Oh, OK.  That seems reasonable enough given the ways that things might go wrong.  Nevertheless…:

> …there's no way for the methods external developers add to their block definitions to access the original implementations (e.g. via `super`).

Not with that attitude!

Where method `foo` is always mixed in to each `Block`/`BlockSvg` instance directly (as I believe is the case in Blockly):
```
function foo() {
  // ...
  Object.getPrototypeOf(this).foo.call(this, ...arguments)
  // ...
}
```

In a hypothetical system where the mixed-in method might be mixed-in to a prototype of the object upon which it will be called:

```
function foo() {
  // ...
  let obj = this;
  while (obj) {
    let pd = Object.getOwnPropertyDescriptor(obj, 'foo');
    obj = Object.getPrototypeOf(obj);
    if (pd && pd.value === foo) {
      obj.foo.call(this, ...arguments);
      break;
    }
  }
  // ...
}
```

**Comment by cpcallen** [comment]
BTW: `destroy` seems like a reasonable choice, but I might have gone with `onDispose` or `finalize` (well, actually `finalise`, but I realise that Neil and I are probably losing the battle for proper spelling…)

**Comment by rachel-fenichel** [comment]
> I prefer calling destroy at the end of the disposal process, rather than in the middle.

It can't be all the way at the end though, right? So we'll need to have some documentation on pre/post conditions for this dispose hook.

Overall I like this proposal.

**Comment by BeksOmega** [comment]
> > I prefer calling destroy at the end of the disposal process, rather than in the middle.
> 
> It can't be all the way at the end though, right? So we'll need to have some documentation on pre/post conditions for this dispose hook.

It can be right after [this line](https://github.com/google/blockly/blob/1cccc3cb4a185d84b455e956201d7ff2d434acc8/core/block.ts#L361). In which case the only things running after it are [disconnecting the dom](https://github.com/google/blockly/blob/1cccc3cb4a185d84b455e956201d7ff2d434acc8/core/block_svg.ts#L910) (and then only in the rendered case).

So I don't think we need info about postconditions since there's nothing there devs should need to worry about. We will probably want to explain preconditions in the docs.
