### ISSUE TITLE
Cannot use build.py

### ISSUE THREAD

**Issue by crousekimo** [google/blockly#6342]
When I type python build.py to build compressed.js files, blockly shows the following messages.
May I know what happen??

![image](https://user-images.githubusercontent.com/43980978/184572472-c14e15c1-c42d-4b68-bb68-43030313c53a.png)

**Comment by maribethb** [comment]
Hello! We no longer use or support `build.py` for building blockly. We also highly recommend you don't build blockly yourself (unless you are working on the core library). If you are looking to update your version of blockly, we'd recommend that you use our packaged release https://www.npmjs.com/package/blockly which is already built. If you need any help upgrading your version of blockly you can post in our developer forum https://groups.google.com/g/blockly where we will need to know the version you are upgrading from, and any specific issues you are having.

You can see our current build process here: https://developers.google.com/blockly/guides/contribute/core/building but it's not recommended to do this yourself, since we publish the built files already. Also, since we are currently migrating to TypeScript, this documentation is already out of date for the code in the `develop` branch right now.
