### ISSUE TITLE
UTF8 Symbols get changed in variable names

### ISSUE THREAD

**Issue by Brandyparty** [google/blockly#6410]
Languages like PHP can use UTF8 symbols in Variable names. The generated code from blockly however changes these codes to their hexcodes within the names. 

![image](https://user-images.githubusercontent.com/19206386/188972326-b11005fe-7e53-477e-9f92-b15db3f8d445.png)

**Comment by BeksOmega** [comment]
Related to #1654

**Comment by NeilFraser** [comment]
Reconfirming that Dart and Lua still do not support UTF8 symbols.  Neither does Python 2, but Python 3 does.

**Comment by rachel-fenichel** [comment]
After discussion: wontfix, because the rules for figuring out which symbols are acceptable are easy to mess up, and the resulting issues at runtime are particularly nasty.

If someone wants to show their generated code while using UTF-8 or Unicode strings, and it's not possible to use ascii (or is detrimental to the learning experience for students), please comment here so we can discuss further.
