### ISSUE TITLE
Consider reverting PR #6335 due to ES5 incompatibility

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#6419]
**Describe the bug**

The change to release Blockly as ES6 rather than transpiling to ES5 has the unintended consequence of breaking most ES5-style subclasses of Blockly classes, most notably subclasses of `Field`.  This includes [breaking a number of our own samples and demos](/google/blockly-samples/issues/1267).

The change to publishing ES6 should perhaps be treated as a deprecation of the previous ES5 support, including giving a suitable notice period etc.

**To Reproduce**

See google/blockly-samples#1267

**Comment by rachel-fenichel** [comment]
After discussion, we decided to go forward with the move to ES5 at the same time as the major TypeScript changes. This quarter's release is major in every way, and dragging out the deprecation of ES5 just guarantees that we have a major release in the future.

Developers will be impacted by this if they
- Use ES5-style subclassing AND
- Update to Blockly v9 AND
- Cannot trivially change their inheritance because they are using `this` before calling the super constructor

**Comment by cpcallen** [comment]
Corrected Rachel's comment: 

> the move to ES5

to "the move to ES6".
