### ISSUE TITLE
Pinch to zoom not working anymore

### ISSUE THREAD

**Issue by clementcontet** [google/blockly#6508]
**Describe the bug**

Since the migration from Blockly 6.2 to Blockly 9, the pinch to zoom doesn't work for me on touch devices.

**To Reproduce**

Visit https://www.supercodingball.com/code/offline/do-nothing on a touch device (or clone and run https://github.com/Orange-OpenSource/super-coding-ball on a touch device).

**Expected behavior**

I may do something wrong but I can't figure out what.

The pinch setting is still there: https://github.com/Orange-OpenSource/super-coding-ball/blob/d86a9d3dd2bdf4830518bac607a0e347ff380e86/src/app/components/blockly/blockly.component.ts#L83

**Smartphone (please complete the following information):**
 - Chrome Android

**Comment by clementcontet** [comment]
In console, I get the following warning: 'Tried to start the same gesture twice.'
I've tried https://blockly-demo.appspot.com/static/demos/code/index.html on a mobile device and I get the same error.

**Comment by maribethb** [comment]
I've done a git bisect and #6099 is the culprit, still working on root causing

**Comment by maribethb** [comment]
root cause found: https://github.com/google/blockly/blob/1162a660a0cfe9ff2acdbed5ee66246d3bd5beb2/core/touch.ts#L167

`PointerEvent` is a [subclass](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent) of `MouseEvent`, so the touch identifier is always set to 'mouse' if pointer events are supported. This causes `shouldHandleEvent` to always think we are talking about the same touch point, and says we should always handle the touch event.

PR incoming (after more testing is done)
