### ISSUE TITLE
Does blockly have solution for collaborative development?

### ISSUE THREAD

**Issue by caixiao7** [google/blockly#6592]
My application uses blockly as a component and it provides usual features just like other ide tools do. Users could create a project containing multi blockly workspaces. At the end of the day,each workspace turns into python code as a module and is called by a main.py generated by my ide.

If there are two developers modifying the same blockly workspace at the same time,how could they merge blockly code when they finish their own jobs? I found it difficult to compare blockly in xml format. Is there any ready-made solution solving this problems?

Besides,I don`t know whether is a wise way to divide a project into several blockly workspaces because I found microbit and other applications using blockly are using only one workspace. In that case, code modularity is not guaranteed

**Comment by BeksOmega** [comment]
Hello!

If you are looking for real-time collaboration, we generally recommend using the [events system](https://developers.google.com/blockly/guides/configure/web/events) to handle that. You can check out the [real time collaboration demo](https://github.com/google/blockly-samples/tree/1be2b748414ef147c8f7d657fa440442c0ef49a8/examples/blockly-rtc) for an example =) But be warned: it's not polished and could run into event conflicts!

Generally we like to keep these kinds of questions on our [developer forum](https://groups.google.com/g/blockly), so if you have any further questions please start a thread over there! It's also a good place to ask questions like this because other devs /using/ Blockly are more likely to see it and share their experiences =)

Best wishes!
