### ISSUE TITLE
possible error in Blockly.Connection.prototype.hideAll

### ISSUE THREAD

**Issue by yoderjen** [google/blockly#67]
This may or may not be a bug.  The Blockly.Connection.prototype.hideAll function doesn't actually hide the connections (setting this.hidden_ = true;).  The corresponding unhideAll function does set this.hidden_ = false;.

I am doing some weird type checking with my app (depending on the nextStatement's block type, I hide and unhide inputs on some blocks), and I was getting a glitch where I'd see a highlighted connection path for hidden inputs (although only after I'd dragged around the parent block after a hide - as if the hidden input connection got repopulated into the connection database during the drag?  I don't know this, I didn't track down why it only happened after a move).  I could even connect a block into the hidden input!  I fixed my glitch by adding 
this.hidden_ = true; 
into the hideAll function (called from the input.setVisible function).

There may have been a good reason not to put this statement in? - if so, please respond to this so I can figure out a better way to fix my glitch. Thanks.

**Comment by NeilFraser** [comment]
Sorry for the delay, I was in a country that has no Internet.

Indeed, this is a classic case of active rot.  Two completely independent command chains evolved that hide/unhide connections.  I've merged them so that Connection:setHidden is now the only method which toggles the .hidden_ property.  Thanks!
