### ISSUE TITLE
CI hangs if tests fail

### ISSUE THREAD

**Issue by maribethb** [google/blockly#6756]
If any of the tests fail, CI fails to exit and hangs until GitHub kills it after 6 hours.

Root cause: https://github.com/google/blockly/pull/6615

**Comment by BeksOmega** [comment]
Ok I dug into this because I didn't understand what the root problem was and why #6763 fixed it, and now I understand!

When there was a failure in the mocha tests or generator tests, we leave the webdriverio browser window open ([mocha](https://github.com/google/blockly/blob/65834a0f01b0fdb86de1d9290324201044c8dfc7/tests/mocha/webdriver.js#L79), [generators](https://github.com/google/blockly/blob/65834a0f01b0fdb86de1d9290324201044c8dfc7/tests/generators/webdriver.js#L98)). Presumably this is so that you could debug the failure when running `npm run test` locally. 

This meant that the gulp tasks for mocha and generators would not complete in the case of failure, because the node processes were kept alive by the browser windows.

Before #6615 this was not a problem, because if you explicitly reject a promise (or equivalently, throw an error within an async function), then it will force the gulp task to exit even while the browser instance is alive. Which is what the [old code was doing](https://github.com/google/blockly/blob/d37223d8abe0b8afeac152092bdc6c1955bb53dd/scripts/gulpfiles/test_tasks.js#L319). And now after #6763 we are [doing that once again](https://github.com/google/blockly/blob/65834a0f01b0fdb86de1d9290324201044c8dfc7/scripts/gulpfiles/test_tasks.js#L92).

So explicitly rejecting a promise (as we did), or forcing the webdriverio instance to close regardless of failure or success (as we did not do), would both have fixed the CI issue.

**Comment by cpcallen** [comment]
> if you explicitly reject a promise (or equivalently, throw an error within an async function), then it will force the gulp task to exit even while the browser instance is alive.

I suspected that might be the case—it seemed like the most plausible explanation given the observed behaviour—but thank you for verifying it.

> So explicitly rejecting a promise (as we did), or forcing the webdriverio instance to close regardless of failure or success (as we did not do), would both have fixed the CI issue.

I wonder if we should change our `test/mocah/webdriverio.js` to close the browser session when running in CI even if tests failed.  That seems like a better approach.

**Comment by BeksOmega** [comment]
> I wonder if we should change our test/mocah/webdriverio.js to close the browser session when running in CI even if tests failed. That seems like a better approach.

Personally I think it'd be best to investigate getting rid of webdriver for running the tests :P

**Comment by maribethb** [comment]
Makes sense. I would also like to reduce our use of webdriver except where needed (and really not convinced it's needed for generator tests at all) but it should be an easy fix to also check if in CI, don't keep the browsers open. However, I would prefer to keep both approaches where we both reject a promise and also close our webdriver instances.

Rejecting the promise fits better with my mental understanding of how gulp works. If we didn't reject the promise at the end, what else is telling gulp that the test failed? wouldn't it always report success? (this is what happens if you run `npm run test:generators` by itself)

**Comment by BeksOmega** [comment]
> If we didn't reject the promise at the end, what else is telling gulp that the test failed? wouldn't it always report success?

Oddly, nothing /needs/ to tell gulp that the tests failed, unless we're trying to force it to exit (which we are). We log explicitly that tests failed, so we don't care if it exits as if it succeeded :P

Definitely counter to the mental model, but technically the case.

**Comment by maribethb** [comment]
Isn't gulp exiting with success or failure what determines if the CI ultimately reports success or failure? it's not useful to log that the tests failed in CI if GitHub reports they passed.

**Comment by cpcallen** [comment]
> Rejecting the promise fits better with my mental understanding of how gulp works. If we didn't reject the promise at the end, what else is telling gulp that the test failed? wouldn't it always report success? (this is what happens if you run `npm run test:generators` by itself)

It was definitely an error on my part that in #6615 [`Tester.prototype.runAll`](https://github.com/cpcallen/blockly/blob/195b9d2e00281e1cbb4c31cee6852f58becac9dc/scripts/gulpfiles/test_tasks.js#L45) (which becomes  a gulp task via [`.asTask`](https://github.com/cpcallen/blockly/blob/195b9d2e00281e1cbb4c31cee6852f58becac9dc/scripts/gulpfiles/test_tasks.js#L55) did nothing to signal failure to `gulp` if any of the individual tests failed.  However:

* It should still have (by virtue of being an `async function` that runs to completion) been signalling _successful_ async task completion, and I'm not sure why gulp behaves differently with respect to terminating node for successful vs. unsuccessful task completion (that seems like it might be a bug in gulp).
* We're now back to [using `gulp.series`](https://github.com/google/blockly/blob/ee51c0f41c6c52d118b8e6b6d406b5b303c7e101/scripts/gulpfiles/test_tasks.js#L366), [the documentation for which](https://gulpjs.com/docs/en/api/series/) says:

  > When the composed operation is executed, all tasks will be run sequentially. If an error occurs in one task, no subsequent tasks will be run.

  which means that if any of the tests fail then `reportTestResult` would not even be run were it not for the fact that `runTestTask` always signals success.  (This could certainly be improved: if `build` fails then there's not much point even attempting the following tests—except for `renamings`, which is independent.)
