### ISSUE TITLE
Dropdown content turns into text?

### ISSUE THREAD

**Issue by lukeplays33** [google/blockly#6806]
### Check for Duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

Specefic words in my dropdowns turn into "text".

My block:
![Screenshot 2023-01-30 17 18 58](https://user-images.githubusercontent.com/54947833/215535008-28d6d615-67ca-4d9f-b83c-dd4ce0298478.png)

Definition:
`Blockly.Blocks['saveitem'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("call")
        .appendField(new Blockly.FieldDropdown([["LocalStorage Manager","local"], ["SessionStorage Manager","session"]],this.validate), "NAME")
        .appendField(".setItem");
    this.appendValueInput("key")
        .setCheck("String")
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("key");
    this.appendValueInput("item")
        .setCheck(null)
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("value");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour('%{BKY_FUNCTION_HUE}');
 this.setTooltip("Returns true if darkmode is enabled");
 this.setHelpUrl("");
  },validate: function(newValue) {
  this.getSourceBlock().updateConnections(newValue);
  return newValue;
},updateConnections: function(newValue) {
    if(newValue == 'session') {
this.setTooltip('Store an item in the ' + newValue + 'Storage will be removed after the last browser session closes.')
} else if(newValue == 'local') {
this.setTooltip('Store an item in the ' + newValue + 'Storage.')
}
}
};`

I expect the word "Manager" to be in the dropdown but it isn't.

### Reproduction Steps

[Screen recording 2023-01-30 17.24.39.webm](https://user-images.githubusercontent.com/54947833/215534669-6b6cbee2-c5cf-472f-b168-3b70f3f65197.webm)

**Comment by cpcallen** [comment]
This is working as intended: [the `FieldDropdown` constructor calls `trimOptions` to factor any common prefix or suffix out of the drop down options](https://github.com/google/blockly/blob/05f343795edc33859d9af8b9373f0aa491c35d41/core/field_dropdown.ts#L132).  This is a particular convenience when translating blocks to multiple languages, as different languages might have different prefixes/suffixes.

If you find this behaviour undesirable then one workaround is to supply a menu generator function that returns the array of dropdown options rather than supplying the array itself.  (This will require defining the block using JavaScript rather than plain JSON; using an JSON + an extension might also be possible.)
