### ISSUE TITLE
Non-Geras renderers align value input text differently from Geras

### ISSUE THREAD

**Issue by SneezingCactus** [google/blockly#6873]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

It seems like the vertical text alignment in value inputs is handled differently in Geras, than in non-Geras renderers, like Thrasos. Non-Geras renderers vertically center the text, while Geras moves it directly to the top.

Vertically centered text looks alright in some cases, but it can look off or jarring in other cases (see how the "create list with" text doesn't seem to be aligned with anything at first glance).

### Reproduction steps

1. Grab a block with external inputs,
2. Connect a block with more than one external input into it.
3. Switch between Geras and a different renderer to see the difference.

### With Geras
![withgeras](https://user-images.githubusercontent.com/46355725/222267688-220f0be9-cc39-4a5a-b243-6ee04e9c3d4d.png)
### With Thrasos
![withthrasos](https://user-images.githubusercontent.com/46355725/222267726-023659e3-fd41-48db-b7d0-7641ef057504.png)

**Comment by maribethb** [comment]
Hello, thank you for reporting.

While you are not wrong, this behavior is something we are not likely to change. In some cases, vertical centering may look "wrong" but in others it may look more correct than the alternative. Deciding which case is which requires too much context on an individual block for the renderer to figure out. For more background discussion, see https://github.com/google/blockly/issues/2894#issuecomment-523567247 and https://github.com/google/blockly/pull/2835

You can change this by customizing the renderer, or just using thrasos. We actually suggest using thrasos instead of geras for a more updated look anyway.
