### ISSUE TITLE
Option to keep Category expanded after placing block

### ISSUE THREAD

**Issue by kmckee** [google/blockly#696]
I'm using categories in the toolbox.  When I expand a category and drag a block onto the worksurface, that category gets collapsed again.  

Is there an existing option, or would it be feasible to add an option, that kept the 'popup' showing all blocks in the category open even after selecting a block?

I feel like having to open a category every time isn't the best experience.  Over at scratch.mit.edu they do something similar to what I'm looking for.

Thanks!

**Comment by kmckee** [comment]
![auto_collapse](https://cloud.githubusercontent.com/assets/1400242/19350727/f127565a-9126-11e6-91db-d9798ec69f4e.gif)

**Comment by NeilFraser** [comment]
Yes, there is a setting for this.  You can try it out here:
https://blockly-demo.appspot.com/static/demos/toolbox/index.html
Just open the console and type:
workspace.toolbox_.flyout_.autoClose = false

We don't advertise this setting since most developers who request this quickly go back to the default behaviour once they see it in action.

**Comment by jessicabelicia** [comment]
Hi!

I know it is been a while, but I am also facing the same issue at the moment.
I tried to use `workspace.getFlyout().autoClose = false` and it worked at first, but it is not working anymore since a couple of weeks ago.

It would be really appreciated if there is a way to keep the toolbox opened after dragging a block in the latest version.

Thanks!
