### ISSUE TITLE
python codegen bug when generate code s[0:-1] it will generate s[-1:-1]

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#6963]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

both text and lists category  this block has this issue,I capture a screenshot bellows to describe this bug

in python,we never use s[-1:-1]

### Reproduction steps

1. 
2. 
3. 

### Screenshots

![Snipaste_2023-04-08_08-50-00](https://user-images.githubusercontent.com/42778/230696380-337bb941-3802-4181-b303-9aabfa624486.png)

**Comment by maribethb** [comment]
Hi @mlzboy,

This behavior is because by default blockly uses one-based indexes (which is more intuitive to new programmers). So we automatically subtract 1 from whatever number is used in this block. You'll also see this behavior in some of the other list and text blocks like getIndex.

If you'd like to use zero-based indexes in your application, you can set the `oneBasedIndex` option to `false` in the [configuration options](https://developers.google.com/blockly/guides/configure/web/configuration_struct).
