### ISSUE TITLE
A official WordPress plugin for Blockly

### ISSUE THREAD

**Issue by Atten007** [google/blockly#6964]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

No.

### Request

Hello,

I want to create a page named "BlockSpigot", which allows Minecraft players to create plugins for PaperMC visually with a block programming language. I want to run this page on WordPress 6.2, but there's currently no official Blockly plugin by Google for WordPress, so I wanted to ask here if there's an official WordPress plugin for blockly and if yes, where can I download the plugin? Or is there currently not an official Blockly plugin for WordPress?

Greetings,
Atten

### Alternatives considered

I don't considered alternative solutions.

### Additional context

I don't have additional context.

**Comment by maribethb** [comment]
Hello,

There is no plugin for using Blockly with WordPress, and supporting one is not in scope for the core Blockly team. The good news is because Blockly is designed for web, you can probably get something working on your own using HTML and JavaScript. You can try asking on the [forum](https://groups.google.com/g/blockly) if anyone else has experience doing this. The forum is a better place for general development questions like this. Thanks,

Maribeth
