### ISSUE TITLE
Invalid block names confuse the library

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#698]
On Blockly Dev Tools, create a block in the library named '123'. It will be saved as '_\123' which generates JSON with '_\123'. If you then export the library and reimport it you sometimes get an error, other times you just get a confused library that has the blocks listed under the unadjusted name (123) and offers to save your new block (_\123).

The two issues here:
- Invalid names should just get an underscore prefix. The backslash is not needed.
- When importing, invalid block names should get adjusted as well.

**Comment by RoboErikG** [comment]
The error is thrown by BlockExporterTools in eval, so there's something wrong with how we're building the list of blockDefs in JS.

BlockExporterTools.prototype.addBlockDefinitions = function(blockXmlMap) {
  var blockDefs = this.getBlockDefinitions(blockXmlMap, 'JavaScript');
  eval(blockDefs);
};

**Comment by picklesrus** [comment]
A little more background.  It turns out the original block factory (currently at blockfactory_old) has this problem too, it just isn't nearly as obvious. 

Example: 
1. load https://blockly-demo.appspot.com/static/demos/blockfactory_old/index.html#fnup34
2. switch the language code to javascript 
3. Notice there's the same octal error in the console and block preview disappears.
