### ISSUE TITLE
Change language without extracting a parameter from the url 

### ISSUE THREAD

**Issue by ddazal** [google/blockly#701]
Hello, a friend and I are developing a web application using Blockly that allows the user to get the .c code for two microcontrollers (by now). It's still so far from the final version but if you want to take a look, you can follow it here: https://github.com/ddazal/pickly (all the work isn't in the branch master)

We're using AngularJs and angular tranlaste for i18n. In index.html page we load the script of Blockly which contain the default language we want with an id. In order to change the blocks language we use the .replaceWith() method in a function that is in the controller.

``` javascript
$scope.changeLanguage = function(Lan_key){
     $translate.use(Lan_key);
     $('#block_lang').replaceWith('<script id="block_lang" src="google-blockly/msg/js/'+Lan_key+'.js"></script>');
};
```

The language of the blocks that aren't in the workspace do change, but the blocks in the workspace don't. How can we fix that without extracting a parameter from the url (as seen in the demos of blockly)? We are not experts so this issue has been a little tricky for us to solve. 

Thank you so much in advance

**Comment by NeilFraser** [comment]
Blocks in one language may look completely different from blocks in another language due to differences in word-order.  Thus you can't change the language of a running Blockly instance.

If you really want to change language without doing a page reload, you can save the workspace to XML, destroy the workspace with workspace.dispose(), create a new workspace with Blockly.inject(), then load the XML into the new workspace.

**Comment by ddazal** [comment]
You rock Neil! Thank you so much. I had to use a timeout before restoring the workspace, but works great
