### ISSUE TITLE
The trigonometric functions involved in the conversion from Blockly to the Python language are wrong

### ISSUE THREAD

**Issue by Landy0524** [google/blockly#7015]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

![image](https://user-images.githubusercontent.com/44955388/234246199-c94f0c9b-63fe-42d9-91b1-7bbaa167110b.png)

The parameter of asin, acos, atan mast be a number in the range -1 to 1. But now return 45

### Browsers

Chrome desktop

**Comment by maribethb** [comment]
Hello,

Blockly is behaving correctly here, so I'm going to close this issue. If you do try to call asin with an input of 45, you get a math domain error in python, which is correct. If you call it with an appropriate input then you get the correct answer. So there's nothing wrong with the python generator.

The `45` in the screenshot you shared is a shadow number block. Shadow blocks suggest default values. In this case it makes sense as a default value for a "sin" operation but not for an "asin" operation. When the value of the dropdown is changed from "sin" to "asin", we don't update the value of the shadow block. This is consistent with how blockly works with real blocks and input values as well. Blocks can validate the value of their fields, but generally don't validate the contents of blocks that are attached to their inputs. For instance, if this block had a number field instead of an input, you could have a validator that ensured the value entered by the user is between -1 and 1. You can't do that for an input that accepts a block, because the value of that block isn't known until runtime. It could be based on a variable, set in a loop, or even set to a random number, so there's no way to validate that the value is correct.

You could set up a change listener that updates the value of the shadow block when the dropdown is changed. But that's not going to stop a user from dragging a real number block with a value of 45 into this input connection. You could also not use a shadow block for this block.
