### ISSUE TITLE
Blockly freeze on ios 12.4

### ISSUE THREAD

**Issue by AzkabanPresident** [google/blockly#7081]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

 9.0 and above have this problem.Under 9.0 versions is ok

### Reproduction steps

1. create html, add <script src="https://unpkg.com/blockly/blockly.min.js"></script>
2. run on ios 12.4
3. whole page is freezen.

**Comment by rachel-fenichel** [comment]
iOS 12 uses Safari 12, which we no longer support (because Apple doesn't support it). Can you tell me more about your use case so I can see if I can suggest workarounds? Specifically, are you using iOS 12 because that's what your users need, or just incidentally because that's what you have locally?

**Comment by AzkabanPresident** [comment]
> iOS 12 uses Safari 12, which we no longer support (because Apple doesn't support it). Can you tell me more about your use case so I can see if I can suggest workarounds? Specifically, are you using iOS 12 because that's what your users need, or just incidentally because that's what you have locally?

thanks for your replay. Yes,I have some users  using iOS 12. Now I use Blockly 8.0.5, it works.
