### ISSUE TITLE
block only allowed specific type,but after set to a variant,this limition is lost

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#7185]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

![image](https://github.com/google/blockly/assets/42778/8e69fec9-74f6-4ab0-bf98-d61470251a68)

### Reproduction steps

1. 
2. 
3.

**Comment by rachel-fenichel** [comment]
Can you share your block definitions?

**Comment by maribethb** [comment]
Hello,

This problem is due to having untyped variables. The default variables in Blockly do not have types so they can connect to any type of connection. If you have untyped variables, there is no way to know what the value of the variable is until code runtime, so we cannot make the decision in the editor about whether the blocks are allowed to be connected.

Consider these blocks: 
<img width="505" alt="Screenshot 2023-06-21 at 3 59 17 PM" src="https://github.com/google/blockly/assets/8573958/25745e68-2e2a-4d32-bb01-c872e14eac26">

Sometimes the variable `i` will be set to a string and sometimes to a number. We won't know until code runtime. So if you have untyped variables, you need to make sure you use sensible defaults in your code generators in case the type of variables doesn't make sense, or otherwise surface these types of errors to your users.

Alternatively, you can use typed variables. Using these, users will create variables that can only hold strings, or only hold numbers, etc. You can read more about typed variables on [this documentation page](https://developers.google.com/blockly/guides/create-custom-blocks/variables).

Since this is more of a question and not an issue with Blockly, I'm going to close the issue. If you have followup questions, please ask on our [developer forum](https://groups.google.com/g/blockly) and we will be happy to help you. Thanks!
