### ISSUE TITLE
Add an `isShadow` parameter to `BlockCreate`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7252]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Right now mirroring between workspaces when one workspace has shadow blocks causes extra block to be mirrored into the other workspace.

E.g: If you overwrite a shadow block, and then disconnect the overwriting block, the mirrored block with get an additional real block matching the state of the shadow block.

You can work around this by parsing the XML to see if it's a shadow node, but that sucks.

Note that you cannot check the `ids` to see if any are shadows, because you can't know what the top ID is (the array is not ordered).

### Request

Add an `isShadow` property to `BlockCreate` so you can know if it's a shadow block.

### Alternatives considered

Make the `ids` array ordered so you can check the first block to see if it's a shadow.

### Additional context

Might also be useful to add this to `BlockDelete`? But I don't have a concrete use case for that.

**Comment by maribethb** [comment]
Rachel would rather not add properties to the top-level of the event, but we were both kind of confused about why this would need to be. Why is the fact that it's a shadow block in the xml info for the event but not the json? Is there actually a bug in that part of the event serialization we should fix instead? So this needs more info but based on what we have right now we'd rather do one of the alternatives considered (also, Rachel asks why it sucks to parse the xml, since it's there already?)

**Comment by BeksOmega** [comment]
> Why is the fact that it's a shadow block in the xml info for the event but not the json?

Yeah so in the JSON, the shadow-vs-block info is stored at the "connection level", not within the data defining the block itself. If the block's data is assigned to the `shadow` property of the connection, then it's a shadow, if it's assigned to the `block` property, then it's a normal block.

```
{
  type: 'test_block',
  next: {
    'shadow': {  // This object is what gets serialized. It does not say if the block is a shadow.
      'type': 'other_test_block'
    }
  }
}
```

We [did consider including whether the block was a shadow or not in the object](https://docs.google.com/document/d/1Dbpezxsd4H1S0p31ncrZ1hLaMfFYBeanv8pqjkpxoHI/edit?resourcekey=0-hYVVlo828cnLmnlj30Lysg#heading=h.1t2oytucd4c1) as well, but at the time we decided against it because it would increase the serialization size.

In the XML system, whether the block is a shadow or not is specified by the type of XML element (`<shadow/>` vs `<block/>`) so it's part of the data that actually defines the block (not up a level like in JSON).

> Is there actually a bug in that part of the event serialization we should fix instead?

I don't thiiink so. We could include the "kind" of block in the serialized state, but that increases save size as discussed above. We could also special case the serialized JSON for creation events, but that's difficult to document and surface to developers. In my mind, that has the same draw backs as adding a new property, but strictly less advatages.

> Rachel asks why it sucks to parse the xml, since it's there already?

I guess the actual mechanics of inspecting the XML aren't terrible. But I think it kind of sucks that we've communicated "JSON is the future" but folks have to solve this issue by dealing with XML. It makes the API seem unfinished and unintentional.

---

Thinking about this more, I think this is actually two issues:
  1) Mirroring shadow create events creates duplicate blocks.
      I think this is just a bug we should fix internally (fixing the `run` method of `BlockCreate` events to handle shadows properly). It might even be a regression when we switched to JSON - I'd have to check.
  2) Giving developers a way to know whether a create event was for a shadow block.
      Personally I still think the `isShadow` property  feels the most explainable, understandable, and clean! And I'd also be happy with solving this by having the `ids` array be ordered (since that at least elliminates the need to deal with XML). But if y'all are happy with the current system I'm also ok with that!

**Comment by maribethb** [comment]
First, let's definitely fix the behavior in the `run` method to handle shadow blocks correctly. That should be bumped higher priority. I filed https://github.com/google/blockly/issues/7310 for that.

If that were fixed, when else would a developer want to know if the create event involves shadow blocks? Presumably you would only want to set an `isShadow` property to true if the *top-level* block is a shadow block. If that's all you care about, then you can just check if *every* block in the id list is a shadow block. Since shadow blocks can't have "real" children, you don't need the id array to be sorted.

If that is an acceptable way to check if the top-level block is a shadow block, then I don't think we're adding a lot of value by adding an `isShadow` method, and anyway before doing work on this I'd want to hear from developers who are requesting this information.


______________

Side note: As far as I know the only way to actually get a Create event with a top-level shadow block is when you disconnect a block that "covers up" a shadow block. Since shadows aren't selectable and can't have real children I don't know of another way that event would be generated. That sort of feels to me like maybe it shouldn't be a create event, but changing that would be a breaking change and probably annoying.

**Comment by BeksOmega** [comment]
I think checking the ID list to ensure everything is a shadow is a reasonable work around! Especially considering in most cases it will have a length of 1 :P

Reprioritizing the `run` functionality makes sense to me! Cuz I think that is indeed a bug.

And I agree, it's weird that regenerating a shadow fires a create event (I actually checked some old versions of blockly to make sure we've always done that - and it seems we have). But yeah, breaking changes =(

**Comment by maribethb** [comment]
Closing since we agreed that checking if all the IDs represent shadow blocks is acceptable. That's what I did for #7427
