### ISSUE TITLE
Update `widgetCreate_`  in `/core/field_input.ts` to return `HTMLInputElement` instead of `HTMLElement`

### ISSUE THREAD

**Issue by btw17** [google/blockly#7253]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

This is a minor note, though in `/core/field_input.ts` we always know that the type info is of type `HTMLInputElement`, which is an `HTMLElement` but with more input-specific stuff. The proper type info should be returned so that input-specific manipulations of the element can be done.

### Request

1) Please update the return type info from  `HTMLElement` to  `HTMLInputElement` for [widgetCreate_](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/field_input.ts#L351) in `/core/field_input.ts`! 😁
2) Remove the `as HTMLInputElement` cast in [showInlineEditor](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/field_input.ts#L334C10-L334C20).

**Comment by saymedgm** [comment]
@maribethb I know how to solve this please assign me this issue

**Comment by saymedgm** [comment]
@BeksOmega can you assign me this issue

**Comment by BeksOmega** [comment]
Hello @saymedgm ! This issue is actually being saved for an event we're running called [Grace Hopper Open Source Day](https://anitab-org.github.io/open-source-day/)! It is meant to help young girls and non-binary technologists make their first contributions to open source =)

If you still want to contribute we have some good [help wanted issues](https://github.com/google/blockly/labels/help%20wanted) that are open for contribution! Just make sure they're /not/ tagged with ghc-osd.

**Comment by aku1310** [comment]
Hey, I am interested to work on this issue. Can it please be assigned to me?

**Comment by BeksOmega** [comment]
Go for it @aku1310 !
