### ISSUE TITLE
Blockly.Field property documentation malformed

### ISSUE THREAD

**Issue by ball-of-twine** [google/blockly#7315]
### Location

https://developers.google.com/blockly/reference/js/blockly.field_class

### Type

- [X] Text
- [ ] Image or Gif
- [ ] Other

### Suggested content

In Blockly.Field class, the description of property DEFAULT_VALUE ([link](https://github.com/google/blockly/blob/06ba992206090b1eade12577ce01164f1af2b486/core/field.ts#L77C1-L77C1)) contains a code block (` ``` `) that breaks [the generated documentation](https://developers.google.com/blockly/reference/js/blockly.field_class#properties). The code block closes the property \<table> and the subsequent properties are displayed in pipe-concatenated strings (see screenshot).
![image](https://github.com/google/blockly/assets/55562516/78e27a56-8f68-452a-a35d-833ef4b7a2b0)

The generated documentation should look like this:
![image](https://github.com/google/blockly/assets/55562516/2d6bc470-2c95-4043-ae0d-f1bc59e589c3)

### Additional context

Could be an issue with api-documenter or api-extractor.
One solution would be to try replacing the example code block with single-backtick inline code, or the example could just be plain text.

**Comment by maribethb** [comment]
Hi @ball-of-twine , thanks for reporting! We'd accept a PR for this if you'd like to fix it. The documentation comes from the inline documentation on the method, and you can check the generated markdown by running `npm run docs`. Switching to single backtick should be fine.

Otherwise this issue will be added to our general backlog. Thanks!
