### ISSUE TITLE
Avoid using data: images

### ISSUE THREAD

**Issue by hochhaus** [google/blockly#735]
Currently blockly [uses](https://github.com/google/blockly/blob/master/blocks/text.js#L66) one `data:` image (in Blockly.Blocks['text'].newQuote_) which is hard coded in the JS. This causes problems for users who have strict Content-Security-Policies (CSP) which disallow `data:` URLs in img-src (eg: `img-src 'self';`).

The rest of the blockly resources are configurable via the awesome `media:` configuration option and therefore are easily self hostable with a strict CSP. Converting the `newQuote` image to be served in the same manner as the other resources (eg: the `media/` directory) would be ideal.

**Comment by NeilFraser** [comment]
Those quotes are already in the media directory, see quote0.png and quote1.png.  Just add this code to your program after Blockly's block file is loaded:
```
Blockly.Blocks['text'].newQuote_: function(open) {
  var file = this.workspace.options.pathToMedia +
      (open == this.RTL ? 'quote0.png' :  'quote1.png');
  return new Blockly.FieldImage(file, 12, 12, '"');
}
Blockly.Blocks['text_join'].newQuote_: Blockly.Blocks['text'].newQuote_;
Blockly.Blocks['text_prompt'].newQuote_: Blockly.Blocks['text'].newQuote_;
```

I don't think we want to change Blockly itself to remove data URLs since they provide a nicer experience for most users.  You are the first person to report problems with a CSP.  We'll keep an eye on this going forward.
