### ISSUE TITLE
blocks behind toolbox while dragging to delete

### ISSUE THREAD

**Issue by rockyxia** [google/blockly#7354]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Dragging a blocklyDraggable element onto a blocklyToolboxDiv element will be obstructed by blocklyToolboxDiv, making it impossible to elevate the blocklyDraggable element level. Originally, raising the blocklyBlockDragSurface element level was sufficient. How can we solve this problem?

blocklyDraggable元素拖拽到blocklyToolboxDiv元素会被blocklyToolboxDiv遮挡，无法提升blocklyDraggable元素层级，原来通过提升blocklyBlockDragSurface元素层级即可，如何解决这个问题？

### Reproduction steps

Drag building blocks to toolbox

### Screenshots

![1691069485540](https://github.com/google/blockly/assets/8003658/a9f83fdb-8742-4204-a299-a48ed158846f)

### Browsers

Chrome desktop

**Comment by maribethb** [comment]
This happened as a result of removing the block drag surface. We removed that for performance reasons, so we don't want to add it back and give up the performance improvements. We will take a look soon to see if there's another way of solving this. Thank you for reporting!

**Comment by XJJ3** [comment]
This issue is very important, can we try to fix it as much as possible?

**Comment by rachel-fenichel** [comment]
This problem showed up because we stopped moving the block to a new surface during a drag. Normally the toolbox and flyout live in front of the blocks so that when you drag the workspace the blocks slide behind the toolbox/flyout. 

To fix this issue we might be able to change the z-index of the toolbox/flyout during a drag so that they sit above the workspace surface but below the block surface. Then at the end of the drag we could put it back.

**Comment by BeksOmega** [comment]
Blocks are also getting dragged behind the flyout toolbox: 
![Screen recording 2023-10-11 1 39 47 PM](https://github.com/google/blockly/assets/25440652/2d6805ec-20e8-4790-9b42-022ef1938913)

**Comment by BeksOmega** [comment]
I retested performance of adding blocks to the drag surface, and I don't think it had a signficant performance impact for individual blocks. (It had an impact for workspaces because we had to move all of the blocks.) We currently move blocks to the front of the block canvas when we start dragging them, so they get repainted in either scenario.

I think adding a drag surface for individual elements is the correct solution, rather than messing with the layering of flyouts and toolboxes.

How exactly this gets implemented depends on if we want to refactor layering more broadly or not.

**Comment by rachel-fenichel** [comment]
> I think adding a drag surface for individual elements is the correct solution, rather than messing with the layering of flyouts and toolboxes.

Since refactoring dragging and layering would be a much bigger project, and this is a user-visible regression, just add the drag surface directly (without changing other parts of layering).

**Comment by BeksOmega** [comment]
Turns out this is not a regression. Reproduces back to 2018: https://20181105-dot-blockly-demo.appspot.com/static/demos/toolbox/index.html

And the old CSS event documents it as being the intentional behavior:
```
.blocklyBlockDragSurface {
  display: none;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: visible !important;
  z-index: 50;  /* Display below toolbox, but above everything else. */
}
```
