### ISSUE TITLE
Sometimes parent block doesn't connect to input block

### ISSUE THREAD

**Issue by clementcontet** [google/blockly#7412]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When moving a parent block to connect to a compatible input block, sometimes it doesn't connect (and the input block gets moved away).

### Reproduction steps

1. Move parent block to input block.
2. The input block isn't connected and gets instead "pushed away"
On https://developers.google.com/blockly I've seen this behavior when the parent block is not the top dragged block (cf screenshot)

On https://google.github.io/blockly-samples/plugins/shadow-block-converter/test/ we can see that the connection is not done when the parent block already has a shadow block

And on SuperCodingBall, I had to "chase" the input block (cf screenshot)

### Screenshots

https://github.com/google/blockly/assets/7261426/a6e1d5ad-9a72-42b8-b810-b72d55accd6d

https://github.com/google/blockly/assets/7261426/91c9a89e-e6e5-47e5-aa88-5ddaddaa3508

### Browsers

Chrome desktop

**Comment by rachel-fenichel** [comment]
Hi Clement,

There are three different issues here.

The first one is that connections on blocks other than the parent block aren't available for connection during a drag. (The exception is the last next connection on a stack of blocks.) 

That behaviour is intentional. Imagine a stack of `set count to` blocks, all of which had empty inputs. If you dragged it toward a math block you would have a lot of valid connections that are very close to each other, resulting in blocks bouncing around as insertion markers appear and disappear and the dragged block resizes. Sticking to only connections on the top block being dragged helps avoid that case.

The second issue is that you can't drag a parent block with a shadow toward a child block and have them connect. This is also intentional. If we did it the other way, you could accidentally connect a parent to an existing block, which would wipe out a shadow. In general, the user has to drag the child block to the parent connection if there's any ambiguity about what connection to make.

The third issue is the block chasing that you show in your second recording. I'm going to split that into a separate issue to look at more.
