### ISSUE TITLE
non-movable blocks never generate click events

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#742]
This is reproducible on the Playground. If you import a block with movable="false" the block never generates a click event. It does generate a selected event, but click is broken.

**Comment by joe2236** [comment]
hi,
i have the same problem with the latest version but even more ...

my scenario is i want to have a fixed predefined workflow that allows the user to configure the blocks so that inputs and dropdowns in blocks can be set but no new block, moving, deleting.

therefore i do not show the toolbox and set all blocks to deletable="false", movable="false" and editable="true".
when using moveable="false" problem described by @RoboErikG happens.

**additionally** when using movable="false" in a "controls_if" block all sub blocks dont get any events even no selected events.
i have tried some old version from 17 Aug 2016 and there all of this is working correctly.

**Comment by rachel-fenichel** [comment]
Fixed by #1078
