### ISSUE TITLE
In the case of multiple connected blocks, an acknowledgment mechanism is provided to drag away blocks

### ISSUE THREAD

**Issue by CaffeMrDe** [google/blockly#7456]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Problem

When multiple blocks are assembled and connected, dragging one of the blocks away separates the multiple block areas. When clicking and dragging quickly, it is easy to cause accidental deletion. I have a suggestion to avoid this misoperation by popping up a confirmation box when multiple blocks are already connected
![t1](https://github.com/google/blockly/assets/35086726/22796ffc-d5b3-4494-a2c9-65ec2718058d)

### Request

In the case of multiple blocks connected, a confirmation box pops up when dragging a block away from the connection aread。
Delete all fast popups like global popups。
![2023-09-04_170219](https://github.com/google/blockly/assets/35086726/9dccc34b-fdda-4bb8-8ef7-8c2e4dcdb329)

**Comment by rachel-fenichel** [comment]
Is the issue that blocks are getting deleted off the workspace, or just that they are getting disconnected during a drag?

In your video, the blocks that are getting dragged are disconnected from the parent block. This is the correct and expected behaviour. Are you suggesting a confirmation on every drag?

I'd also like to know more about your application. Is this for robotics?
