### ISSUE TITLE
Block missalignment when warning is added during drag

### ISSUE THREAD

**Issue by carlosperate** [google/blockly#75]
Hi,

When blocks are being drag and a warning is added to any of the blocks (therefore adding the warning icon), the blocks svg misaligns until they are reattached one by one.

As demo I have recorded this quick video of my fork, as I was not quite sure how to replicate the problem with normal blockly:
https://www.youtube.com/watch?v=csbsCaaR_So

**Comment by NeilFraser** [comment]
Fixed.  Having warning icons appear during a drag is not really helpful (since one can't open them to see the error at that time, and the warning may be resolved by the time the block drops).  Blockly now postpones changes to warnings until the block is dropped.  This solves the rendering problems too.

Thanks!
