### ISSUE TITLE
FieldDropdown limited to screen size

### ISSUE THREAD

**Issue by andrewfstratton** [google/blockly#751]
Can the field dropdown have a scroll bar added when the screen size is reached? This would also be better for small screens.

**Comment by NeilFraser** [comment]
This was first reported in 2012:
https://code.google.com/archive/p/blockly/issues/64
It got fixed.  But now it's broken again.

Furthermore, menus (both context and dropdown) are now adding scrollbars to the main page.  Just open a menu on the demo page:
https://blockly-demo.appspot.com/static/demos/fixed/index.html
That's behaviour I've not seen before.  This issue is a double regression.

**Comment by rachel-fenichel** [comment]
Fixed in 2018.
