### ISSUE TITLE
Remove `bump` script in `package.json`

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#7543]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Request

`bump` is very out of date:

`"bump": "npm --no-git-tag-version version 4.$(date +'%Y%m%d').0",`

It can just be deleted.

**Comment by SunMoon97** [comment]
Hello,

I'm new to the field of open-source contribution and would appreciate some guidance on approaching the following issue.I haven't started working on this issue yet and I'd like to learn how to approach it effectively. Any advice or suggestions would be greatly appreciated. Thank you for your time and assistance!

Best regards,

**Comment by alicialics** [comment]
Hi @SunMoon97,

In order to contribute a PR, you would follow the standard practice:
- Create a Fork
- Create a new branch in your fork
- Make a commit with your change
- Make a PR here

I am not sure where I can find the best guide for this workflow but here is an example: https://reflectoring.io/github-fork-and-pull/

For the change in particular you can search for the proposed string:
`"bump": "npm --no-git-tag-version version 4.$(date +'%Y%m%d').0",` and remove it from the codebase.  I'll leave it to you an exercise on how to do this.

**Comment by SunMoon97** [comment]
Thank you for the guide @alicialics . I removed the bump script from package.json ,can you please see to it and tell me what needs to be done more?

**Comment by rachel-fenichel** [comment]
Hi @SunMoon97, your next step is to create a pull request, [following the GitHub guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) on how to do it.

For more information on contributing to Blockly specifically, please take a look at our guides to [getting started contributing](https://developers.google.com/blockly/guides/contribute/get-started), [writing a good PR](https://developers.google.com/blockly/guides/contribute/get-started/write_a_good_pr).

**Comment by SunMoon97** [comment]
Thanks for merging the pr.Can you suggest some other good first issues?

**Comment by alicialics** [comment]
> Thanks for merging the pr.Can you suggest some other good first issues?

check out https://github.com/google/blockly/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
