### ISSUE TITLE
function with a chinese name the generate code is not correct

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#7569]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

![image](https://github.com/google/blockly/assets/42778/5f844496-83dc-4a25-a24a-f70ec6e84675)

above pic show  the issue ,if define with a chinese name it will not generate ths chinese function it will give your an encode words

test with v9.2.1
### Reproduction steps

1. 
2. 
3.

**Comment by BeksOmega** [comment]
Hello! This is working as intended: https://developers.google.com/blockly/guides/create-custom-blocks/code-generation/fields#variables

> Variables are entered by the user in their language of choice. This means they may need to be converted to ASCII characters. For example, "متغير" would get converted to "_D9_85_D8_AA_D8_BA_D9_8A_D8_B1".

We do this because most languages do not support non-ASCII characters. However, JavaScript does in some cases! So if you want you can create your own logic for converting between variable models and final variable names. The logic that does this in core lives [here](https://github.com/google/blockly/blob/9c7c71ad879a62e285d97236e1c6907287463251/core/names.ts#L136).
