### ISSUE TITLE
Feature request: highlight matching functions when selected

### ISSUE THREAD

**Issue by drigz** [google/blockly#759]
When you select a function definition, the function definition is highlighted:

![image](https://cloud.githubusercontent.com/assets/632207/20829817/04254a90-b87e-11e6-94ef-c37a3ab0b98c.png)

A user suggested to me that it would be helpful to highlight where the function is used too. This could also make it easier to find the definition when you select the function-call block. Do we have a way of highlighting other blocks in a different colour?

For example, IntelliJ does this:

![image](https://cloud.githubusercontent.com/assets/632207/20829749/b76b0a8c-b87d-11e6-8b22-753d404c5974.png)

**Comment by NeilFraser** [comment]
workspace.highlightBlock or block.setHighlighted might be a good way to implement this.  Note that a *selected* block has an orange border and indicates a block being edited, whereas a *highlighted* block is a lighter colour and normally indicates a block being executed.  There can only be one selected block, but any number of blocks may be highlighted.

**Comment by drigz** [comment]
Thanks for the suggestion. I tried it out, and it looks like this:

![image](https://cloud.githubusercontent.com/assets/632207/20830535/31717fde-b881-11e6-99f1-189230912fb9.png)

Is this functionality you'd consider for upstream Blockly, or something that downstream projects should implement if they want it?

**Comment by bkisdi** [comment]
By the way: variables (both setters and getters) could be highlighted as well on selecting a setter or getter (not respectively).

**Comment by NeilFraser** [comment]
Good point @bkisdi .  Also, right-clicking on a function call offers to "Highlight function definition" (bad terminology, it's actually 'selected').  Maybe this option should be deleted, and the function definition just be highlighted automatically.

My concern with using highlight is that highlight is also used for showing program execution.  So what happens if a program is running and a variable or function is selected?  Does all highlighting get cleared the next time the program steps?  This looks like a very messy path.

Does this mean we need *selected* (block being edited), *highlighted* (block(s) being executed), and *referenced* (block(s) related to selected block)?  Such a complicated UI...

**Comment by bkisdi** [comment]
For functions I propose a "Go to function definition" instead of the current one, which should select **and scroll into view**_ the function block - a simple highlight is not practical enough in most cases. (Perhaps this is an other Feature request.)

Program execution is a different (mental) state. I hope the workspace is not editable during execution (and no confusion), is it? If it is, then your _referenced_ color can be a solution.

For variables, automatic highlight can cause ugly flickering - I propose new menu points like "Highlight 
setters" and "Highlight references", or whaterever is your terminology. Also for functions I'd modify the OP of **drigz** with a "Highlight references" menu point instead of automatic highlight. Or it can be configured.

The highlight remains while the original block is selected - or later? Till the next modification or the next similar menu command?

**Comment by rachel-fenichel** [comment]
> Program execution is a different (mental) state. I hope the workspace is not editable during execution (and no confusion), is it? If it is, then your referenced color can be a solution.

Editing code during execution is used by a variety of kids coding apps.  In particular, Scratch does this, so that kids can "tinker" with their code to get it right without having to restart it all.  So yes, this is something that we actively want to support.

**Comment by NeilFraser** [comment]
I built of a partial implementation of reference highlighting (functions, variables, flow control).  But although it sounds like a good idea, the UX just felt too random.  Blocks highlighting without a clear indication why, lots of visual noise.  For users who write Blockly programs for a living, this would probably be helpful.  But for more casual users I believe that reference highlighting is just too confusing.  I've talked with the rest of the team, and we agree that this just isn't right for Blockly.

That said, you can implement this yourself by watching the event stream and calling workspace.highlightBlock as needed.

**Comment by drigz** [comment]
Sounds like the right call - thanks for considering it!
