### ISSUE TITLE
RFE: Add method to search blocks

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#766]
Add a method to workspace that can search Block text and field values.

 - [ ] Add a method to Workspace to search instantiated blocks on the workspace.
 - [ ] Add a method to Toolbox to search template blocks.

Bonus work:
 - [ ] Allow searching unselected drop down options.
 - [ ] Allow searching tooltip text.

See thread https://groups.google.com/d/msg/blockly/5sL4oq6Ero8/HX9gpjl2CgAJ

**Comment by MikeSolvalou** [comment]
Hi @rachel-fenichel , @AnmAtAnm ,

We have done some work on searching the toolbox and workspace.
Our forked repository is here: https://github.com/raissanorth/blockly
A demo for the toolbox search can be found in demos/swen503/our-demo.html
A demo for the workspace search can be found in demos/workspace-search/index.html

Our demos use the unbuilt version of blockly. We have been unable to get any demos relying on the built version of blockly to work. We think this is because a new file we added, search.js, is not getting included by the Python script that builds everything.

The toolbox search interface is integrated into the blockly core, but the workspace search only includes backend methods that can be invoked from the browser console or by javascript outside of blockly.

Both of these search functions rely on the search method in block.js, which searches all text in a block, including tooltip text, but not unselected dropdown options.

We would welcome any feedback on our work.

Regards,

@MikeSolvalou
@debcrook
@gelboljohn
@oliverbmwilson
@raissanorth

**Comment by AnmAtAnm** [comment]
That's awesome. Super excited to see this come to life. It is so close to my mocks!

<img width="400" alt="screen shot 2017-03-02 at 8 54 25 am" src="https://cloud.githubusercontent.com/assets/9916202/23517707/fb2302c2-ff25-11e6-8330-a9ac5eae4421.png">

Some notes:
 * It seems like the toolbox demo doesn't search the text field strings. If I search bird, the relevant Jabberwocky block does show up.
 * The workspace search should include one of every fields.  Particularly missing is the dropdown. It makes sense to search unselected drop downs in the toolbox, because they can be presented as selected.  But workspace blocks should not be changed in response to a search; their unselected dropdown options should be excluded.
 * Obviously, we should add a  text field UI for toolboxes (probably with relevant XML), so we can show the word that was searched for.

We'll get back to you regarding the `build.py` issue.  I think I encountered it recently with extensions, but I forget the solution.

**Comment by AnmAtAnm** [comment]
Regarding the build error, it looks like you `goog.provide('Blockly.Search')`, but never `goog.require('Blockly.Search')` in any other file.  Thus, it get left out of the dependency tree.

Also, I suggest reading up on the [Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html) before any pull request.

**Comment by ividovic** [comment]
Dear MikeSolvalou,

what are the necessary steps to implement your search function to my Blockly application?

Best regards

**Comment by ividovic** [comment]
Thank you for your reply.

I will contact them and check repo.

Anyway, how can I add your proof of concept to the demo?

Best regards

2018-05-26 3:21 GMT+02:00 Raissa North <notifications@github.com>:

**Comment by rachel-fenichel** [comment]
Closing in favor of https://github.com/google/blockly-samples/issues/242
