### ISSUE TITLE
Nested Categories with `registerToolboxCategoryCallback`

### ISSUE THREAD

**Issue by tjosten** [google/blockly#7666]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

I have made the observation that it does not seem to be possible to return a nested category from `registerToolboxCategoryCallback`.

When discussing this in the [mailing list](https://groups.google.com/g/blockly/c/OROgRcOTp6g), I was advised to add an issue about this.

### Reproduction steps

Use `registerToolboxCategoryCallback` and respond with the following code:

```
{
      kind: "CATEGORY",
      name: "Main Category",
      contents: [
            {
                  kind: "CATEGORY",
                  name: "Sub Category 1",
                  contents: [ { …blocks… } ]
            }
      ]
}
```

Other than one would expect, this (nested categories) does not work when being used with a toolbox category callback, but does perfectly when when being used with `updateToolbox` or `Blockly.inject`.

**Comment by cpcallen** [comment]
Observations from investigation of issue as reported in the Blockly group:

* The proximate cause is that the custom category callback is only called from `Flyout.prototype.getDynamicCategoryContents`, all calls to which are ultimately via `.show` (both in `core/flyout_base.ts`), so any dynamically-generated subcategories are not known about until the dynamic category itself is opened, and therefore cannot be included in the list of categories in the toolbox.
* [Slight aside:] It looks like the existing machinery in `Flyout` ends up calling `.getDynamicCategoryContents` (and thus the callback itself) more than once, which—aside from being inefficient—creates the risk of the callback returning inconsistent values.  While the category contents obvious needs to be refreshed from time to time it would be wise to call the callback only once per refresh.
* At the moment it is only necessary to refresh the dynamic category (by calling the supplied callback) when the category is opened at at certain other well-defined points in time (e.g. when new variables are created).  To support subcategories we'll need to think very carefully about when else it will be necessary: when the toolbox is initially rendered, at least, and at any time that the returned subcategories might change.

**Comment by maribethb** [comment]
This callback is used to populate the flyout that opens when a category is clicked. The flyout itself cannot contain categories. Subcategories are still rendered in the main toolbox, not the flyout. So in my opinion this would be a feature request and not a bug report.

If you want to update the toolbox to include new subcategories, you can call `updateToolbox` when the categories change. In fact, if your category does contain both blocks and subcategories, I think you could even call `updateToolbox` from within the callback (which would show the blocks in the flyout via the standard dynamic category mechanism and as a side effect also update the main toolbox). I haven't tested that though, and I don't know what would happen if the blocks list you return is empty and you *only* call `updateToolbox` at that time.

Does calling `updateToolbox` instead of using a dynamic category work for you? If not, please explain why not. We'll triage this issue soon but it is unlikely to be added to our upcoming projects without a compelling use case that we do not alreayd have a solution for.
