### ISSUE TITLE
All mutators have broken workspace coordinates.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#7677]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

The root block for all mutators appears over the toolbox.  LTR only.

### Reproduction steps

1. Open a mutator bubble.

### Screenshots

<img width="218" alt="Screenshot 2023-12-01 at 20 48 12" src="https://github.com/google/blockly/assets/250480/8e881047-be69-4876-8583-4e4ed7ed1be0">

**Comment by BeksOmega** [comment]
I /think/ the issue is that I deleted code [here](https://github.com/google/blockly/pull/7634/files#r1385439054) because I thought we always update the metrics of the workspace immediately.

But apparently the updating of the metrics is handled by the scrollbars, and mutators don't have scrollbars. Not sure if I'm going to add the code back or actually fix it so the logic doesn't need to go through the scrollbars.
