### ISSUE TITLE
Blocks can connect to blocks under the flyout instead of being deleted

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#780]
When dragging a block to the flyout to delete it, if there's a block underneath with the right connection type, blockly makes it look like the block will be deleted on drop (you see the X mouse cursor), but it actually just connects.

**Comment by NeilFraser** [comment]
This was intentional.  Consider this sequence:
https://www.youtube.com/watch?v=Qbwy27NGWfs
(Note that the screen recording lies about the mouse cursor status.)  Connecting is the safer option, and I believe the one that's more expected when editing happens to take place around delete areas.

That said, it would be nice if the X mouse cursor would disappear during a connection even if over a delete area.  And the lid of the trashcan should probably close too.  But I'd advise against fixing this bug by deleting the block.

**Comment by rachel-fenichel** [comment]
Hey Neil,

I've looked at this and I think the correct behaviour is to connect if it would otherwise land in the trash, but to delete if the cursor is over the flyout.

This is a much bigger issue now because we're finally managing to put the flyout in front of the workspace, and because scratch has an always open flyout and a movable workspace.

I agree that we're currently doing the right thing with the trash can.
