### ISSUE TITLE
domToWorkspace() or serialization.load() is slow when having ~6K blocks

### ISSUE THREAD

**Issue by mrkprdo** [google/blockly#7805]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Problem

loading ~6K blocks into workspace is making domToWorkspace() or serialization.load() to take around ~30s. 

### Request

Can we make those calls allow asynchronous loading of blocks...
IE. i can split my blocks into their respective root parent block group, then each group can be loaded using promise and promise.all() till all groups are done. 

### Alternatives considered

Tried exploring serialization for JSON or XML and nothing seems to provide faster approach.
If there is some ways to efficiently load many-many blocks at once, please let me know.
Thanks.

**Comment by maribethb** [comment]
Hello,

In general Blockly is not designed to handle this many blocks at once. We recommend that you find a way to have fewer blocks on a single workspace at once, such as by introducing multiple workspaces that can interact to simulate having multiple "files" in a text-based program.

So that said, you can try splitting up loading yourself. You can already load an individual block using the blocks serializer rather than the workspace serializer. But that would be something you'd need to implement on your side, not something we'd do on our end. 

Please consider posting in the forum if you'd like additional discussion on how to handle very large workspaces. Thanks!
