### ISSUE TITLE
Dancing blocks with Zelos in 10.4

### ISSUE THREAD

**Issue by clementcontet** [google/blockly#7898]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

With the new connection preview feature, inserting big blocks in Zelos can be very disturbing/hard :(

### Reproduction steps

Tested in local playground

### Screenshots

https://github.com/google/blockly/assets/7261426/c097dbf6-2699-442e-b2d4-86db132ea3a2

### Browsers

Chrome desktop

**Comment by BeksOmega** [comment]
Darn, I tested this before releasing but I didn't test this with taller blocks :/ I think the simplest  solution here is to make sure connection locations are static (the magenta dots in the following recording). Right now they're always positioned at the middle of the connection, which changes when the insertion marker is attached.

![Screen recording 2024-03-04 2 02 26 PM](https://github.com/google/blockly/assets/25440652/decb41e6-5f0f-4d93-819c-2c3ceb841468)

**Comment by clementcontet** [comment]
Hi, setting the connection locations on top would sure fix the issue, but it is quite a drastic change in UX (users would have to align the top of the dragged block to the top of the parent block connection).

Currently, when an insertion marker appears (and is bigger than the former connection), the parent block grows but its top position is fixed.
Maybe we could let the parent block grow, but shift it to the top, so that the insertion marker stays "middle vertically aligned" with the former connection, and thus the dragged block?

**Comment by BeksOmega** [comment]
> Currently, when an insertion marker appears (and is bigger than the former connection), the parent block grows but its top position is fixed. Maybe we could let the parent block grow, but shift it to the top, so that the insertion marker stays "middle vertically aligned" with the former connection, and thus the dragged block?

Just to make sure I'm understanding, you mean move the parent block so that the connection stays in the same relative position?

If that's the case, I'm not sure that makes sense e.g. if you're inserting into a large stack of blocks, it would have to move the whole stack, which might throw your different stacks out of alignment.

**Comment by clementcontet** [comment]
Yes that was my idea, but I agree it's a complex UX problem and nothing seems to be ideal :(

When you insert into a stack of blocks, they are already moving to the bottom:

https://github.com/google/blockly/assets/7261426/229c408d-c599-4c05-ae86-61af39c83523

Maybe blocks above the parent block could move to the top and blocks below move to the bottom? (so that the insertion marker middle stays aligned with the connection middle)

**Comment by BeksOmega** [comment]
Put up #7899 which fixes this issue by reverting back to the previous behavior, which just highlights inputs without adding the insertion markers.

I think the ideal solution would be to have the block dragger (or the `IDraggable` in the future) track how far away the connection is after the connection preview is created. If it is farther away, make it so that you have to move farther away than that (+ some extra padding) before the connection unpreviews.

Once that is implemented, we can turn insertion markers back on for zelos inputs.
