### ISSUE TITLE
check lint settings for tsdoc params

### ISSUE THREAD

**Issue by maribethb** [google/blockly#8014]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

We use api-documenter to generate reference documentation for blockly. It reads the tsdoc and generates the md files we have on devsite.

For functions, we're somewhat lax in the lint rules about what you have to document. If you have a well-named parameter you don't need to write a redundant description for it. But I'm 99% sure that in order for that to param to show up in the generated reference docs, it at least needs to be mentioned in the tsdoc by name

```
/**
 * Calculates the area of a rectangle.
 * @param width
 * @param height
 * @returns area
 */
function getArea(width, height) {}
```

Our lint settings need to be set up so that the name of the parameter is required but a description is not.

I haven't verified this issue yet, so two assumptions need to be checked:
1) that api-documenter requires the param to be listed in tsdoc
2) that our lint settings are not already set this way

### Reproduction steps

1. 
2. 
3.

**Comment by gonfunko** [comment]
Parameters do not have to be included in the docstring to be included in the docs; see for example https://developers.google.com/blockly/reference/js/blockly.workspacesvg_class.createdom_1_method, which includes the `injectionDiv` argument, even though [that argument is not referenced in the TSDoc](https://github.com/google/blockly/blob/9a7de53029afc09dfc9d055a4eae40b316728455/core/workspace_svg.ts#L730-L737). Closing since everything appears to be working fine here.
