### ISSUE TITLE
Color surounding of input based on type

### ISSUE THREAD

**Issue by tobiasBora** [google/blockly#8145]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

It can sometimes be confusing for a beginner to know which type is expected by an input (integer/string/…). 

### Request

As such, it would help if it would be possible to, somehow, add a color around the node (this color would match the color of the category for instance). Not sure what would be the pretiest option, but I can think of simply changing the color of the stoke like:

![image](https://github.com/google/blockly/assets/2164118/4f774908-a6a7-4534-a395-4a31c3c5b72d)

I also tried:

![image](https://github.com/google/blockly/assets/2164118/0f0dc7b9-1c79-48d0-ac5e-59ab672f9a77)

Not sure what you prefer.

### Alternatives considered

Write explicitly the type as a sentence, but fairly ugly and verbose.

**Comment by maribethb** [comment]
Hi! This isn't a feature we'd want to add directly to core, but it should be possible to do this with a custom renderer. Some projects use shape instead of color for a similar effect that is more colorblind-friendly. You can learn more in the custom renderer [codelab](https://blocklycodelabs.dev/codelabs/custom-renderer/index.html?index=..%2F..index#0). 

If you decide to try and implement this and run into roadblocks, please ask in the forum and we'd be happy to help figure out what you need. If it turns out additional APIs are needed in core to support this feature we could open feature requests at that time.
