### ISSUE TITLE
Error Generate Javascript after blockly Update

### ISSUE THREAD

**Issue by jogibear9988** [google/blockly#8181]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

I get the following exception after update to blockly 11.0.0

Uncaught (in promise) Error: JavaScript generator does not know how to generate code for block type "start_event".

My custom definition looks like this:

        //@ts-ignore
        Blockly.defineBlocksWithJsonArray([
            {
                'type': 'start_event',
                'message0': 'Event %1',
                'nextStatement': null,
                'style': 'hat_blocks',
                'args0': [
                    {
                      'type': 'field_variable',
                      'name': 'EVENTVAR',
                      'variable': 'event'
                    }
                  ],
            },
        ]);
        
        //@ts-ignore
        Blockly.JavaScript['start_event'] = function (block) {
            //@ts-ignore
            let name = Blockly.JavaScript.getVariableName(block.getField('EVENTVAR').variable.name);
            return name + ' = ' + 'eventData;\n';
        };

### Reproduction steps

1. look at my code

### Stack trace

```shell
blockly_compressed.js:1393 Uncaught (in promise) Error: JavaScript generator does not know how to generate code for block type "start_event".
    at JavascriptGenerator$$module$build$src$generators$javascript$javascript_generator.blockToCode (blockly_compressed.js:1393:174)
    at JavascriptGenerator$$module$build$src$generators$javascript$javascript_generator.workspaceToCode (blockly_compressed.js:1391:236)
    at generateEventCodeFromBlockly (BlocklyJavascriptHelper.js:43:35)
    at WiredCombo.<anonymous> (ScriptSystem.js:227:62)
    at fireEvent (wired-base.js:76:7)
    at WiredCombo.fireSelected (wired-combo.js:276:9)
    at WiredCombo.onItemClick (wired-combo.js:270:14)
    at I.handleEvent (lit-html.js:6:6509)
```

### Browsers

Chrome desktop

**Comment by maribethb** [comment]
Hi, this is expected. Block-code generators should be defined as described [here](https://developers.google.com/blockly/guides/get-started/code-generation#block-code_generators); the format changed in v10. If you are coming from v10 you may have seen [deprecation warnings](https://github.com/google/blockly/blob/6a29acbe7a77213e1f62b6b79e52d7da805bae80/core/generator.ts#L260) about the style you were using. You will need to update your block-code generator functions to the format specified in the documentation now.

If you have additional questions about this, please post in the [forum](https://groups.google.com/g/blockly) instead. Replies to issues may be missed since this is working as intended.

**Comment by jogibear9988** [comment]
Thank for your help.

changeing: 

    //@ts-ignore
    Blockly.JavaScript['start_event'] = function (block) {
        //@ts-ignore
        let name = Blockly.JavaScript.getVariableName(block.getField('EVENTVAR').variable.name);
        return name + ' = ' + 'eventData;\n';
    };

to

    //@ts-ignore
    Blockly.JavaScript.forBlock['start_event'] = function (block) {
        //@ts-ignore
        let name = Blockly.JavaScript.getVariableName(block.getField('EVENTVAR').variable.name);
        return name + ' = ' + 'eventData;\n';
    };

fixes it
