### ISSUE TITLE
Surface workspace comments' IDs in the DOM

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8242]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

The workspace comments' IDs should be in the dom so that the multiselect plugin can figure out which comments are being selected.

`getCommentById` should also be made public.

### Request

Add the comment's ID to a `data-id` attribute.

**Comment by changminbark** [comment]
Hello,

I am currently tasked with updating the multiselect plugin to allow for support in the selection of other draggables. I wanted to ask whether it is possible to make it so that id's for all draggable objects and corresponding workspace getById() methods are implemented in Blockly to allow for access to them. Currently, the plugin uses the workspace getById() method to access the draggable objects so that we can call methods like drag(), isMovable(), etc. If there is a different way of tackling this issue or there is a reason why these ID related methods should not be exposed to the public, please let me know.

I will try to look into this issue, but I am not sure I will have the time to. If there is anyone else who can look into this, that would be helpful!

**Comment by changminbark** [comment]
Another question I had regarding the workspace comments is: Why are the classes of the renderedWorkspaceComments of the 'blocklyComment blocklyEditable' classes and not the 'blocklyDraggable' class? Should it not include the 'blocklyDraggable' class if it is a draggable object?

**Comment by mark-friedman** [comment]
> I wanted to ask whether it is possible to make it so that id's for all draggable objects and corresponding workspace getById() methods are implemented in Blockly to allow for access to them.

FYI, [this comment](https://github.com/mit-cml/workspace-multiselect/pull/62#issuecomment-2209411042) has some info that I think would make this fairly simple.

**Comment by BeksOmega** [comment]
> Another question I had regarding the workspace comments is: Why are the classes of the renderedWorkspaceComments of the 'blocklyComment blocklyEditable' classes and not the 'blocklyDraggable' class? Should it not include the 'blocklyDraggable' class if it is a draggable object?

I split this off into a separate issue: https://github.com/google/blockly/issues/8253

**Comment by changminbark** [comment]
I want to tackle this issue. Thank you!

**Comment by changminbark** [comment]
I have fixed this in this PR: https://github.com/google/blockly/pull/8358
