### ISSUE TITLE
Unexpected snap close to the "colour with" block

### ISSUE THREAD

**Issue by carlosperate** [google/blockly#83]
I don't know if this happens with other blocks as well, but for the "colour with" block I've found a weird snap when the block is close to the first input. If we try to drop a block as shown in this screenshot:
![snap1](https://cloud.githubusercontent.com/assets/4189262/6632215/6306a526-c92a-11e4-9272-de8b952dfe7f.png)

It ends up snapping to the grid right below the one expected. You can see it animate towards the top position, but it intermediately moves to the one square below:
![snap2](https://cloud.githubusercontent.com/assets/4189262/6632216/630b2a7e-c92a-11e4-8dce-cad8094ea33a.png)

This does not happen with the current version in https://blockly-demo.appspot.com/static/demos/code/index.html , so probably something to do with the latest commits in master.

**Comment by NeilFraser** [comment]
Although unexpected, this behaviour is correct.  The issue is that Blockly does not want two blocks to look like they are connected, when they are not.  In your case, you drop the number block, the grid pulls it closer to the colour block, the distance is now (barely) within the threshold of "looking connected" so the number block is pushed away diagonally.

**Comment by carlosperate** [comment]
Makes sense, thanks for the clarification.
