### ISSUE TITLE
Can't re-enable "disabled orphaned blocks" after migration to v11

### ISSUE THREAD

**Issue by clementcontet** [google/blockly#8310]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

My app disable automatically blocks that are orphaned (through `workspace.addChangeListener(Events.disableOrphans)`), and it is the only way to disable blocks (I have `options.disable = false`).

When loading a workspace that have been generated with v10, v11 automatically set the `disabledReasons` to `MANUALLY_DISABLED` (see https://github.com/google/blockly/issues/8095), but the users can't re-enable them (because of the `options.disable = false`).

I can't see a good solution to this issue :(

**Comment by johnnesky** [comment]
Ah, I hadn't considered this case, thanks for the bug report!

I talked with Beka and she suggested that the https://www.npmjs.com/package/@blockly/disable-top-blocks plugin might help unblock your users. If you allow disabling in the workspace and add this plugin, users will be able to use the right-click context menu to enable and disable blocks but only when they're not currently orphaned.

Otherwise, you can wait for me to implement a workaround. I think that when any disabled reason is removed, and the workspace is configured to not allow manually disabling/enabling, and the block is currently marked as manually disabled, then the manually disabled reason should be removed in addition to the reason that initiated the change.

**Comment by clementcontet** [comment]
Hi, thanks for the investigation and quick fix!
I'll wait for the next release 😀
