### ISSUE TITLE
Blocks in mutators are behind the flyout

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#843]
![4ae417b7-8bd1-461e-9657-0da5d9c64842](https://cloud.githubusercontent.com/assets/13686399/22126030/ec821a56-de4a-11e6-81b0-7c8be45bf596.gif)

**Comment by picklesrus** [comment]
Some background in case it is useful:  This was a known tradeoff made to get the performance improvements from the recent work on drag surfaces.  To turn mutator flyouts into their own <svg> instead of children of the workspace <svg> requires untangling the fact that zoom in mutators works because of a scale attribute on a parent element.  This isn't necessarily the only way to fix this bug though.

**Comment by picklesrus** [comment]
Fixed in develop.
