### ISSUE TITLE
Browser test toolbox_drag_test fails in Drag category because of drag_to_dupe block

### ISSUE THREAD

**Issue by johnnesky** [google/blockly#8466]
### Description

The `toolbox_drag_test.mjs` file fails when testing the `'Drag'` category because it's using the set of blocks defined by the `dev-tools` plugin which includes a custom block type called `drag_to_dupe` which automatically duplicates itself upon being dragged to the workspace, whereas the test is attempting to verify that all blocks in the toolbox add exactly one block to the workspace upon being dragged. The `drag_to_dupe` block was added in: https://github.com/google/blockly-samples/pull/2377

### Reproduction steps

1. Run `npm run test:browser`
2. The test fails.

**Comment by abhinavjha0239** [comment]
@johnnesky I wanted to work on this issue can you please assign it to me

**Comment by BeksOmega** [comment]
Sorry @abhinavjha0239 this isn't open for contributions yet because we're not sure how we want to fix it!

**Comment by cpcallen** [comment]
After discussing with @BeksOmega we think this should be fixed by removing the whole Drag category from the blocks tested by `toolbox_drag_test.mjs`, since each of the blocks in this category has a separate instruction about how it should be dragged.

(We should probably write an automated test to do that, too, but that's out of scope for this issue.)

**Comment by BeksOmega** [comment]
@abhinavjha0239 Are you still interested in working on this now that we've figured out the desired behavior?

**Comment by abhinavjha0239** [comment]
@BeksOmega yes I am interested in working on it
