### ISSUE TITLE
Bootstrap+Blockly: dragsurface rendering

### ISSUE THREAD

**Issue by GarrusVakarian** [google/blockly#864]
Using Blockly in a Twitter Bootstrap-enabled web page will only render the initial canvas (i.e. the workspace from coordinates [0,0] to [workspace.width, workspace.height]) while dragging the workspace surface. 

You can replicate this issue by opening the Blockly [JavaScript code generation demo](https://blockly-demo.appspot.com/static/demos/generator/index.html), opening your browser's developer console, navigating to the HTML code and pasting the following three lines into the <head> section:

```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
```
![HTML example](http://i.imgur.com/hd3YqVy.png)

If everything goes as planned, the layout of the page should have changed slightly, most noticeably the header text. Now, to witness the compatibility issue, move the existing block outside of the boundaries of the initial canvas. Any which way will do, just make sure you don't accidentally delete the block.

![HTML example](http://i.imgur.com/Xl7zBFD.png)

Now, when you attempt to drag the workspace, you will notice that the moment you click the left mouse button, part of the block seems to simply vanish. Depending on where you placed the block, it may even disappear completely while dragging. As soon as you let go of the left mouse button, the block will be restored.

![HTML example](http://i.imgur.com/zuUGdww.png)

While I don't know what part of Bootstrap may be causing this, the issue can traced to the following code in blockly/core/workspace_svg.js and blockly/core/workspace_drag_surface_svg.js respectively.

```javascript
Blockly.WorkspaceSvg.prototype.setupDragSurface = function() {
  // Don't do anything if we aren't using a drag surface.
  if (!this.useWorkspaceDragSurface_) {
    return;
  }

  this.isDragSurfaceActive_ = true;

  // Figure out where we want to put the canvas back.  The order
  // in the is important because things are layered.
  var previousElement = this.svgBlockCanvas_.previousSibling;
  var width = this.getParentSvg().getAttribute("width")
  var height = this.getParentSvg().getAttribute("height")
  var coord = Blockly.utils.getRelativeXY(this.svgBlockCanvas_);
  this.workspaceDragSurface_.setContentsAndShow(this.svgBlockCanvas_,
      this.svgBubbleCanvas_, previousElement, width, height, this.scale);
  this.workspaceDragSurface_.translateSurface(coord.x, coord.y);
};
```
```javascript
Blockly.workspaceDragSurfaceSvg.prototype.setContentsAndShow = function(
    blockCanvas, bubbleCanvas, previousSibling, width, height, scale) {
  goog.asserts.assert(this.SVG_.childNodes.length == 0,
    'Already dragging a block.');
  this.previousSibling_ = previousSibling;
  // Make sure the blocks and bubble canvas are scaled appropriately.
  blockCanvas.setAttribute('transform', 'translate(0, 0) scale(' + scale + ')');
  bubbleCanvas.setAttribute('transform',
    'translate(0, 0) scale(' + scale + ')');
  this.SVG_.setAttribute('width', width);
  this.SVG_.setAttribute('height', height);
  this.SVG_.appendChild(blockCanvas);
  this.SVG_.appendChild(bubbleCanvas);
  this.SVG_.style.display = 'block';
};
```

Setting the workspace's useWorkspaceDragSurface_ member to false seems to remedy the issue, yet I am unsure of what other effects this may or may not have. To me, it seems like a temporary solution instead of a permanent fix.

**Comment by picklesrus** [comment]
I don't know anything about using bootstrap, but I believe what is causing the problem is the 
"svg:not(:root){overflow:hidden}" bit in https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css.

Blockly's css specifies overflow: visible on the drag surface <svg> https://github.com/google/blockly/blob/master/core/css.js#L165 and my guess it is overridden by the bootstrap css.

The appearing/disappearing you're seeing makes sense because when a workspace drag starts (on mouse down) the parts of blockly that are about to move are moved over to the drag surface and translated using style's translate3d (instead of the svg transform attributes because it avoids a lot of repainting). Then, on mouse up they're moved back to the main svg.  I think what's happening is the drag surface's overflow is hidden by the bootstrap css so the blocks appear to disappear when they're in the negative coordinate space.
 
If you override that blocklyWsDragSurface class linked above after the bootstrap css is loaded or maybe add a !important to the overflow:visible , does that solve the problem?

**Comment by GarrusVakarian** [comment]
Adding a simple !important to the blocklyWsDragSurface CSS class's overflow property seems to fix the issue.

Tested by appending the following line to the DOM's head element, post Bootstrap inclusion.
```html
<style type="text/css"> .blocklyWsDragSurface{ overflow: visible !important;} </style>
```

**Comment by stevekrouse** [comment]
That worked great! Thanks @GarrusVakarian 👍

**Comment by mburgess1983** [comment]
Works great, have saved my day!
