### ISSUE TITLE
Minimap demo

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#924]
This demo should be similar to the mirror demo, but the secondary Blockly instance should be smaller and should always show the full extent of the workspace.

The minimap should have a box outlining the currently visible area of the main workspace.
Clicking and dragging on the minimap should move the main workspace to match.

This would live in the demos folder.

**Comment by picklesrus** [comment]
Some more context with some code pointers to get started:

For complicated workspaces with lots and lots of blocks it can be difficult to navigate the infinite workspace.  While zooming in and out is possible, it can be clunky.  An alternate possibility is to show a clickable mini map (https://en.wikipedia.org/wiki/Mini-map) that allows you to jump to other parts of the workspace.

Blockly's [mirror demo](https://blockly-demo.appspot.com/static/demos/mirror/index.html)), which takes advantage of Blockly Events, is, functionality wise, actually very similar to what you'd need to build a mini map. since the mini map would be just be a smaller version of the mirrored workspace.

 It would "mirror" the workspace in the same way that the mirror demo does (code [here](https://github.com/google/blockly/blob/master/demos/mirror/index.html):  but it would be smaller and more zoomed out.  The [zoomToFit function](https://github.com/google/blockly/blob/f5f6d69d5ef86d92e249054004c39690b0961f61/core/workspace_svg.js#L1399) on the workspace would come in handy to help fit all the blocks in the mini map.

When the user moves the rectangle on the minimap, we could transform the coordinates of the rectangle into the main workspace's coordinate system and tell the scrollbars to move.  ScrollbarPair's [set(x,y) function](https://github.com/google/blockly/blob/f5f6d69d5ef86d92e249054004c39690b0961f61/core/scrollbar.js#L138) might be useful here as it adjusts scrollbars and the contents of the workspace along with it.

A potential starting point to see how all the pieces fit together might be to take the existing mirror demo and modify to:
1. make the main workspace scrollable (look at the options passed to inject)
2. set the zoom level on the mirrored workspace to be at the most zoomed out level (also configurable through the options passed to inject)
3. make a click handler on the mirror workspace that draws a rectangle around the click each time the mirror demo is clicked
4. Use that click handler to adjust the scrollbars on the main workspace.

**Comment by K-ran** [comment]
Hi. I did work on this minimap and thought that should get some reviews before a pull request.
Here is a demo of what I made: https://k-ran.github.io/blockly/demos/minimap/index.html
I made some changes in workspace and scrollbar code to make a `scrollChangelistener.` Here:
https://github.com/K-ran/k-ran.github.io/blob/master/blockly/core/scrollbar.js#L805-L809
https://github.com/K-ran/k-ran.github.io/blob/master/blockly/core/workspace.js#L497-L523

Also I tried making the rectangle scroll able by using `mapDraggar.addEventListener('drag',callback) ` below [this](https://github.com/K-ran/k-ran.github.io/blob/master/blockly/demos/minimap/minimap.js#L74l) but its not triggered.

**Comment by picklesrus** [comment]
This is great progress!  It is exciting to see it take shape.

First, about the drag event:  Are you using the drag and drop web api (https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) I didn't look at your Minimap class super closely, but I get the impression that maybe not? I'd think you'd have to set up the rectangle to be draggable to get a drag event.  Before I did use that api, I'd look to see if it is well supported across browsers, though it is certainly fine to use for a proof of concept.

As for the methods you're adding to blockly: They're concise and isolated which is great. However, I'm concerned about introducing the this into the Blockly api as is. I want to think through other use cases that might need to know about the workspace moving and what they would need from the api. For example, we might decide it would be better to create a new workspace move Event and fire that instead.  There are some considerations with regards to how we'd do something like this for android and iOS that I'd like to discuss with some folks before settling on the api change too.  For now, because javascript is quite... flexible? forgiving?... what if you just put these new methods in your minimap file? If we're looking for something to put here https://blockly-demo.appspot.com/static/demos/index.html to show developers how to create a minimap, I think that would be a good enough start.

**Comment by K-ran** [comment]
Updated demo: https://k-ran.github.io/blockly/demos/minimap/index.html
@picklesrus The drag and drop api was not working on svg images (here referring to the rect), no idea why. But I coded a simple drag and drop functionality using the javascript's mouse events. And its working like a charm. 
Regarding changing the Blockly api for scroll listener, I brought all all changes in the [minimap.js](https://github.com/K-ran/k-ran.github.io/blob/master/blockly/demos/minimap/minimap.js), Blockly api is untouched. But [this](https://github.com/K-ran/k-ran.github.io/blob/master/blockly/demos/minimap/minimap.js#L43) ( it was a bit painful to do so) will change when Blockly has proper ui event handling.
Also I dont't know what to do about the icon so I made [this](https://github.com/K-ran/k-ran.github.io/blob/master/blockly/demos/minimap/icon.png) for the time being. 
Please review the demo/code and tell me should I go for a pull request.
Link to the demo: https://github.com/K-ran/k-ran.github.io/tree/master/blockly/demos/minimap

**Comment by picklesrus** [comment]
Great!
We haven't played with the drag and drop api much because caniuse.com claims it isn't supported on mobile browsers, so it is likely preferable that you didn't use it.

Yeah, I'd say go ahead and make a PR.  I think what we'll probably do while we sort out the API changes is put this in the demo directory and mark it as a work in progress.  Once the API issues are sorted out we can link to it from https://blockly-demo.appspot.com/static/demos/index.html.  As you noticed, we don't really want to encourage folks to do what you did for scrolling to make this work.  I haven't looked super closely at your minimap code, but you'll probably want to run lint on it - you can look at the .eslintrc in the root directory to see what rules we follow. Also, I think it makes sense to shrink the minimap in the vertical direction. In the demo it currently has the height of the entire workspace.

We're currently thinking of creating a UI event to indicate a viewport change and this will be a great use case to use to help iron out the details.

**Comment by BeksOmega** [comment]
Dupe of https://github.com/google/blockly-samples/issues/337
