### ISSUE TITLE
Possible missing module.exports in compressed file

### ISSUE THREAD

**Issue by justingeeslin** [google/blockly#955]
I noticed that `blocky_uncompressed.js` has a `module.exports` = `Blockly` while `blocky_compressed.js` does not have any `module exports`. Is this intentional -or might it be stripped out by the (closure) compiler by mistake?

**Comment by AnmAtAnm** [comment]
This is intentionally added by our `build.py` script, which is how we generate our _uncompressed and _compressed files.

[`build.py`, line 149](https://github.com/google/blockly/blob/592b2e1a518fe4a3b3c170fcea579cee8a63c3b5/build.py#L149)
```
if (isNodeJS) {
  window.BLOCKLY_BOOT()
  module.exports = Blockly;
```

(Looks like we're missing a semicolon.)

**Comment by justingeeslin** [comment]
Why is `module.exports` **not** present in the compressed file? Should only the uncompressed and not the compressed file be used when required using npm? Seems like these two files should be equivalent to one another..

**Comment by AnmAtAnm** [comment]
I see the code in question is just within the Gen_uncompressed class. I'm going to have to ask @carlosperate to chime in, since he added that. #237

If I may guess, in a node build environment, it makes little sense to run the compressed version. This is the one your are developing with and might want to track back to legible line numbers. Most often, the client-side code included in the NPM dependencies will be repackaged, including their own compression pass, with all included libraries.

**Comment by carlosperate** [comment]
Well, that specific PR was just adding an extra check to the existing `isNodeJS` flag, which was only present in the uncompressed version.
I've not really used headless blockly with node itself (the PR problem was that when a page with blockly was loaded in an electron "window" the old flag incorrectly though it was running in node), so I am not quite sure why the same wasn't also injected into the compressed version. The original PR adding this bit was https://github.com/google/blockly/pull/209.

**Comment by samelhusseini** [comment]
Our built files are now packaged into UMD modules which add the module.exports in there. Closing this issue.
