### ISSUE TITLE
Always-open flyouts scroll to the top as you type

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#990]
Typing in an input field (typically text or number) makes the flyout scroll.
![bf9bc2fe-391f-492c-b999-198465fbc66f](https://cloud.githubusercontent.com/assets/13686399/24223994/185157d6-0f16-11e7-8ea8-ab954a2c353e.gif)

**Comment by zgtm** [comment]
This bug is also triggered by resizing the browser window.

The bug can very easily be verified here: https://blockly-demo.appspot.com/static/demos/mirror/index.html

It can be triggered directly by calling `Blockly.mainWorkspace.flyout_.scrollbar_.resize()`

A very simple but hacky workaround is to insert the line

    hostMetrics.viewTop += 5;
right before 

    if (Blockly.Scrollbar.metricsAreEquivalent_(hostMetrics, this.oldHostMetrics_)) {
in `Blockly.Scrollbar.prototype.resize` ([blockly/core/scrollbar.js:398](https://github.com/google/blockly/blob/d919adb8560980a1604115f5624ae5b3fef0c99e/core/scrollbar.js#L398)). Tested in Chrome and Firefox under Linux.

It seems to be caused by some miscalculation or rounding error. Note that the fix only works with the number `5`. Using `4` makes it still scroll up (but slower), using `6` makes it scroll down.

**Comment by rachel-fenichel** [comment]
Yeah, there's something slightly wrong with our get and set metrics code for the flyout, and maybe for the main workspace.  I'm looking into it.  A few of these bugs have cropped up, and they're all related.

**Comment by rachel-fenichel** [comment]
Fixed by #1301
